### ISSUE TITLE
Benchmarking for Uber Calc

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#1000]
We have started the work of providing more comprehensive benchmarks for uber calc in #983. This is the tracking issue for what work we need to do 

https://hackmd.io/XuQCeNQGSS6ytS0KiIzSrg?both contains the details of what values we should be exporting.

- [x] Cleanup #983 and merge it
- [ ] Add missing values from the linked list above
- [ ] Rename existing outputs and inputs to adhere to the list above
- [ ] Switch the benchmarks we run on our benchmark server to these new ones, such that the values get auto generated

**Comment by vmx** [comment]
> Cleanup #983 and merge it

That's what I'm currently working on.

**Comment by nicola** [comment]
Old issue that I consider done.
