### ISSUE TITLE
Expose prometheus metrics from proofs library

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/rust-fil-proofs#1056]
### Description
Could rust-fil-proofs expose prometheus metrics for tracking of perf in a non-test/benchmark systems?

### Acceptance criteria

Desired metrics:
```
histogram porep_precommit_phase_1 by layer, sector_size
histogram porep_precommit_phase_2 by sector_size
histogram epost by sector_size
```

### Risks + pitfalls
Performance impact, maybe

**Comment by dignifiedquire** [comment]
There is a decent library for this here: https://github.com/tikv/rust-prometheus

**Comment by dignifiedquire** [comment]
We should probably integrate this into our `measure` functionality, and makeit a by default enabled feature flag.

**Comment by porcuquine** [comment]
@keyvank This might be valuable, but please confirm with @lanzafame that he still needs it (and close if not).

**Comment by cryptonemo** [comment]
Unclear if still needed, and prior work on this was discarded in #1210
