### ISSUE TITLE
Simplify `BucketSample[n, m]` construction

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#1067]
Described in page 22 of this [TR](https://web.stanford.edu/~bfisch/porep_short.pdf), this construction expands on the [`DRSample`](https://eprint.iacr.org/2017/443.pdf) algorithm to allow in-degrees bigger than two (the immediate predecessor and one random parent) by increasing the number of nodes and clustering them in groups of `m`, where `m` is the target in-degree. Over that meta-graph the original `DRSample` is called (`BucketSample[n]` in the TR, which only deals with the random parent, the immediate predecessor seems implicit in the construction) to produce many parents for the same meta-node.

This expanded algorithm has two issues in my view:

1. It's overly complicated, it introduces a new layer of abstraction (the meta-graph and the logic associated with navigating these expanded meta-nodes).

2. It allows a new undesired edge case that `DRSample` does not suffer from: a node can have itself as its parent. This happens when one of the nodes in the expanded meta-node is (randomly) assigned another node (close in distance) in its same meta-node (blue edge in this [diagram](https://i.imgur.com/ALt4fMx.png)).

Proposed solution: simplify `BucketSample[n, m]` as just a `m` repetitive calls to `BucketSample[n]` (`DRSample`). Some observations:

* `BucketSample[n, m]`/`BucketSample[n]` should then be converted to a call that doesn't generate the entire graph (of size `n`) but just the parents of a particular `i` node. This is already what our current implementation does (generate parents for only one node per call as needed).

* We [inject the node index `i` in the seed](https://github.com/filecoin-project/rust-fil-proofs/blob/14870d715f1f6019aba3f72772659e38184378bf/storage-proofs/src/drgraph.rs#L185) to have deterministic parents independent of call order (due to the way we implement `BucketSample[n, m]`, see point above). We won't need to inject the index [`k`](https://github.com/filecoin-project/rust-fil-proofs/blob/14870d715f1f6019aba3f72772659e38184378bf/storage-proofs/src/drgraph.rs#L188) of the nodes in the meta-node because we always request *all* the parents of a node at once, so the `m` *sequential* calls to `DRSample` will always have the same outcome.

* Calling many times `DRSample` for the same node allows for the (undesired) case of having the same parent for node `i` many times. This is already the case with `BucketSample[n, m]` (and also our current implementation): nodes in meta-node `i` might (independently) have parents from the same meta-node `j` that once collapsed into normal nodes (modulo operation in the pseudo-code of the TR) will mean it will have the same node `j` as parent more than once. The chances in both constructions are the same.

**Comment by porcuquine** [comment]
@schomatis Is it worth transferring this issue somewhere (research?) or should we just close? Implicit in this question is my assumption that this won't change further now that spec and audits are completed. (I'm not sure which parts of the above were implemented and which were not, either.)

**Comment by schomatis** [comment]
This was a product of a discussion with @DrPeterVanNostrand on the SDR spec, he should have more insight on the matter (and he may have already addressed this issue in a previous PR).

**Comment by dignifiedquire** [comment]
@DrPeterVanNostrand I am closing this issue, as I believe there is no further action needed from an implementation standpoint. Please let me know if there is still sth needed to be done.
