### ISSUE TITLE
Fix all clippy warning

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1123]
### Description

Currently CI isn't running the same clippy command as other repos (e.g. https://github.com/filecoin-project/filecoin-ffi/blob/6109b6ad2fa9968941c206161dd01ac059011d4e/.circleci/config.yml#L138). To catch all warnning this should be run:

    cargo clippy --all-targets --all-features -- -D warnings

In order to enable that on CI, all issues need to be fixed first

### Acceptance criteria

    cargo clippy --all-targets --all-features -- -D warnings

passes without any warning or errors

### Risks + pitfalls

This changes code everywhere, there might be merge conflicts with other open PRs.

### Where to begin

Where the first warning/error is.

**Comment by cryptonemo** [comment]
Thanks!
