### ISSUE TITLE
Use latest stable Rust 1.43 as default toolchain

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1142]
### Description

We currently also run the tests on Rust stable, so things should work.

I suggest moving away from nightly and using stable Rust instead. As a start I'd use the current stable version 1.43. We would put that into the `rust-toolchain` file instead of nightly. That way we would still make sure that everyone builds with the same version.

### Acceptance criteria

CI is green with 1.43 specified in `rust-toolchain`.

### Risks + pitfalls

The may be reasons why we are on nightly that I'm not aware of. Please @porcuquine, @laser or anyone else chime in if you know of such a reason.

I only remember that the FFI needed to be built with the same version, but it could well be a stable one IMHO.

Also the other related projects like filecoin-ffi need to be upgrade to the same toolchain.

### Where to begin

Edit the `rust-toolchain` file and fix errors if there are any.

**Comment by dignifiedquire** [comment]
It is likely fine for the moment, but we might have to switch to nightly at some point if we need to use inline assembly again.

**Comment by tcharding** [comment]
If we go for this, using v1.43, we will need to close https://github.com/filecoin-project/rust-fil-proofs/issues/390 because the lint required is only available in 1.45.

**Comment by vmx** [comment]
> we will need to close #390 because the lint required is only available in 1.45.

The lints `option_unwrap_used` and `result_unwrap_used` were [recently renamed to `unwrap_used`](https://github.com/rust-lang/rust-clippy/pull/5563#issue-412631541). So the original issue is especially right with v1.43, where those separate lints still existed.

**Comment by tcharding** [comment]
> > we will need to close #390 because the lint required is only available in 1.45.
> 
> The lints `option_unwrap_used` and `result_unwrap_used` were [recently renamed to `unwrap_used`](https://github.com/rust-lang/rust-clippy/pull/5563#issue-412631541). So the original issue is especially right with v1.43, where those separate lints still existed.

Oh, my mistake, I did not realise, I though they were new lints. Cheers.

**Comment by tcharding** [comment]
I think this can be closed now, [this recent commit](https://github.com/filecoin-project/rust-fil-proofs/commit/447a8ba76da224b8b5f9b7b8dd624ba9a6a107a6) updated `rust-toolchain` to stable `1.43.1`.
