### ISSUE TITLE
tree_r_last GPU error

### ISSUE THREAD

**Issue by deltazxm** [filecoin-project/rust-fil-proofs#1157]
### Description
2020-06-06T23:11:07.059 INFO storage_proofs_porep::stacked::vanilla::proof > processing config 3/8 with leaf nodes 700000 [63000000, 134217728, 331435456-332135456]
2020-06-06T23:11:07.110 INFO storage_proofs_porep::stacked::vanilla::proof > node index 63700000/700000/134217728
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotInField("0xffffffffffff0000ffffe954d9f899c0ffff9a4c000050000000000000000223")', /rust-fil-proofs/storage-proofs/core/src/hasher/poseidon.rs:406:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by xcshuan** [comment]
```rust
impl From<PoseidonDomain> for Fr {
    #[inline]
    fn from(val: PoseidonDomain) -> Self {
        Fr::from_repr(val.0).unwrap()
    }
}
```

I guess the value of input may not covered in Fr domain, as Fr just a subset of all 256-bit numbers.

**Comment by cryptonemo** [comment]
@xcshuan How was this error generated?

**Comment by xcshuan** [comment]
> @xcshuan How was this error generated?

I'm not sure, I've only seen this once.

**Comment by cryptonemo** [comment]
Ok, can you close for now and re-open if/when it's reproducible?

**Comment by porcuquine** [comment]
Were you running with fake data, maybe on a tree building test? If so, this just means you generated some bad data that wasn't in the field.

**Comment by xcshuan** [comment]
> Ok, can you close for now and re-open if/when it's reproducible?

I don't have the right to close the issue, you can close it.
