### ISSUE TITLE
About the adjustment of SDR parent cache

### ISSUE THREAD

**Issue by ElecRoastChicken** [filecoin-project/rust-fil-proofs#1173]
### Description
@dignifiedquire 
Dig, I've found that you're modifying partial caching for SDR, in this change, the cache will be stored on the disk, and it is local, not global. After our test, it will be very unbeneficial to run multiple sectors (such as 8 sectors) at the same time, because the IO speed of the SSD will become the bottleneck. I hope you can set local and global as optional options through the environment variable setting.

BTW, can you change the disk cache to asynchronous? This might reduce the time cost caused by IO.

**Comment by porcuquine** [comment]
@dignifiedquire Can you explain your logic clearly to the nice chicken?
