### ISSUE TITLE
Test feistel implementation is a valid permutation

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#1193]
### Description

We want to make sure that the current Feistel implementation has no bugs.

### Acceptance criteria

A test that checks if feistel is a valid permutation which tests a permutation of 2^30 nodes.

**Comment by porcuquine** [comment]
@keyvank I've assigned this to you.

I think the idea here is:

- create an array with sequential values.
- iterate over the array, replacing each element with its corresponding permutation value (make sure to use same keys every time).
- check to make sure all the original values are still represented, each exactly once.

If that isn't true, then we're not really permuting. If it is true, make sure you actually did something and are not just checking the original values.
