### ISSUE TITLE
Dead Code here?

### ISSUE THREAD

**Issue by Dizans** [filecoin-project/rust-fil-proofs#1200]
It seems that the `mpsc::sync_channel` call here does nothing.

https://github.com/filecoin-project/rust-fil-proofs/blob/00a8d958d401997353fd3523b4069b19c9cdc3a6/storage-proofs/porep/src/stacked/vanilla/proof.rs#L462

**Comment by porcuquine** [comment]
Good catch. #1201 addresses this.
