### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#1205]
# Support ARM

This epic issue is for top-level tracking of the 'support ARM' epic.

The following may be incomplete, but please add to it and mark completed as appropriate.

- [x] #1204 
- [ ] 'once we add space, if things do build in-full ( and work as advertised perf-wise ), may be worth considering providing precompiled stuff for a "golang-only" experience, just like with x86-64' — @ribasushi

**Comment by ribasushi** [comment]
Benchmarks comparing Arm to EPYC CPUs within the context of AWS: https://github.com/filecoin-project/rust-fil-proofs/issues/1224#issuecomment-663227253

**Comment by cryptonemo** [comment]
@ribasushi I think we're resolved on this now?

**Comment by ribasushi** [comment]
@cryptonemo this one is resolved yes. The lotus one - I will do one more retest later.

**Comment by ribasushi** [comment]
@cryptonemo I don't have perms to close
