### ISSUE TITLE
AMD EPYC 7R32 / AMD EPYC 7571 / AWS-ARM Neoverse-N1 NON-GPU benchmarks

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#1224]
I am linking to @ribasushi's ARM benchmarks here so it isn't lost if we want to find it later:

https://github.com/ribasushi/basic-aws-io-benchmark/compare/iobench_c6g.metal_2020-07-10_22-36-11..iobench_c5a.16xlarge_2020-07-10_22-36-00?diff=split&expand=1#diff-5357fbc60c60046048d7880e12e655b9

**Comment by ribasushi** [comment]
@porcuquine let's rename this to `AMD EPYC 7R32` / `AMD EPYC 7571` / `AWS-ARM Neoverse-N1` **NON-GPU** benchmarks

Once you go to the link above, at the very top you can switch the branches to compare as follows:

| Branch | Processor | # vCPUs | Ram | 512MiB Sector | 32GiB Sector |
| --- | --- | --- | --- | --- | --- |
| [`iobench_a1.metal_2020-07-07_17-39-53`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_a1.metal_2020-07-07_17-39-53) | Arm Cortex-A72 (AWS Graviton) | 16 | 32GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_a1.metal_2020-07-07_17-39-53/bench_lotus_sealing_512MiB.txt) | 
| [`iobench_c5a.8xlarge_2020-07-07_17-39-57`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_c5a.8xlarge_2020-07-07_17-39-57) | AMD EPYC 7R32 | 32 | 64GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_c5a.8xlarge_2020-07-07_17-39-57/bench_lotus_sealing_512MiB.txt) |
| [`iobench_c5a.16xlarge_2020-07-10_22-36-00`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_c5a.16xlarge_2020-07-10_22-36-00) | AMD EPYC 7R32 | 64 | 128GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_c5a.16xlarge_2020-07-10_22-36-00/bench_lotus_sealing_512MiB.txt) | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_c5a.16xlarge_2020-07-10_22-36-00/bench_lotus_sealing_32GiB.txt) |
| [`iobench_c6g.metal_2020-07-10_22-36-11`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_c6g.metal_2020-07-10_22-36-11) | Arm Neoverse-N1 (AWS Graviton2) | 64 | 128GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_c6g.metal_2020-07-10_22-36-11/bench_lotus_sealing_512MiB.txt) | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_c6g.metal_2020-07-10_22-36-11/bench_lotus_sealing_32GiB.txt) |
| [`iobench_r5a.4xlarge_2020-07-10_22-36-38`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_r5a.4xlarge_2020-07-10_22-36-38) | AMD EPYC 7571 | 16 | 128GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_r5a.4xlarge_2020-07-10_22-36-38/bench_lotus_sealing_512MiB.txt) | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_r5a.4xlarge_2020-07-10_22-36-38/bench_lotus_sealing_32GiB.txt) |
| [`iobench_r5ad.2xlarge_2020-07-07_18-15-56`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_r5ad.2xlarge_2020-07-07_18-15-56) | AMD EPYC 7571 | 8 | 64GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_r5ad.2xlarge_2020-07-07_18-15-56/bench_lotus_sealing_512MiB.txt) |
| [`iobench_r6g.2xlarge_2020-07-07_17-19-25`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_r6g.2xlarge_2020-07-07_17-19-25) | Arm Neoverse-N1 (AWS Graviton2) | 8 | 64GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_r6g.2xlarge_2020-07-07_17-19-25/bench_lotus_sealing_512MiB.txt) | 
| [`iobench_r6g.4xlarge_2020-07-10_22-36-49`](https://github.com/ribasushi/basic-aws-io-benchmark/tree/iobench_r6g.4xlarge_2020-07-10_22-36-49) | Arm Neoverse-N1 (AWS Graviton2) | 16 | 128GiB | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_r6g.4xlarge_2020-07-10_22-36-49/bench_lotus_sealing_512MiB.txt) | [✅ result](https://github.com/ribasushi/basic-aws-io-benchmark/blob/iobench_r6g.4xlarge_2020-07-10_22-36-49/bench_lotus_sealing_32GiB.txt) |

**Comment by porcuquine** [comment]
Renamed. Thank you.

**Comment by vmx** [comment]
Closing this issue as the information is preserved here, but there's no actionable item.
