### ISSUE TITLE
sha256 compress on arm64

### ISSUE THREAD

**Issue by ArthurZangCN** [filecoin-project/rust-fil-proofs#1227]
### Description
why has no function which use arm64 intrinsics like  sha256_intrinsics::compress256 ? so we test the time of the process on  AMD bigger than on ARM64 v8 .

**Comment by LuoZijun** [comment]
`asm` feature is required.

**Comment by ArthurZangCN** [comment]
> try enable `asm` feature on aarch64 platform.
> 
> Code: https://docs.rs/crate/sha2-asm/0.5.4/source/src/sha256_aarch64.S

是因为rust不支持arm64 v8吗？

**Comment by ArthurZangCN** [comment]
Is it because rust does not support arm64 v8?

**Comment by LuoZijun** [comment]
> > try enable `asm` feature on aarch64 platform.
> > Code: https://docs.rs/crate/sha2-asm/0.5.4/source/src/sha256_aarch64.S
> 
> 是因为rust不支持arm64 v8吗？

支持，只是没人写。汇编也一样。

**Comment by ArthurZangCN** [comment]
> > > try enable `asm` feature on aarch64 platform.
> > > Code: https://docs.rs/crate/sha2-asm/0.5.4/source/src/sha256_aarch64.S
> > 
> > 
> > 是因为rust不支持arm64 v8吗？
> 
> 支持，只是没人写。汇编也一样。

也是，看来就真的是因为硬件性能导致的了。

**Comment by LuoZijun** [comment]
> > > > try enable `asm` feature on aarch64 platform.
> > > > Code: https://docs.rs/crate/sha2-asm/0.5.4/source/src/sha256_aarch64.S
> > > 
> > > 
> > > 是因为rust不支持arm64 v8吗？
> > 
> > 
> > 支持，只是没人写。汇编也一样。
> 
> 也是，看来就真的是因为硬件性能导致的了。

汇编代码里面有使用到 AARCH64 里面的 `crypto` 指令集，对SHA256的运算有加速。你只是需要在 AARCH64 平台开启 `asm` 特性即可。
也就是说，目前代码对 aarch64 平台里面的 sha256 计算加速是支持的。

**Comment by dignifiedquire** [comment]
arm64 support should be there, if your processor supports it, if you build with a current rust nightly and `target-cpu=native`
