### ISSUE TITLE
GPU FFT failed!

### ISSUE THREAD

**Issue by ArthurZangCN** [filecoin-project/rust-fil-proofs#1236]
### Description
when i used GeForce GTX 1660 SUPER to run seal, the log printed error :

2020-07-30T15:31:11.818 INFO filecoin_proofs::api::seal > snark_proof:start
2020-07-30T15:31:11.819 INFO bellperson::groth16::prover > Bellperson 0.9.2 is being used!
2020-07-30T15:31:18.113 INFO bellperson::gpu::locks > GPU is available for FFT!
2020-07-30T15:31:18.750 INFO bellperson::gpu::fft > FFT: 1 working device(s) selected.
2020-07-30T15:31:18.751 INFO bellperson::gpu::fft > FFT: Device 0: GeForce GTX 1660 SUPER
2020-07-30T15:31:18.751 INFO bellperson::domain > GPU FFT kernel instantiated!
2020-07-30T15:31:18.792 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error: 

################################ OPENCL ERROR ############################### 

Error executing function: clCreateKernel("radix_fft")  

Status error code: CL_INVALID_PROGRAM_EXECUTABLE (-45)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateKernel.html#errors  

#############################################################################

**Comment by cryptonemo** [comment]
@ArthurZangCN Please see https://github.com/filecoin-project/bellman/#supported--tested-cards

**Comment by ArthurZangCN** [comment]
> @ArthurZangCN Please see https://github.com/filecoin-project/bellman/#supported--tested-cards

you means only support the cards in that list？ so my card  1660 SUPER do not support？

**Comment by cryptonemo** [comment]
> you means only support the cards in that list？ so my card 1660 SUPER do not support？

That looks correct.  It doesn't mean it can't be supported, you may be able to modify the code to work with it.  But it does not support it at this time.

**Comment by cryptonemo** [comment]
@ArthurZangCN Read the README linked above regarding custom cards not in the list.

**Comment by ArthurZangCN** [comment]
> > you means only support the cards in that list？ so my card 1660 SUPER do not support？
> 
> 
> 
> That looks correct.  It doesn't mean it can't be supported, you may be able to modify the code to work with it.  But it does not support it at this time.

thanks，if i want to modify the code to support my card， where is the hot codes？ please give me some guidance， driver or bellman's codes？

**Comment by cryptonemo** [comment]
@ArthurZangCN Is this issue resolved?  I believe everything you need to know is in the README referenced above.

**Comment by ArthurZangCN** [comment]
> @ArthurZangCN Is this issue resolved? I believe everything you need to know is in the README referenced above.

no，because i have no idea to resolved the error，now i am contact to nvidia fea，hope he could give me some advices.

**Comment by ArthurZangCN** [comment]
@cryptonemo no，because i have no idea to resolved the error，now i am contact to nvidia‘s FAE，hope could give me some advices by he.

**Comment by cryptonemo** [comment]
@ArthurZangCN Did you read the README linked above?  There's a setting to use `BELLMAN_CUSTOM_GPU` which "Will allow for adding a GPU not in the tested list. This requires researching the name of the GPU device and the number of cores in the format ["name:cores"]."

**Comment by ArthurZangCN** [comment]
@cryptonemo yes, i tried this setting before, but has no esolved the error.

**Comment by cryptonemo** [comment]
@ArthurZangCN Ok.  The last thing I can suggest in the meantime is to ask around on Slack and see if anyone has run into this or resolved it already.

**Comment by dignifiedquire** [comment]
The GeForce GTX 1660 SUPER has only 6GB of RAM, which is not enough for our needs, usually at least 8GB are required, so it is unlikely to be supported.
