### ISSUE TITLE
Where to find some V27 proofs params  such as 16KiB 1GiB

### ISSUE THREAD

**Issue by plotozhu** [filecoin-project/rust-fil-proofs#1250]
I am in optimized P2 and want to check different arties, but  only 2K/8M/512M/32G/64G  parameters' description in parameters.json. where can I find and download other parameters, such as 16KB 1G?

**Comment by askender** [comment]
similar issue when run `cargo run --release --bin gpu-cpu-test`:
```
thread 'low-01' panicked at 'thread 'failed to generate PoSt: No cached parameters found for proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331highthread '', ' panicked at 'low-02fil-proofs-tooling/src/bin/gpu-cpu-test/main.rsfailed to generate PoSt with high priority: No cached parameters found for proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331' panicked at ':', failed to generate PoSt: No cached parameters found for proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f33165fil-proofs-tooling/src/bin/gpu-cpu-test/main.rs', ::fil-proofs-tooling/src/bin/gpu-cpu-test/main.rs572:
```
I only have the file:
45G   /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params

**Comment by vmx** [comment]
You can create your own parameters for testing purpose via `cargo run --release --bin paramcache`.

**Comment by plotozhu** [comment]
> You can create your own parameters for testing purpose via `cargo run --release --bin paramcache`.

Thanks a lot, we will try this.

**Comment by vmx** [comment]
I close this issue as the issue seems to be solved.

**Comment by cryptonemo** [comment]
@askender Why v27 params instead of v28?

**Comment by vmx** [comment]
@cryptonemo because v28 weren't a thing back then.
