### ISSUE TITLE
May I ask which IDE or Editor you use to develop this project?

### ISSUE THREAD

**Issue by banishee** [filecoin-project/rust-fil-proofs#1255]
### Description
I use the Clion with Rust plugin. But it seems that many methods and packages couldn't be indexed.

**Comment by dignifiedquire** [comment]
emacs + rust-mode + [rust-analzyer](https://github.com/rust-analyzer/rust-analyzer)

**Comment by vmx** [comment]
vim + [vim.rust](https://github.com/rust-lang/rust.vim)

**Comment by banishee** [comment]
> emacs + rust-mode + [rust-analzyer](https://github.com/rust-analyzer/rust-analyzer)

thanks for your answer.

**Comment by banishee** [comment]
> vim + [vim.rust](https://github.com/rust-lang/rust.vim)

Thanks. But I don't like vim😂

**Comment by cryptonemo** [comment]
emacs + rust-mode

**Comment by cryptonemo** [comment]
@banishee Is there an issue here, or can this be closed?
