### ISSUE TITLE
integrity check for cached graphs

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#1264]
### Description

Hardware failures (bad RAM in the reported case) can lead to incorrect graph generation, and this can lead to a bad cache. Since graphs are constant per `porep_id`, per graph type, we should be able to provide a canonical digest and validate it before using a cache. If the cache is bad, regenerate the graph.

Context: https://github.com/filecoin-project/rust-fil-proofs/issues/1230#issuecomment-677663934

### Acceptance criteria

A bad graph cache doesn't lead to failure if current hardware produces a correct graph. Instead, the bad cache is replaced  by a newly-generated good one.

**Comment by Meatball13** [comment]
FYI - Checksums for proper cache files

sha256sum v28-sdr-parent-e1fa5d5b811ddbd118be3412c4a8c329156b8b8acc72632bca459455b5a05a13.cache
3c4f9841fcc75aed8c695800e58d08480629f25af3a2aefd81904181d75cc0b6  v28-sdr-parent-e1fa5d5b811ddbd118be3412c4a8c329156b8b8acc72632bca459455b5a05a13.cache

b2sum v28-sdr-parent-e1fa5d5b811ddbd118be3412c4a8c329156b8b8acc72632bca459455b5a05a13.cache
af6bac6fd4290e86fb3ea7449175f22c810dc57dafe4189e7ee6b0daa70bcee007435e63e85cea05d0a02d5923b84079fba15092440808cfb8e6f1ccabbbd0f3  v28-sdr-parent-e1fa5d5b811ddbd118be3412c4a8c329156b8b8acc72632bca459455b5a05a13.cache
