### ISSUE TITLE
Window PoSt challenge generation should not depend on sector order

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#1270]
### Description

Window PoSt challenge generation currently depends on the ordering of provided sectors.

This is considered to be a 'protocol bug' in that this is the behavior which has been specified and audited. However, it allows for miners to influence challenges by shuffling their sectors. One possible (and probably cleanest) solution is to make challenge-generation independent of sector ordering — at the cost of a breaking change (so extant Window PoSts would not verify with the new code, requiring a network reset or proofs upgrade).

In the current code, the function `generate_leaf_challenges` *appears* to do the right thing, but this function is only called from Election PoSt so is not actually used. https://github.com/filecoin-project/rust-fil-proofs/blob/4a07a868d077f5926b23c3f913f99d8b46b8cebc/storage-proofs/post/src/fallback/vanilla.rs#L192-L211

Notice, however, that in `generate_public_input` for Fallback PoSt, `challenge_index` depends on `i` (the sector's index within the submitted partition). This must *not* be the case. https://github.com/filecoin-project/rust-fil-proofs/blob/4a07a868d077f5926b23c3f913f99d8b46b8cebc/storage-proofs/post/src/fallback/compound.rs#L68-L76 Instead, the `challenge_index` can just be `n`. Each sector's challenge indexes should range from 0 to `challenge_count`.

The same can be seen in the vanilla proof: https://github.com/filecoin-project/rust-fil-proofs/blob/4a07a868d077f5926b23c3f913f99d8b46b8cebc/storage-proofs/post/src/fallback/vanilla.rs#L324-L333

### Acceptance criteria

Window PoSt challenge generation does not depend on the ordering of provided sectors.

### Risks + pitfalls

This will be a *breaking change* to proofs: a proof generated with the previous Window PoSt will not verify. Therefore, we will *either*:
- need a network reset; or
- need a proofs upgrade (with new RegisteredProof for modified Window PoSt).

This decision must be made at the project level, and we can support either path. If the proofs upgrade is selected, a new issue should be created; and both that new issue and the current should be addressed in the PR realizing this work.

Note that *because Winning PoSt uses only a single partition*, this change should not affect Winning PoSt challenge generation. Therefore, we don't technically need a new RegisteredProof. We should at least verify that this is true if we opt for a proofs upgrade.

In that case, we must either actually upgrade Winning PoSt also (which may be simplest) — or else explicitly verify that old Winning PoSt proofs still pass (and that challenge generation is unaffected).

### Where to begin

- vanilla proof: https://github.com/filecoin-project/rust-fil-proofs/blob/4a07a868d077f5926b23c3f913f99d8b46b8cebc/storage-proofs/post/src/fallback/vanilla.rs#L324-L333
- circuit input generation: https://github.com/filecoin-project/rust-fil-proofs/blob/4a07a868d077f5926b23c3f913f99d8b46b8cebc/storage-proofs/post/src/fallback/compound.rs#L68-L76

**Comment by porcuquine** [comment]
cc: @nicola @cryptonemo @magik6k @whyrusleeping @daviddias @momack2.

**Comment by cryptonemo** [comment]
This was addressed in 2 PRs in different ways that didn't land:

https://github.com/filecoin-project/rust-fil-proofs/pull/1284
https://github.com/filecoin-project/rust-fil-proofs/pull/1286

Re-open if this remains an issue.
