### ISSUE TITLE
Document FIL_PROOFS_USE_FIL_BLST

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#1279]
### Description

README should be updated to document the `use_fil_blst` setting and corresponding `FIL_PROOFS_USE_FIL_BLST` env var. This through the cracks in #1271.

**Comment by vmx** [comment]
Not all settings from `rust-fil-proofs.config.toml.sample` are documented in the README, but I agree to document that one. The documented settings have quite a bit if explanation around them. I'd say it's better suited to be written by someone who knows all the implications. Hence assigning it to @porcuquine.

**Comment by dignifiedquire** [comment]
this option is gone in the latest release
