### ISSUE TITLE
Should NSE Window-PoSt have public-inputs for each replica's layer roots?

### ISSUE THREAD

**Issue by DrPeterVanNostrand** [filecoin-project/rust-fil-proofs#1298]
[Currently](https://github.com/filecoin-project/rust-fil-proofs/blob/8a17bc87e68506508695219e5a8bfbd3ba8a1d33/storage-proofs/post/src/nse_window/circuit.rs#L171-#L222), a Window-PoSt SNARK has public inputs for each replica's  `comm_r` and `comm_layers`. This means that both a SNARK's prover and verifer will input `comm_r` and `comm_layers` and equality constraints will assert equality between them [the prover and verifier's public-inputs]. After these public-input checks, our Window-PoSt circuit performs an additional check that `poseidon(comm_layers) = comm_r`.

It may be possible to remove `comm_layers` from the public-inputs and rely solely on `comm_r` as a public-input. In this scenario, the prover witnesses `comm_layers`, the circuit checks that `poseidon(comm_layers) = comm_r`, and each Merkle proof is checked to be consistent with the witnessed last layer root to show consistency with the public `comm_r`.

**Comment by porcuquine** [comment]
Correct. The layer commitments should definitely not be public inputs. `comm_r` should be the public input. It should be produced by a hash of (for lack of better names) `comm_c` and `comm_r_last`. That way, only `comm_c` need be stored in `p_aux` (persistent auxiliary data retained by the prover), passed as private inputs to the circuit, and hashed with `comm_r_last` to open `comm_r`. Then `comm_r_last` may be used as the root in Window PoSt.

**Comment by DrPeterVanNostrand** [comment]
Closing in favor of Issue #1310
