### ISSUE TITLE
NSE Window-PoSt Optimizations

### ISSUE THREAD

**Issue by DrPeterVanNostrand** [filecoin-project/rust-fil-proofs#1310]
**Optimization 1** - remove public inputs for `layer_1_root`, ..., `layer_15_root`
1. Define `comm_14 = poseidon_14(layer_1_root, ..., layer_14_root)`
2. Redefine `comm_r = poseidon_2(comm_14, layer_15_root)`
3. Remove `layer_1_root, ..., layer_15_root` from the circuit's public inputs (while retaining `comm_r`) 
4. Add witnesses for `comm_14` and `layer_15_root`
5. Prove that the witnesses are consistent with the public `comm_r`
6. Prove that each Merkle proof is consistent with `layer_15_root`

Q. How will redefining `comm_r` affect the PoRep (e.g. `paux`)?
Q. Is it possible to make arity-14 poseidon constants? E.g.
```
pub static ref POSEIDON_CONSTANTS_14_BASE: PoseidonConstants::<Bls12, U14> =
    PoseidonConstants::new_constant_length(14);
```

**Optimization 1 Alternative**

The verifier inputs a single public-input, the digest (calculated outside of the circuit) of every`comm_r` for a given Window-PoSt partition: `comm_r_all = poseidon_n(comm_r_1, ..., comm_r_n)` where: `n` is the number of replicas challenged per Window-PoSt partition. 

Q. Is it possible to make an arity `n` Poseidon hash function (non-circuit)?

**Optimization 2** - pack multiple challenges into a single public input

NSE Merkle challenges are a 27-bit integers (`n_nodes_per_window = 2^27`). Currently, each Merkle challenge is one public input. But, a single public input is capable of representing 2^254 bits. Therefore, 9 challenges can be packed into a single public input (`254 bits per public input / 27 bits per challenge = 9 challenge per public input`).

1. For each chunk of 9 challenges `c_1, ..., c_9`, add a public input for the packing of the 9 challenge chunk (e.g. `Fq::from_bits_lsb(to_27_bits_lsb(c1) || ... || to_27_bits_lsb(c9))`)
2. Witness the least significant 243 bits of each public input (adding an equality constraint between each input and its witnessed binary representation)
3. To validate the i-th Merkle proof in the partition, use the `floor(i / 9)`-th public input's `i % 9`-th range of 27 bits (the i-th challenge's bits). Each 3-bit chunk (1 octal digit) of the 27-bit chunk will represent a path element's "missing" index. Hash each Merkle proof's path using the challenge's public 27-bit auth-path, assert equality between the calculated root at the witnessed (previously proved) `layer_15_root`.

**Optimization 3** - challenge-set derivation must be independent of replica-set ordering

Currently, the challenges are derived using their absolute challenge-index across all partitions, replicas, and windows in a Window-PoSt. Challenge derivation should only depend on a challenge's index within its replica. E.g.

```
digest_bytes: [u8; 32] = sha256(randomness || sector_id || challenge_index_in_replica)
digest_int = LittleEndian::read_u64(&digest_bytes)
challenge = digest_int % n_nodes_per_window
```

**Comment by cryptonemo** [comment]
No longer needed
