### ISSUE TITLE
NSE PoRep paritions use the same challenge-set

### ISSUE THREAD

**Issue by DrPeterVanNostrand** [filecoin-project/rust-fil-proofs#1314]
NSE PoRep is multi-partition, where each partition should have a unique challenge-set. [Currently](https://github.com/filecoin-project/rust-fil-proofs/blob/feat/nse-post/storage-proofs/porep/src/nse/vanilla/proof_scheme.rs#L117), the same challenge-set is used for every partition in a vanilla PoRep because each partition creates an identical instance of `Challenges` via. `clone`.

Pseudocode describing current implementation:

```rust
fn NarrowStackedExpander::prove_all_partitions() {
    let challenges = Challenges::new();
    for partition in 0..partition_count {
        for (layer_challenge_index, layer_challenge) in challenges.clone().enumerate() {
            ...
        }
    }
}
```

Each challenge's value in a partition is dependent on its index within the partition, as opposed to it's index across all partitions.

Q. Should challenge derivation instead be dependent on a challenge's index across all partitions in a PoRep ([similarly to SDR](https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs/porep/src/stacked/vanilla/challenges.rs#L46))?

**Comment by cryptonemo** [comment]
No longer needed
