### ISSUE TITLE
PC1 takes much longer time(≈140min/layer) with 1.46 rustup compilation 

### ISSUE THREAD

**Issue by firesWu** [filecoin-project/rust-fil-proofs#1324]
### Description
It takes much longer time to finish PC1, both for real sealing and benching, when we compile with rustup version 1.46. It is normal if we complied with rustup version 1.45 OR 1.47

**Comment by dignifiedquire** [comment]
that should not be the case, what flags are you using, and what architecture, and what commit of proofs?

**Comment by cryptonemo** [comment]
Closing due to lack of feedback.
