### ISSUE TITLE
WinningPost blocked by PC2

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/rust-fil-proofs#1334]
Today my miner missed it's first and only opportunity to mine a block. It took 99 seconds. Looking at the logs closer my miner was doing PC2s on the GPU. I think WindowPosts suspend any operation until the finish as they are high priority. You really should make WinningPost the same high priority, otherwise sector sealing will just always murder the possibility of mining a block.

**Comment by porcuquine** [comment]
This is definitely on the roadmap. The safe strategy right now is to reserve a GPU for this purpose, but that's obviously annoying if you win too infrequently.

I can detour on the route to multi-GPU scheduling and implement the preemption component for tree building before finalizing the rest. There is still a little preparatory work that has to land first, but you have been heard.

**Comment by karalabe** [comment]
Yeah, so it's not PC2 blocking. Apparently this op takes 1.5 minutes on my 3080. https://github.com/filecoin-project/rust-fil-proofs/issues/1355

**Comment by vmx** [comment]
GPU priority locking has been implemented quite a long time ago, hence closing this issue.
