### ISSUE TITLE
refactor: improve and unify binaries

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#1345]
Our binaries needs some love, they should all use 

- the same logger (pretty-env-logger, with timed option)
- humansized inputs and outputs for byte amounts
- structopt for parameter handling
- unified parameter naming

**Comment by vmx** [comment]
I propose using https://github.com/filecoin-project/rust-fil-logger/ for logging, which is more or less a configuration for `flexi_logger`. Advantage is that it has a JSON output which is compatible with the logging Lotus. Which might be useful for some.

**Comment by dignifiedquire** [comment]
@vmx does it provide colored output for the log levels when using the regular output?

**Comment by vmx** [comment]
> @vmx does it provide colored output for the log levels when using the regular output?

Coloured on the console, uncoloured if you pipe it into something :)

**Comment by dignifiedquire** [comment]
Fixed on `master`
