### ISSUE TITLE
Restore ability to build on aarch64

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/rust-fil-proofs#1351]
### Description
During the last month a number of improvements were merged that no longer compile on aarch64 (arm).
 
### Acceptance criteria
The project once again builds on arm, like it did around the start of October 2020.

### Risks + pitfalls
N/A

### Where to begin
I put together a repro box for the dev-team (announced privately). The current repro steps are:
```
git clone https://github.com/filecoin-project/rust-fil-proofs
cd rust-fil-proofs
echo "nightly-2020-10-05" > rust-toolchain
cargo build --release --all 2>&1 | tee ~/rfp_build.log
```

Current first failure (others are expected) is:
```
...
   Compiling bellperson v0.12.0
   Compiling fil_logger v0.1.2
error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bellperson-0.12.0/src/groth16/multiscalar.rs:268:19
    |
265 | fn prefetch<T>(p: *const T) {
    |             - this type parameter
...
268 |         _prefetch(p, _PREFETCH_READ, _PREFETCH_LOCALITY3);
    |                   ^ expected `i8`, found type parameter `T`
    |
    = note: expected raw pointer `*const i8`
               found raw pointer `*const T`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `bellperson`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by dgbo** [comment]
Hi, we also encountered this problem today.

We have a solution, see: https://github.com/filecoin-project/bellperson/pull/129

Local tests are good. Hope this would address your problem too. Thanks.

**Comment by dignifiedquire** [comment]
Thank you @dgbo I have merged and released that patch with `bellperson@0.12.1`. 
Confirmed on the test machine that this indeed fixes things so they compile again :)

**Comment by dgbo** [comment]
@dignifiedquire Wow, thanks a lot for the quickly review and approvement.

**Comment by dignifiedquire** [comment]
closing, tracking ci setup in #1353
