### ISSUE TITLE
No  rust-fil-proofs/storage-proofs/core/src/proof.rs info log output

### ISSUE THREAD

**Issue by ProgramAPE** [filecoin-project/rust-fil-proofs#1371]
I want to debug the WindowPost.
But I found no rust-fil-proofs/storage-proofs/core/src/proof.rs info log output
when do the windowpost.
`        let vanilla_proofs = S::prove_all_partitions(
            &pub_params.vanilla_params,
            &pub_in,
            priv_in,
            partition_count,
        )?;
`

the infos in the S::prove_all_partitions never log out . Why?

**Comment by vmx** [comment]
Do you see other log output? Which information would you like to see logged?

**Comment by ProgramAPE** [comment]
@vmx sorry I just see the wrong place which impl the ProofSchema
