### ISSUE TITLE
Improve phase2 ignored tests

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/rust-fil-proofs#1379]
### Description

The ignored filecoin-phase2 tests always fail, unless the 'phase1radix2m10' file is present locally.  Since this file is too large to be practically checked into our repo, it generally cannot exist, yet it causes a 'run all ignored tests' from the top-level to fail.  This is not ideal, as that only discourages anyone from running the ignored tests, which coincidentally contain most of the 'interesting' code that needs to be tested.  Some options to fix this are to either 1) add a feature that conditionally compiles out the tests (although this leads to warnings, since all of the tests appear to require the input files), 2) re-factor the tests so that they are CLI programs that can verify correctness and be run manually when the input file is present, or 3) simply move this crate into it's own repo, so that testing the main proofs repo does not affect any requirements for this repo's testing.

### Acceptance criteria

All `rust-fil-proofs` ignored tests run from the top-level should pass.

### Where to begin

Consider the above options (or others).

**Comment by cryptonemo** [comment]
For this one, I think it's a straight-forward change to create a new filecoin-phase2 repo and move the contents of phase2 (with slight modifications to Cargo.toml) out of rust-fil-proofs.  Thoughts?

**Comment by dignifiedquire** [comment]
sounds good to me

**Comment by cryptonemo** [comment]
> sounds good to me

Good deal.  If moved to a separate crate, with the minor changes mentioned applied, does this require a newly published crate (assuming patch version), or should we wait until substantial changes occurred?  Honestly not sure about this case.  It does physically change being a separate repo, but doesn't do anything for end-user consumption.

**Comment by dignifiedquire** [comment]
I think we should probably do a patch release, so we have a crate published from the right location, with updated links in `Cargo.toml`

**Comment by cryptonemo** [comment]
I've got a repo going here: https://github.com/cryptonemo/filecoin-phase2

If all looks good, I'll create the release.

**Comment by cryptonemo** [comment]
filecoin-phase2 has been moved to a new repo: https://github.com/filecoin-project/filecoin-phase2
filecoin-phase2 has been released as as `v1.0.1` on crates.io
phase2 has been removed from rust-fil-proofs.
