### ISSUE TITLE
Fix broken GPU locking

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/rust-fil-proofs#1380]
### Description

GPU lock contention is flaky, as it sometimes works and sometimes doesn't.  It seems to be most problematic when trying to prove snarks on machines without a GPU.  The locking/serialization for the GPU column and tree builders is also not reliable, as it can cause hangs when running all ignored tests (by default, in parallel) when the GPU column and tree builders are enabled.  Running the tests in parallel with the GPU column/tree builders enabled doesn't generally make sense, as the trees are so small, they are likely going to be slower than CPU building in parallel, however, the locking shouldn't fail by hanging either.

### Acceptance criteria

All tests using GPU pass without hanging

### Where to begin

Proper multi-gpu support is slated to improve or resolve this situation.

**Comment by cryptonemo** [comment]
Note that this issue was originally created when running tests would hang, however the issue is showing up in production for miners.

**Comment by cryptonemo** [comment]
Very likely related to https://github.com/filecoin-project/bellperson/issues/146

**Comment by cryptonemo** [comment]
This will be resolved by filecoin-project/bellperson#150

**Comment by dignifiedquire** [comment]
can this be closed?

**Comment by cryptonemo** [comment]
> can this be closed?

Yes, thanks.  Resolved with https://github.com/filecoin-project/bellperson/pull/150
