### ISSUE TITLE
PC2 panic at release 6.0

### ISSUE THREAD

**Issue by yydfjt** [filecoin-project/rust-fil-proofs#1385]
### Description

thread '<unnamed>' panicked at 'failed to flatten and write store: Bad file descriptor (os error 9)', /rust-fil-proofs/storage-proofs/porep/src/stacked/vanilla/proof.rs:641:26
thread '<unnamed>' panicked at 'failed to send base_data, tree_data: "SendError(..)"', /rust-fil-proofs/storage-proofs/porep/src/stacked/vanilla/proof.rs:592:34
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /rust-fil-proofs/storage-proofs/porep/src/stacked/vanilla/proof.rs:544:34
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /rust-fil-proofs/storage-proofs/porep/src/stacked/vanilla/proof.rs:549:53

**Comment by cryptonemo** [comment]
Please see https://github.com/filecoin-project/rust-fil-proofs#advanced-gpu-usage

In particular, the `FIL_PROOFS_COLUMN_WRITE_BATCH_SIZE` setting.

**Comment by cryptonemo** [comment]
Re-open if you can't find a resolution using the ulimit or env setting, with more specific information.
