### ISSUE TITLE
Audit and improve unseal for performance

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#1402]
`unseal` has not gotten as much attention yet, and there is likely more things we can do. 

- avoid a second copy: https://github.com/filecoin-project/rust-fil-proofs/pull/1401
- use mmap, instead of in memory https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/mod.rs#L156-L157
- others?

**Comment by cryptonemo** [comment]
Related work:

https://github.com/filecoin-project/rust-fil-proofs/pull/1401
https://github.com/filecoin-project/filecoin-ffi/pull/162
