### ISSUE TITLE
Unable to compile sha2raw:2.1.0 on ARM platform

### ISSUE THREAD

**Issue by dbshch** [filecoin-project/rust-fil-proofs#1442]
### Description

The commit #1394 introduced a problem in the sha2raw crate:
On ARM platform, the mod sha256_intrinsics can't be imported.

error[E0432]: unresolved import crate::sha256_intrinsics
--> sha2raw/src/platform.rs:1:13
|
1 | use crate::{sha256_intrinsics, sha256_utils};
| ^^^^^^^^^^^^^^^^^ no sha256_intrinsics in the root

**Comment by cryptonemo** [comment]
Build issue resolved by https://github.com/filecoin-project/rust-fil-proofs/pull/1444

**Comment by cryptonemo** [comment]
Resolved by #1457
