### ISSUE TITLE
failed to create metadata

### ISSUE THREAD

**Issue by exciting678** [filecoin-project/rust-fil-proofs#1446]
Hi,

My system is MacOS, when I run "cargo build --release --all", the result show:

---- metadata::tests::test_metadata stdout ----
thread 'metadata::tests::test_metadata' panicked at 'failed to create metadata: could not find repository from '/Users/lujing/Documents/WorkSpace/rust-fil-proofs-master/fil-proofs-tooling'; class=Repository (6); code=NotFound (-3)', fil-proofs-tooling/src/metadata.rs:135:36

what's the problem? Thanks a lot.

**Comment by vmx** [comment]
`fil-proofs-tooling` gets some information from your `.git` directory. Can you double check that you have one in your `rust-fil-proofs-master` directory?

**Comment by exciting678** [comment]
> `fil-proofs-tooling` gets some information from your `.git` directory. Can you double check that you have one in your `rust-fil-proofs-master` directory?

Yes, I have a .git directory in `rust-fil-proofs-master directory`, thanks.

**Comment by vmx** [comment]
@exciting678 and you still get this error?

**Comment by exciting678** [comment]
> @exciting678 and you still get this error?

Yes, but after I reload

**Comment by exciting678** [comment]
@vmx Hi, I have solved the problem by download the project again with command `git clone`,  but I downloaded the zip file before. Thanks.

**Comment by vmx** [comment]
So it would be good if the compilation of the tools would either provide a better error, or (even better) have a fallback in case there is no Git repository available.

**Comment by cryptonemo** [comment]
@vmx If we're good to close here (perhaps with a new issue), please do.

**Comment by vmx** [comment]
I would just keep the issue open instead of creating a new one as it still accurately describes the issue and a potential fix.

**Comment by vmx** [comment]
I think this has been fixed with https://github.com/filecoin-project/rust-fil-proofs/pull/1688. If not, feel free to re-open this issue.
