### ISSUE TITLE
Next Proofs Release

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/rust-fil-proofs#1484]
### Description

Target Aug 12.
_NOTE: Our timeline advanced because we are trying to target 2 different proofs releases in the same lotus rc tagging timeframe (with one being a fallback for the other in case it's not reached, or has issues specific to the changes)._

PRs targeting the next proofs release (`v9.0.0`):

- [X] Bellperson 0.15.0
- [x] rust-gpu-tools release (optionally with https://github.com/filecoin-project/rust-gpu-tools/pull/46)
- [x] https://github.com/filecoin-project/bellperson/pull/187
- [x] Bellperson 0.16.0 (minor release required after merging above)
- [x] https://github.com/filecoin-project/neptune/pull/91
- [x] Neptune 4.0.0 release required with updated `bellperson` and `rust-gpu-tools`
- [x] https://github.com/filecoin-project/rust-fil-proofs/pull/1485
- [x] Review and merge https://github.com/filecoin-project/rust-gpu-tools/pull/47 and do a 0.4.1 release
- [X] https://github.com/filecoin-project/bellperson/pull/204
- [X] Bellperson 0.16.1 (patch release required after merging above)
- [X] https://github.com/filecoin-project/rust-fil-proofs/pull/1482
- [X] ~~Rust GPU tools update: https://github.com/filecoin-project/rust-fil-proofs/pull/1480~~ See #1482 
- [X] Replace `rayon` threadpool usage outside of `par_iter`: https://github.com/filecoin-project/rust-fil-proofs/pull/1483
- [x] Complete testing, review and/or rebase: https://github.com/filecoin-project/rust-fil-proofs/pull/1477
- [x] Release proofs `v9.0.0` after merging outstanding PRs above
- [x] https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/58
- [x] Release proofs-api `v9.0.0` after merging https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/58
- [x] Drop FFI optional `blst` support, and add optional `pairing` support: https://github.com/filecoin-project/filecoin-ffi/pull/192
- [x] Not proofs specifically, but related work: https://github.com/filecoin-project/filecoin-ffi/pull/179
- [x] Tracking issue for swapping `pairing` with `blst`: https://github.com/filecoin-project/rust-fil-proofs/issues/1438

### Acceptance criteria

Aug 12 take stock of where we are and see what is remaining that may make the release.  Cut `v9.0.0`.  Start next proofs release cycle (dropping pairing and using upstream deps).  Tracking issue for `v10.0.0` to be made after `v9.0.0` release.

### Risks + pitfalls

Hard deadline is Aug 16, in order to make it into the next `lotus` release cycle.

**Comment by vmx** [comment]
I've added https://github.com/filecoin-project/rust-gpu-tools/pull/47 to the list. It fixes an issue with discovering AMD devices.

**Comment by cryptonemo** [comment]
Resolved!  Last update for integrating Proofs v9.0.1 is here: https://github.com/filecoin-project/lotus/issues/7109
