### ISSUE TITLE
What the relationship between tree_c and tree_r_last?

### ISSUE THREAD

**Issue by ProgramAPE** [filecoin-project/rust-fil-proofs#1487]
I just curious can I do the tree-r-last before the tree-c?
I read the source code. It seems tree-r and tree-c has no relation.
but when I do the tree-r-last before tree-c I got the different sealed id.
Can someone tell me why?

**Comment by Leozhang404** [comment]
yes, They are independent processes that can be done in parallel.

**Comment by Leozhang404** [comment]
> I just curious can I do the tree-r-last before the tree-c?
> I read the source code. It seems tree-r and tree-c has no relation.
> but when I do the tree-r-last before tree-c I got the different sealed id.
> Can someone tell me why?

yes, They are independent processes that can be done in parallel.

**Comment by ProgramAPE** [comment]
> > I just curious can I do the tree-r-last before the tree-c?
> > I read the source code. It seems tree-r and tree-c has no relation.
> > but when I do the tree-r-last before tree-c I got the different sealed id.
> > Can someone tell me why?
> 
> yes, They are independent processes that can be done in parallel.

If you do then in parallel you will get different result

**Comment by Leozhang404** [comment]
can you reproduce it ?

**Comment by ProgramAPE** [comment]
> can you reproduce it ?

I am sure I can reproduce it. After you do it you should compare the sealedIds. They are different.

**Comment by Leozhang404** [comment]
for the same sectorID?

can you paste some operation and  result?

**Comment by ProgramAPE** [comment]
> for the same sectorID?
> 
> can you paste some operation and result?

It's my mistake that write some wrong code.  the tree_c and tree_r_last are independent. has nothing to do with each other.
