### ISSUE TITLE
Cuda setting not working for RTX 1080 Ti with C2 Worker

### ISSUE THREAD

**Issue by William8Work** [filecoin-project/rust-fil-proofs#1524]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
$ lotus version && lotus-miner version
Daemon:  1.13.0-rc2+mainnet+git.530011fd0+api1.4.0
Local: lotus version 1.13.0-rc2+mainnet+git.530011fd0
Daemon:  1.13.0-rc2+mainnet+git.530011fd0+api1.2.0
Local: lotus-miner version 1.13.0-rc2+mainnet+git.530011fd0

Machine:
Intel E5-2670, RTX 1080 Ti, Ubuntu 20.04, Nvidia driver 460.73.01,
```

### Describe the Bug

When using the cuda setting with this lotus version (compiled with FFI_USE_CUDA=1 flag), the specific GPU (RTX 1080 Ti) is not able to perform the C2 sealing task:

```
Oct 12 11:20:29 g1wrk06 lotus-worker[553954]: 2021-10-12T11:20:29.135 DEBUG bellperson::gpu::locks > GPU lock acquired!
Oct 12 11:20:29 g1wrk06 lotus-worker[553954]: 2021-10-12T11:20:29.135 ERROR bellperson::gpu::fft > Cannot initialize kernel for device 'GeForce GTX 1080 Ti'! Error: GPUError: CUDA framework is not supported, please compile with the `cuda` feature enabled.
Oct 12 11:20:29 g1wrk06 lotus-worker[553954]: 2021-10-12T11:20:29.135 DEBUG bellperson::gpu::locks > GPU lock released!
Oct 12 11:20:29 g1wrk06 lotus-worker[553954]: 2021-10-12T11:20:29.135 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
```

Please note: the same version of software (v1.13.0-rc2) with cuda is working fine with other GPUs I had (RTX 3090).

### Logging Information

```text
Cuda has been installed properly:

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

And here is the environment setting when lotus is compiled with FFI_USE_CUDA=1 flag:

export CGO_CFLAGS="-D__BLST_PORTABLE__"
export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
export GOPATH=/home/filecoin/filecoin/go
export PATH=/home/filecoin/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/bin:/usr/local/cuda-11.2/bin

export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64
export CUDA_HOME=/usr/local/cuda
export BELLMAN_CUDA_NVCC_ARGS="--fatbin --gpu-architecture=sm_61 --generate-code=arch=compute_61,code=sm_61"
export NEPTUNE_CUDA_NVCC_ARGS="--fatbin --gpu-architecture=sm_61 --generate-code=arch=compute_61,code=sm_61"
export FFI_USE_CUDA=1



If the lotus is compiled without using the FFI_USE_CUDA=1 flag, the C2 will work and here is the log:

Oct 12 13:43:29 g1wrk06 lotus-worker[568686]: 2021-10-12T13:43:29.218 INFO filecoin_proofs::api::seal > snark_proof:start
Oct 12 13:43:29 g1wrk06 lotus-worker[568686]: 2021-10-12T13:43:29.239 INFO bellperson::groth16::prover > Bellperson 0.17.0 is being used!
Oct 12 13:46:10 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:10.916 INFO bellperson::groth16::prover > synthesis time: 161.676594979s
Oct 12 13:46:10 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:10.916 INFO bellperson::groth16::prover > starting proof timer
Oct 12 13:46:25 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:25.522 DEBUG bellperson::groth16::prover > get h
Oct 12 13:46:25 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:25.825 INFO bellperson::gpu::locks > GPU is available for FFT!
Oct 12 13:46:25 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:25.825 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/media/lotus/cache/tmpdir/bellman.gpu.lock" ...
Oct 12 13:46:25 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:25.825 DEBUG bellperson::gpu::locks > GPU lock acquired!
Oct 12 13:46:25 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:25.825 INFO bellperson::gpu::program > Using kernel on OpenCL.
Oct 12 13:46:26 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:26.161 INFO bellperson::gpu::fft > FFT: 1 working device(s) selected.
Oct 12 13:46:26 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:26.161 INFO bellperson::gpu::fft > FFT: Device 0: GeForce GTX 1080 Ti
Oct 12 13:46:26 g1wrk06 lotus-worker[568686]: 2021-10-12T13:46:26.161 INFO bellperson::domain > GPU FFT kernel instantiated!

Oct 12 13:57:31 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:31.994 DEBUG bellperson::gpu::locks > GPU lock released!
Oct 12 13:57:31 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:31.994 DEBUG bellperson::groth16::prover > multiexp h
Oct 12 13:57:31 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:31.994 INFO bellperson::gpu::locks > GPU is available for Multiexp!
Oct 12 13:57:31 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:31.994 DEBUG bellperson::gpu::locks > Acquiring GPU lock at "/media/lotus/cache/tmpdir/bellman.gpu.lock" ...
Oct 12 13:57:31 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:31.994 DEBUG bellperson::gpu::locks > GPU lock acquired!
Oct 12 13:57:31 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:31.994 DEBUG bellperson::groth16::prover > get l
Oct 12 13:57:32 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:32.000 INFO bellperson::gpu::program > Using kernel on OpenCL.
Oct 12 13:57:32 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:32.264 INFO bellperson::gpu::multiexp > Multiexp: 1 working device(s) selected. (CPU utilization: 0)
Oct 12 13:57:32 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:32.264 INFO bellperson::gpu::multiexp > Multiexp: Device 0: GeForce GTX 1080 Ti (Chunk-size: 6167411)
Oct 12 13:57:32 g1wrk06 lotus-worker[568686]: 2021-10-12T13:57:32.264 INFO bellperson::multiexp > GPU Multiexp kernel instantiated!
Oct 12 14:09:37 g1wrk06 lotus-worker[568686]: 2021-10-12T14:09:37.771 DEBUG bellperson::groth16::prover > multiexp l
Oct 12 14:09:37 g1wrk06 lotus-worker[568686]: 2021-10-12T14:09:37.771 DEBUG bellperson::groth16::prover > get_a b_g1 b_g2
Oct 12 14:19:56 g1wrk06 lotus-worker[568686]: 2021-10-12T14:19:56.857 DEBUG bellperson::groth16::prover > get_a b_g1 b_g2
Oct 12 14:19:56 g1wrk06 lotus-worker[568686]: 2021-10-12T14:19:56.857 DEBUG bellperson::groth16::prover > multiexp a b_g1 b_g2
Oct 12 14:42:47 g1wrk06 lotus-worker[568686]: 2021-10-12T14:42:47.442 DEBUG bellperson::gpu::locks > GPU lock released!
Oct 12 14:42:49 g1wrk06 lotus-worker[568686]: 2021-10-12T14:42:49.116 DEBUG bellperson::groth16::prover > proofs
Oct 12 14:42:49 g1wrk06 lotus-worker[568686]: 2021-10-12T14:42:49.131 INFO bellperson::groth16::prover > prover time: 3398.215302182s
Oct 12 14:42:53 g1wrk06 lotus-worker[568686]: 2021-10-12T14:42:53.557 INFO filecoin_proofs::api::seal > snark_proof:finish
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by William8Work** [comment]
Good news is that the cuda is working now with the environment variable updates.

Bad news is that opencl took 60 minutes but cuda took 90 minutes to complete C2, performance is -50%.

**Comment by vmx** [comment]
> @vmx does the lotus-worker need the same environment variables during run time?

No, those are build time flags. Once you've build with CUDA support the only run-time environment variable is `FIL_PROOFS_GPU_FRAMEWORK`, which you can set to `cuda` or `opencl` (if it is not set, CUDA will be used by default).

> Bad news is that opencl took 60 minutes but cuda took 90 minutes to complete C2, performance is -50%.

Such big regression often is a sign that for something the CPU fallback was used. Could you please check the logs that everything is using the GPU as expected?

**Comment by William8Work** [comment]
thanks. I didn't use the FIL_PROOFS_GPU_FRAMEWORK at run time. will just let it use CUDA as default.

I thought about the CPU fallback so I ran one C2 sector with the BELLMAN_CPU_UTILIZATION=0.875, and another without setting the BELLMAN_CPU_UTILIZATION. But both scenarios are about 90 minutes with Cuda. 

what else should I check?

**Comment by William8Work** [comment]
want to confirm @vmx on what you want me to do:
* Set FFI_USE_CUDA=1 and FFI_BUILD_FROM_SOURCE=1 during compilation time
* Set FFI_PROOFS_GPU_FRAMEWORK=opencl during run time.

Correct?

**Comment by vmx** [comment]
> `thread 'worker-thread-2' panicked at 'failed to create tree gpu batcher: GpuError("OpenCL framework is not supported, please compile with the `opencl` feature enabled.")'`
> 
> This is what I see for WindowPost, and PC2 when I set `FFI_PROOFS_GPU_FRAMEWORK=opencl`

@ksidles you need to compile with `FFI_USE_CUDA=1` and `FFI_BUILD_FROM_SOURCE=1`.

**Comment by vmx** [comment]
@ksidles and @William8Work: I just saw, there's a typo in the env variable. make sure you set `FIL_PROOFS_GPU_FRAMEWORK` (it's `FFI` vs `FIL`).

**Comment by William8Work** [comment]
Thanks @vmx. I'll make sure the name of variable is correct.

```
The current performance for C2 is: compiling and run with cuda - 90 minutes. without using cuda compile so use opencl instead, is 60 minutes.

Does "without using cuda compile" mean you haven't set FFI_USE_CUDA=1?
```
yes. when I don't set the FFI_USE_CUDA=1 during compilation, the C2 will use opencl.

**Comment by vmx** [comment]
> yes. when I don't set the FFI_USE_CUDA=1 during compilation, the C2 will use opencl.

@William8Work this is expected. So my idea would be to compile with `FFI_USE_CUDA=1`, but then use `FIL_PROOFS_GPU_FRAMEWORK=opencl`, so that the compiled code is the same as for CUDA. OpenCL is the selected at run-time.

**Comment by ksidles** [comment]
@vmx Thank you. Just to be sure I understand correctly, do I need to recompile lotus in order for OpenCL to work?  I was under the impression the runtime variable `FIL_PROOFS_GPU_FRAMEWORK=opencl` would be enough to elect to use OpenCL.  I'm pretty sure I have lotus compiled properly specifying `FFI_USE_CUDA=1 and FFI_BUILD_FROM_SOURCE=1`.   I think I set the runtime variable correctly as well, but there was a lot of copy and paste going on, so I'm not sure if I used the correct variable or not at this point.  I'll try again just to be sure.

**Comment by William8Work** [comment]
Different from @ksidles, my GPU was ok to run opencl mode with the cuda compilation flag. Here are the results:

C2 on 1080 Ti
```
#1. before lotus v1.13.0-rc2, 75 minutes (origin), this has been the performance last few months.

#2, with lotus v1.13.0-rc2 (cuda), 90 minutes - compiled with FFI_USE_CUDA=1 and FFI_BUILD_FROM_SOURCE=1

#3, with lotus v1.13.0-rc3 (opencl), 60 minutes, compiled with FFI_USE_CUDA=1 and FFI_BUILD_FROM_SOURCE=1, and runtime use FIL_PROOFS_GPU_FRAMEWORK=opencl.
```

**Comment by ksidles** [comment]
@William8Work good to know that setting ` FIL_PROOFS_GPU_FRAMEWORK=opencl` worked for you.  I will recompile to be sure I didn't miss anything.

**Comment by William8Work** [comment]
I ran into another issue: https://github.com/filecoin-project/lotus/issues/7528.

**Comment by vmx** [comment]
@William8Work from the error message, it sounds like you haven't `FFI_USE_CUDA=1` set, but you have it set. That's strange. Also this error message should have nothing to do which graphics card is used. That's really strange.

**Comment by ksidles** [comment]
> the 1080 might be not capable of using the optimizations that we have implemented as it is

@dignifiedquire I think that is most likely the case.  I tried running opencl on my 1080TI with FFI_USE_CUDA=1 and ran into the same error as @William8Work.  I recompiled using FFI_USE_CUDA=0 and opencl started working again.

**Comment by vmx** [comment]
There hasn't been any update, hence I'm closing this issue.
