### ISSUE TITLE
thread 'worker-thread-2' panicked at 'failed to create tree gpu batcher: GpuError("Opencl3(ClError(-9999), None)")

### ISSUE THREAD

**Issue by torans** [filecoin-project/rust-fil-proofs#1531]
### 

![微信截图_20211021102906](https://user-images.githubusercontent.com/11582281/138200861-ec49aee0-386f-4738-8ed3-3a020b630519.png)
![微信截图_20211021102614](https://user-images.githubusercontent.com/11582281/138200568-6908e8eb-9876-4109-ad2e-d6a375e3bc04.png)

### Where to begi
[minerlog.log](https://github.com/filecoin-project/rust-fil-proofs/files/7385541/minerlog.log)
n

**Comment by vmx** [comment]
I'm closing this issue as it was inactive for a long time. If you are still seeing this problem, feel free to create a new issue.
