### ISSUE TITLE
There may be compatibility issues with Lotus when using tonic packages in rust-fil-proofs

### ISSUE THREAD

**Issue by hxuchen** [filecoin-project/rust-fil-proofs#1538]
When I wanted to add some GRPC methods using tonic, I had no problem compiling the RUST part alone, but an error occurred when it was introduced into the Lotus compilation. I suspect it is the problem of CGO, but I have almost no idea about it. I hope to get your help. I tried compiling in Ubuntu and got the same error.

`Undefined symbols for architecture x86_64:
  "_clBuildProgram", referenced from:
      opencl3::program::Program::build::h515bcbab54072c2d in libfilcrypto.a(opencl3-e60197e4526d682a.opencl3.7ia2z0i5-cgu.4.rcgu.o)
`

[detail log.md](https://github.com/filecoin-project/rust-fil-proofs/files/7527704/detail.log.md)

**Comment by vmx** [comment]
This sounds to me that your are missing opencl and hwloc development libraries.

**Comment by hxuchen** [comment]
> 在我看来，您缺少 opencl 和 hwloc 开发库。

You should be right, but I don't know anything about this. Could you please tell me how to deal with this problem or do you have any relevant learning materials? Thank you very much

**Comment by hxuchen** [comment]
> This sounds to me that your are missing opencl and hwloc development libraries.

You should be right, but I don't know anything about this. Could you please tell me how to deal with this problem or do you have any relevant learning materials? Thank you very much

**Comment by vmx** [comment]
I just re-read your original question. So you can compile rust-fil-proofs without problems? On the same machine you cannot compile Lotus. Did you follow the Lotus installation steps?

**Comment by hxuchen** [comment]
> I just re-read your original question. So you can compile rust-fil-proofs without problems? On the same machine you cannot compile Lotus. Did you follow the Lotus installation steps?
Yes,i follow the steps.
When I compiled Lotus using the official rust version, there was no problem. This problem occurred when I used my own version. After checking, I found that the dependency problem only occurred when I used tonic packages

**Comment by hxuchen** [comment]
> > I just re-read your original question. So you can compile rust-fil-proofs without problems? On the same machine you cannot compile Lotus. Did you follow the Lotus installation steps?
> > Yes,i follow the steps.
> > When I compiled Lotus using the official rust version, there was no problem. This problem occurred when I used my own version. After checking, I found that the dependency problem only occurred when I used tonic packages.
> > So I wonder if this problem is caused by CGO.

But I didn't change the original API in the Rust

**Comment by vmx** [comment]
When you were compiling Lotus, did you compile the Rust parts from source (with setting `FFI_BUILD_FROM_SOURCE=1`), or did you use pre-built libraries (the default/when `FFI_BUILD_FROM_SOURCE=0`)?

**Comment by hxuchen** [comment]
> When you were compiling Lotus, did you compile the Rust parts from source (with setting `FFI_BUILD_FROM_SOURCE=1`), or did you use pre-built libraries (the default/when `FFI_BUILD_FROM_SOURCE=0`)?

I compile it with `FFI_BUILD_FROM_SOURCE=1`

**Comment by vmx** [comment]
Sorry for being so sloppy today. I still didn't read the original issue properly. I didn't see that it's specifically about tonic packages. What are "tonic packages"?

**Comment by hxuchen** [comment]
> Sorry for being so sloppy today. I still didn't read the original issue properly. I didn't see that it's specifically about tonic packages. What are "tonic packages"?

it doesn't matter
I added some GRPC methods in the rust-fil-PROOFS, which also use many of the dependency packages.
When this error log appeared, I checked for a long time. Finally, I imported these packages one by one.
This compilation error happens when I use tonic on top of the original and write a simple test case.
None of the other dependent packages cause this problem.
In general, the separate compilation of the rust-fil-proofs will work and the test cases will run properly, so the inclusion of lotus should be ok.
But I don't know why there will be such a problem now, I really have no idea... And none of the Rust APIS have been modified...

**Comment by vmx** [comment]
Perhaps something is changing some environment variables/search paths and hence the libraries cannot be found anymore.

**Comment by hxuchen** [comment]
> Perhaps something is changing some environment variables/search paths and hence the libraries cannot be found anymore.

I think I need to change to a GRPC framework, do you have any recommendations

**Comment by vmx** [comment]
> I think I need to change to another GRPC framework, do you have any recommendations

No.

**Comment by hxuchen** [comment]
> > I think I need to change to another GRPC framework, do you have any recommendations
> 
> No.

Well, let me try something else. Truly appreciate your help

**Comment by hxuchen** [comment]
> > I think I need to change to another GRPC framework, do you have any recommendations
> 
> No.

When I checked the build log, I noticed a difference.
![image](https://user-images.githubusercontent.com/63218494/141508927-a31182e2-f3e5-4256-855a-52a7801ecc4c.png)

**Comment by hxuchen** [comment]
```
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -liconv -lSystem -lresolv -lc -lm -liconv
```
Whether the compilation order caused the error

![image](https://user-images.githubusercontent.com/63218494/141512234-14391865-eb03-48ff-ba95-709a26fce78d.png)
