### ISSUE TITLE
Consider using a Cargo.lock file for releases

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/rust-fil-proofs#1541]
### Description

Because of dependency upgrades (some broken beyond our control), previously tagged proofs releases are often not buildable.  One way to solve this is keeping a committed Cargo.lock file.  Perhaps an alternative is to simply upload the Cargo.lock file somewhere on github (or within the repo) that corresponds to each tagged release.  In any case, the ask is to find a way to record the dependencies in use at the time of a release to help ensure past releases can still build/run.

Motivation:

1) It's useful to compare past release performance to current/pending release performance.  Having a straight-forward way to do that saves time troubleshooting.

2) It's sometimes the case that current master is working, but the current stable release is broken (i.e. a fix in master fixes a dependency issue that the stable release can't resolve due to a Cargo patch release on a dependency being pulled in).

### Acceptance criteria

Ideally going forward, all tagged releases can be checked out and build properly.

### Risks + pitfalls

This may take some time to find a workable solution.

### Where to begin

Discuss pros/cons

**Comment by vmx** [comment]
For my Filecoin Orbit talk I wanted to run benchmarks of a version from 1 year ago. It wasn't easy. One issue I had was a dependency that has yanked the version we were using. You can only build with yanked version if you have it in a Cargo.lock file. It is not possible to create a Cargo.lock if it needs a yanked version of any dependency (I had to patch Cargo to do that).

Having a Cargo.lock somehow for releases would be great.

**Comment by cryptonemo** [comment]
Good to know.  I've been in build hell a few times trying to revive a past version.  I don't know that a Cargo.lock file will automatically solve all the problems, but I think it could help greatly.

The downside to a committed one is that a new release would be required every time we'd want to pull in a patch release of a dependency, which is why maybe an archive of them may serve us better.

**Comment by vmx** [comment]
> The downside to a committed one is that a new release would be required every time we'd want to pull in a patch release of a dependency, which is why maybe an archive of them may serve us better.

Do you mean a release for downstream dependencies? If yes, that's not an issue, the Cargo.lock is ignored if the crate is used a dependency: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries. Though I'm not a huge fan of having a Cargo.lock in the repo.

**Comment by dignifiedquire** [comment]
How about we upload it to the github release page or sth like that everytime we do a new release? This way we at least have some  historical track that can be used

**Comment by vmx** [comment]
As reported here: https://github.com/filecoin-project/rust-fil-proofs/issues/1550 our original trusted setup instructions say that you should [build rust-fil-proofs commit b288702](https://github.com/filecoin-project/phase2-attestations/blob/a5f58bc31efbfdcd93f0207efe475c62a50ae13c/README.md#latest-phase-2-mainnet). But that doesn't work as it uses a yanked version. This is another reason to supply `Cargo.toml` files somehow. Once we've decided how to do it, we should updated the documentation of the trusted setup.

**Comment by cryptonemo** [comment]
The solution we'll end up using mostly likely is adding a directory called `releases` to the repo with versioned Cargo.lock files in it (thanks to @vmx for this idea).  I prefer it to github releases, as it's simpler and more straight-forward.

**Comment by cryptonemo** [comment]
Resolved with https://github.com/filecoin-project/rust-fil-proofs/pull/1554
