### ISSUE TITLE
aes crate yanked on version 0.3

### ISSUE THREAD

**Issue by emmanuelm41** [filecoin-project/rust-fil-proofs#1550]
### Description
It is not possible to build actual mainnet version (tag 5.1.1) as aes v 0.3 crate was yanked. 

Installation:
![image](https://user-images.githubusercontent.com/10941036/147827634-6e92e1ef-d96d-41a2-b6f3-3c2461910c02.png)

Aes yanked version:
![image](https://user-images.githubusercontent.com/10941036/147827661-8282245e-1892-4bfd-8504-42c09780d6fc.png)

Aes link:
https://crates.io/crates/aes/versions

### Where to begin
Follow this instructions in order to build the project
https://github.com/filecoin-project/phase2-attestations/blob/trusted-setup-2/README.md

**Comment by vmx** [comment]
Thanks for the report and sorry for the delay. We have an open issue about [supplying Cargo.lock files for releases](https://github.com/filecoin-project/rust-fil-proofs/iss
[Cargo.lock.txt](https://github.com/filecoin-project/rust-fil-proofs/files/7839336/Cargo.lock.txt)
ues/1541).

As you mentioned the trusted setup page explicitly, I've attached a Cargo.lock file for [commit b288702](https://github.com/filecoin-project/rust-fil-proofs/commit/b288702). Remove the `.txt` extension and copy it to the root of your rust-fil-proofs checkout.

**Comment by emmanuelm41** [comment]
Thanks @vmx for the response. This file fixed the error. I had indeed. However, I am still getting two errors more. In this case, it is something related to other modules. Did I use the incorrect branch? 

```

#13 321.5 error[E0658]: `while` is not allowed in a `const fn`
#13 321.5   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.2.6/src/header/value.rs:86:9
#13 321.5    |
#13 321.5 86 | /         while i < bytes.len() {
#13 321.5 87 | |             if !is_visible_ascii(bytes[i]) {
#13 321.5 88 | |                 ([] as [u8; 0])[0]; // Invalid header value
#13 321.5 89 | |             }
#13 321.5 90 | |             i += 1;
#13 321.5 91 | |         }
#13 321.5    | |_________^
#13 321.5    |
#13 321.5    = note: see issue #52000 <https://github.com/rust-lang/rust/issues/52000> for more information
#13 321.5 
#13 321.5 error[E0658]: `if` is not allowed in a `const fn`
#13 321.5   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.2.6/src/header/value.rs:87:13
#13 321.5    |
#13 321.5 87 | /             if !is_visible_ascii(bytes[i]) {
#13 321.5 88 | |                 ([] as [u8; 0])[0]; // Invalid header value
#13 321.5 89 | |             }
#13 321.5    | |_____________^
#13 321.5    |
#13 321.5    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

```

**Comment by vmx** [comment]
As it's quite an old issue I assume it's no longer a problem. If it still is, feel free to re-open.
