### ISSUE TITLE
SnapDeals: Sector upgrade proofs run with high priority

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1553]
Currently the sector upgrade proofs (SnapDeals) are run with high priority (https://github.com/filecoin-project/rust-fil-proofs/blob/b32abab003f1b1cf75d2fe98ed4c4c670843d887/filecoin-proofs/src/api/update.rs#L502 and https://github.com/filecoin-project/rust-fil-proofs/blob/b32abab003f1b1cf75d2fe98ed4c4c670843d887/filecoin-proofs/src/api/update.rs#L569). This issue is about whether that's the correct thing to do or not.

### How the proofs priority flag works

A proof can run on the GPU or the CPU. By default all proofs run on the GPU.

#### Scenario all proofs have the same priority

If one proof is running and another one wants to start, it is blocked until the first proof is finished. This is the behaviour is the same for high and low priority proofs, as long as they have the same priority

#### Scenario when proofs have a different priority

 - low priority proof `LOW` is running, next proof `HIGH` is high priority one: The `LOW` proof gets aborted as soon as possible (without leaving the GPU in a weird state) and is rescheduled on the CPU. The `HIGH` proof is then run on the GPU.
 - high priority proof `HIGH` is running, next proof `LOW` is a low priority one: `The `HIGH` proofs keeps running on the GPU, the `LOW` proof runs on the CPU.

**Comment by cryptonemo** [comment]
> It probably should be low priority as not to block Winning and Window PoSt.

We really just need to confirm the `priority` is what we think it is, as changing it may not have the desired effect.
