### ISSUE TITLE
SDR: cannot put two runs into the same hwloc group

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1556]
### Description

We are using `hwloc` for the multicore SDR. We want to make sure that the workers and the producer should share the same L3 cache. As reported https://github.com/filecoin-project/lotus/issues/7981 it looks like we assign at most one multicore SDR per group. If there requested more then those groups, they get arbitrarily assigned.

Ideally if all groups already have one multicore SDR assigned, we should check if there is still enough room, to put another one into a group. Example: You have 24 cores and they form 4 groups where each group has its own L3 cache. You'd have 6 cores for SDR. If you now only have 2 producers (and one consumer), you only use 3 cores. You could put another SDR run in there. They will battle for the L3 cache, but that might be fine if the lookahead is small enough.

### Acceptance criteria 

You can have severals SDRs assigned to the same group if there are enough cores. Ideally it's a test that tests for the assignment it will use. This tests would likely need to be run manually as it's highly hardware specific, but that's fine.

### Risks + pitfalls

Make sure that the current assignment of one SDR per group (until there are no more free groups left) is kept intact.

### Where to begin

https://github.com/filecoin-project/rust-fil-proofs/blob/307e7af34732eed5d3a6885e4da33489dbcb1ccf/storage-proofs-porep/src/stacked/vanilla/cores.rs contains the relevant code.

**Comment by vmx** [comment]
Yes, this is what I tried to describe in my bug report. Currently you can only assign one SDR to each CCX, once each CCX has one SDR assigned, random cores are used.

**Comment by benjaminh83** [comment]
@vmx any idea if this will be addressed any time soon? 
I think it makes really good sense to get it fixed, as its more efficient to do PC1 on a dual socket system, and right now we cannot really do that without going into virtualization and cheating lotus. 
I can create a VM and bind it to only the second CPU, and tell the VM to show the OS that it has 15 CCX with each 2 cores, and lotus is happily do 15 PC1 Multicore SDR jobs in parallel on this VM with normal speeds.
I just don't think its right that we need to work like this to get lotus working because of a bug right? And not being able to easily use Dual CPU servers is just a waste of power, which we are trying to prevent right? :)

**Comment by vmx** [comment]
@benjaminh83 there's no timeline for this yet, though it's something I'd surely like to look into.

**Comment by f8-ptrk** [comment]
@vmx is there a way forward for this to get into a release soon? 

just to give you an impression on the impact: when planning pc1 servers this issue is the difference between a single server with  2x32core 3000$ cpus (if the scheduling works) and 2 64 core cpu servers with each cpu at 7k

**Comment by vmx** [comment]
@f8-ptrk I don't know how quickly it will be in a proper release soon. But you should be able to try it out today, when built from source with this changed applied https://github.com/filecoin-project/rust-fil-proofs/pull/1588.

**Comment by f8-ptrk** [comment]
sweet! quick question: if we have a 4 core ccx and run 1+1 producer mcSDR PC1s:

will it fit 2(2x 1+1) PC1in that group or 3 (3x 1+1) - one producer core could be shared between PC1s (in theory)

**Comment by f8-ptrk** [comment]
@cryptowhizzard this is worth applying to the dual cpu milans for pc1 you got! it might solve the problems

**Comment by vmx** [comment]
It will fit 2 multicore SDRs into the group. The multicore SDRs run independently, they don't share producers.

**Comment by f8-ptrk** [comment]
> It will fit 2 multicore SDRs into the group. The multicore SDRs run independently, they don't share producers.

they could share a core for their individual producers - thats what i emant

**Comment by vmx** [comment]
> but ack'ed: [core count per group] / 1+ producers = max PC1's per group

Correct, each consumer/producer runs in its own thread which is bound to one specific core each.

**Comment by benjaminh83** [comment]
@vmx Sounds like we have something for testing on ZEN3/MILAN. I would love to get those tests going on my dual 7413, where I have 6 cores in each CCX, and basically want to run 2 (or maybe actually 3) in each CCX. I hope this will work. 

Any Idea if this will work on a dual Intel Xeon 3rd gen? In theory, this will just look like two big CCX's. Would you expect this to work? I could test it on my dual 8380, but I wouldn't start the testing, if you know the fix does not cover this scenario?

**Comment by vmx** [comment]
@benjaminh83 it would be great if someone would try it out!

> Any Idea if this will work on a dual Intel Xeon 3rd gen? In theory, this will just look like two big CCX's. Would you expect this to work?

Yes that would also work. It would then split those two big CXX' into smaller units.

[The test](https://github.com/filecoin-project/rust-fil-proofs/pull/1588/files#diff-c72d0ed94a6fc31d1eb9727a9c3b3480e4cb2a86991af033a7177a9c239b1504R283-R370) might make things clearer. I'd hope that they can even be understood by people not fluent in Rust. It shows how core are assigned. It returns a list of those "units" and the multicore SDR will use one of those units one after another.

Your case sounds similar to [this test case](https://github.com/filecoin-project/rust-fil-proofs/pull/1588/files#diff-c72d0ed94a6fc31d1eb9727a9c3b3480e4cb2a86991af033a7177a9c239b1504R325-R326), where there are 16 cores, and two CXX', while having 2 producers (hence, due to the consumer, 3 threads running).

**Comment by vmx** [comment]
I should also note to everyone trying out: if you run it with `RUST_LOG=debug`, you should get a message like `Core units: …` which lists a nested array, which displays the units it calculated. This way you should see if it works as you'd expect it.

**Comment by cryptowhizzard** [comment]
I would love to test this on the latest 5.18 kernels of Linux since they have more support for the Milan and Zen kernels and NUMA. Is it possible to make a special tag for this so we can compile it in?

**Comment by vmx** [comment]
@cryptowhizzard what do you mean with "special tag"?

**Comment by cryptowhizzard** [comment]
@vmx to have it in lotus, to compile lotus-worker.

**Comment by vmx** [comment]
@cryptowhizzard oh, you mean having a released version of it?

**Comment by benjaminh83** [comment]
@vmx @cryptowhizzard no problem! I will take it up in SPX - @jennijuju and see if we can get a "jenni-tagged" lotus with this package inside.

**Comment by hyunmoon** [comment]
Is this going patch going to be included in the official lotus release?

**Comment by hyunmoon** [comment]
Is this currently stable enough to be included in the lotus release? @vmx

**Comment by hyunmoon** [comment]
@benjaminh83 Could you request another jenni-tag since the code has been updated?

**Comment by vmx** [comment]
> Is this currently stable enough to be included in the lotus release? @vmx

Yes, the plan is to have it in the next Lotus release.

**Comment by hyunmoon** [comment]
Great! I hope you meant v1.17, not v1.18.

**Comment by vmx** [comment]
> Great! I hope you meant v1.17, not v1.18.

v1.18.

**Comment by donkabat** [comment]
so... when do you schedule v1.18_rc1? :)

**Comment by OneilYang** [comment]
Does it need more settings for cpu 7302*2？
cpu: 7302*2 (dual cpu)
test 2 pc1 on it and found this:
![image](https://user-images.githubusercontent.com/71804551/178886812-aa28a5eb-5f71-4e98-881c-c1cc002e96fe.png)
looks like some thing not right for 3/5/7/9 and good for 2/4/6/8, any suggestions?

**Comment by OneilYang** [comment]
Thanks @vmx, now it works very well on 7302*2, great work~~
