### ISSUE TITLE
Check dependencies of all crates

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1598]
### Description

Over the years there were several refactors, which the lead to dependencies in Cargo.toml files which aren't actually used. I propose looking into all crates and check which dependencies are still needed. Some might also be only needed as dev-dependency (similarly to what I did at https://github.com/filecoin-project/rust-fil-proofs/pull/1593).

### Acceptance criteria

All crates specify only the dependencies in their Cargo.toml they actually need.

### Risks + pitfalls

I don't see risks, I think our test coverage on CI is good enough.

### Where to begin

There is tooling to check for unused dependencies. From my experience they don't always work well. This is what I did for the PR mentioned above:

 - Comment out all dependencies and run `cargo build`. Comment the normal dependencies in again until the build works again.
 - Run `cargo test` and start to comment in the dev-dependencies until the tests compile.
 - Check CI that everything still works.

**Comment by 0x5459** [comment]
Hello! I had some doubts when I tried to check the dependencies.

https://github.com/filecoin-project/rust-fil-proofs/blob/master/fr32/Cargo.toml#L29-L30
https://github.com/filecoin-project/rust-fil-proofs/blob/master/fil-proofs-param/Cargo.toml#L71-L72
The dependency `bellperson` is declared in the `Cargo.toml` file for both `fr32` and `fil-proofs-param` crates, but the code doesn't actually use it, only in the `[features]` in the `Cargo.toml` file.

https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-post/Cargo.toml#L42-L43
This is a similar situation. `neptune` crate.

**Comment by vmx** [comment]
> https://github.com/filecoin-project/rust-fil-proofs/blob/master/fr32/Cargo.toml#L29-L30
> https://github.com/filecoin-project/rust-fil-proofs/blob/master/fil-proofs-param/Cargo.toml#L71-L72
> The dependency `bellperson` is declared in the `Cargo.toml` file for both `fr32` and `fil-proofs-param` crates, but the code doesn't actually use it, only in the `[features]` in the `Cargo.toml` file.

Yes, those are exactly those cases this issue us about. The `bellperson` dependency (and mentioning it in `[features]`) should be removed.


> https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-post/Cargo.toml#L42-L43
> This is a similar situation. `neptune` crate.

Yes, it's the same here.

So if you would provide a pull request with removing those dependencies, it would be great!
