### ISSUE TITLE
Use workspace inheritance for dependencies

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1645]
### Description

[Cargo 1.64.0 has a new feature called workspace inheritance](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds). You can define dependencies in your workspace and then crates within your workspace can refer to them. This way you define the version only once. This makes version upgrades way easier, while making sure all crates are on the same version.

For more information see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

### Acceptance criteria

All shared dependencies are defined in the workspace and the individual crates refer to them.

### Risks + pitfalls

I'm not sure how tricky it is to get everything right, given we use features and optional dependencies quite a bit. But as soon as CI is green, I'm confident that things are correct.

### Where to begin

Increase the `rust-toolchain` version to 1.64.0. Then look at the dependencies of the crates and determine shared dependencies. Put those into the workspace and inherit their values from the crates themselves.

**Comment by kamuik16** [comment]
@vmx Mind if I work on this? Is this needed?

**Comment by vmx** [comment]
@kamuik16 we would happily accept a PR. As mentioned in the description I'd put only the shared dependencies into the root `Cargo.toml`. This make it easier in case we e.g. want to reduce the dependencies and see which ones are used only by one crate.
