### ISSUE TITLE
build or update failed

### ISSUE THREAD

**Issue by vegetable1bird** [filecoin-project/rust-fil-proofs#1648]
### Description
tag：storage-proofs-core-v12.0.0

When I run `cargo update` or `cargo build`, the following information is returned：
```
cargo update             
    Updating crates.io index
    Updating git repository `https://github.com/heim-rs/heim`
error: failed to select a version for the requirement `funty = "~1.2"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.1, ...
location searched: crates.io index
required by package `bitvec v0.22.3`
    ... which satisfies dependency `bitvec = "^0.22.3"` of package `ec-gpu-gen v0.3.0`
    ... which satisfies dependency `ec-gpu-gen = "^0.3.0"` of package `bellperson v0.22.0`
    ... which satisfies dependency `bellperson = "^0.22.0"` of package `fil-proofs-tooling v12.0.0 (/home/workspace/rust-fi-proofs-offical/fil-proofs-tooling)`
```

### 
![image](https://user-images.githubusercontent.com/15225035/203240641-2a25e58c-38a1-4f0e-9378-33f145573d05.png)
The release funty 1.2 has been yanked.

**Comment by vmx** [comment]
Yes, it's been fixed on master. You shouldn't need to run `cargo update`. If you have a custom build, you can upgrade just specific dependencies via `cargo update --package <the-package-you-want-to-update>`.

**Comment by vmx** [comment]
Another option is to use add to your Cargo.toml:

```
[patch.crates-io]
funty = { git = "https://github.com/bitvecto-rs/funty/", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }
```
