### ISSUE TITLE
Method to generate sector key

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/rust-fil-proofs#1666]
There seems to be no good way to generate a sector key today - which is needed for snapdeals unsealing, and possibly for future unsealing service-type things.

One could call Precommit1 and Precommit2 with null bytes (PC1 alone doesn't generate the sector key - https://github.com/filecoin-project/rust-fil-proofs/issues/1665)

**Comment by magik6k** [comment]
This is needed to enable https://github.com/filecoin-project/lotus/issues/10316

**Comment by vmx** [comment]
This is about getting the same bytes as TreeR, but without building TreeD or PC2. Only the layer building is needed.

**Comment by vmx** [comment]
There is now an API to run SDR only. It's exposed in the FFI at https://github.com/filecoin-project/filecoin-ffi/pull/402.
