### ISSUE TITLE
Synthetic PoRep Actors and FVM integration

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/rust-fil-proofs#1711]
### Description

The motivation for Synthetic PoRep is described in FIP-0059 (https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0059.md) and code branches in Proofs exist and PRs are currently open:

https://github.com/filecoin-project/rust-fil-proofs/pull/1701
https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/87
https://github.com/filecoin-project/filecoin-ffi/pull/400

### Acceptance criteria and Technical Scope

The remaining work required is updating the following repos:

https://github.com/filecoin-project/builtin-actors
https://github.com/filecoin-project/ref-fvm

With the new Proof types and tests (where applicable).

### Where to begin

Related to the following:

https://github.com/filecoin-project/lotus/issues/10984
https://github.com/filecoin-project/lotus/pull/10970

**Comment by cryptonemo** [comment]
There are 4 repos with `synthetic-porep` branches in flight, required for this work:

https://github.com/cryptonemo/filecoin/tree/synthetic-porep
https://github.com/cryptonemo/builtin-actors-bundler/tree/synthetic-porep
https://github.com/cryptonemo/builtin-actors/tree/synthetic-porep
https://github.com/cryptonemo/ref-fvm/tree/synthetic-porep

The above build at the moment, but the patching mechanism was not working so all Cargo files were modified (not ideal).  Looks like after yesterday, all of them need rebasing as well.

**Comment by jennijuju** [comment]
> patching mechanism was not working so all Cargo files were modified (not ideal)

can you elaborate?

**Comment by cryptonemo** [comment]
^To be clear, I'm not blocked on this, just working through it ...

**Comment by cryptonemo** [comment]
Completed
