### ISSUE TITLE
how to generate sectors cache files

### ISSUE THREAD

**Issue by bugxzhu** [filecoin-project/rust-fil-proofs#1712]
### 
I deleted the folder under the cache by mistake, so the post could not be completed. How do I restore these cache directories?
I followed this webpage, but p_aux and t_aux cannot be generated.
https://github.com/filecoin-project/lotus/discussions/7314

**Comment by cryptonemo** [comment]
Related: https://github.com/filecoin-project/rust-fil-proofs/issues/1545

Re-sealing is the most straight-forward option at this point.

**Comment by bugxzhu** [comment]
> Related: #1545
> 
> Re-sealing is the most straight-forward option at this point.

it takes too long time.

**Comment by cryptonemo** [comment]
> > Related: #1545
> > Re-sealing is the most straight-forward option at this point.
> 
> it takes too long time.

To be clear, there isn't another option if the cached results are permanently deleted.
