### ISSUE TITLE
Bitvec version error

### ISSUE THREAD

**Issue by Moogamouth** [filecoin-project/rust-fil-proofs#1752]
When I run
`cargo build --release --all`
I get
```
error: failed to select a version for the requirement `bitvec = "^0.5"`
  candidate versions found which didn't match: 1.0.1, 1.0.0, 0.22.3, ...
  location searched: crates.io index
required by package `filecoin-proofs v0.6.4 (/home/moogamouth/rust-fil-proofs/filecoin-proofs)`
```
This may have something to do with bitvec 0.5 being yanked.

**Comment by cryptonemo** [comment]
Which version is this on?  It appears to be a very old version (I don't even see a tag for a release that old).

**Comment by Moogamouth** [comment]
[https://github.com/filecoin-project/rust-fil-proofs/releases/tag/cd0e35c11c51cb20]()

**Comment by cryptonemo** [comment]
Try using a more recent release, or the current released/supported version.  That link doesn't work for me btw.
