### ISSUE TITLE
Feature Req: Build flag to disable FVM

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/rust-fil-proofs#1759]
### Description
rust-fil-proofs are used in chain binaries as well as SP binaries. 
The SP binaries do not need most of it, for example the FVM runner has no use in SP binaries. 

If there is a build flag to make a more optimized binary, this will make for a lighter SP binary, which is helpful to Curio as it bundles together a large set of tools and intends to increase the bundling. 

### Acceptance criteria
make sp-lib

### Risks + pitfalls
Slight increase in complexity

**Comment by vmx** [comment]
This should be a feature of https://github.com/filecoin-project/filecoin-ffi, right?

**Comment by snadrus** [comment]
I can move it.
