### ISSUE TITLE
Discussing Geppetto solution to aggregate challenges

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#186]
From Ben: "aggregation just requires setting the field of the second snark to be the order of the curve in the first"

Next steps are:
- [ ] set field of second snark
- [ ] Write circuit accordingly to [Scalable SNARKs paper](https://eprint.iacr.org/2014/595.pdf), [SE SNARKs Verifier Gadget](https://github.com/scipr-lab/libsnark/pull/127), [Snarky Verifier Gadget](https://github.com/o1-labs/snarky/blob/master/src/verifier_gadget.ml)
- [x] Check how Geppetto does this

**Comment by dignifiedquire** [comment]
closing this, @nicola please open in a research repo if this still needs work
