### ISSUE TITLE
Truncate staged sectors back to match metadata on instantiation

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#262]

**Comment by vmx** [comment]
I don't even understand what this is about, hence closing the issue.

**Comment by laser** [comment]
@vmx - IIRC, the software would write to a staged sector and then write metadata to disc to reflect that write. In the event of a crash after the write but before the checkpoint, the metadata may disagree with the bytes on disc, at which point we thought that a rollback of sorts would be appropriate.

**Comment by laser** [comment]
That said, the sector building code doesn't live in this repo any longer - or even in Rust as far as I recall - so the original issue probably doesn't make any sense in 2023.
