### ISSUE TITLE
Proofs tradeoffs calculator

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#285]
I am building a calculator to understand/convince ourselves of the right decision for the number of layers, challenges and other parameters that impact soundness.

[Proofs tradeoff calculator](https://beta.observablehq.com/d/60d1d6521a19e2be)

Things left to do:
- [x] Basic DRGPorep layers vs challenges
- [ ] Add support for layered constructions (ZigZag/TightPoS)

**Comment by dignifiedquire** [comment]
closing this, if more tracking is needed please open in the research repo
