### ISSUE TITLE
SectorBuilder#add_piece should validate that piece-bytes cid matches provided cid

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#297]
## Motivation

`SectorBuilder#add_piece` is given a buffer of piece-bytes and a cid. The SectorBuilder should validate that the bytes match the cid that it's been provided.

## Notes

As per @dignifiedquire, `rust-multihash` doesn't yet do proper streaming, nor does it support blake2 (the default hashing function used in go-filecoin). He said that he has a straightforward plan to make that happen - but it's unclear as to where this sits in his priority queue of work items.

**Comment by porcuquine** [comment]
@laser Is this still something that needs to happen? (`add_piece` doesn't currently receive a cid, as far as I can see.

If this is out of date, can we close? It shows up every week in the research meeting as being blocked.

**Comment by laser** [comment]
@porcuquine - You can safely move this to the icebox.

**Comment by laser** [comment]
Instead of this, we should:

1) Modify `add_piece` to accept a `CommP` instead of `piece_key`/`String`
2) Verify that the provided `CommP` matches the `CommP` which we compute over the provided byte stream
