### ISSUE TITLE
Run test with DIZK

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#365]
The idea is to run the exact number of pedersen hashes (and blake2s hashes) that ZigZag uses in DIZK, a dummy circuit would do

**Comment by porcuquine** [comment]
This work is done. I will close the issue once artifacts are available for consumption.

**Comment by porcuquine** [comment]
https://github.com/filecoin-project/research/blob/master/SNARK/perf-dizk-bellman.pdf
