### ISSUE TITLE
add clippy rules preventing `Result#unwrap` and `Option#unwrap`

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#390]
## Acceptance Criteria

1. replace all calls to `unwrap` with `expects`
1. add clippy rules which fail builds if `unwrap` is used

## Helpful Links

1. https://rust-lang.github.io/rust-clippy/master/index.html#option_unwrap_used
1. https://rust-lang.github.io/rust-clippy/master/index.html#result_unwrap_used

**Comment by porcuquine** [comment]
I think `expects_with_backtrace` is now `expects`.

**Comment by schomatis** [comment]
Potential 3rd point in the acceptance criteria:

* Add a note in the [Coding Standards](https://github.com/filecoin-project/rust-fil-proofs/blob/master/CONTRIBUTING.md#coding-standards) suggesting an alternative, see https://github.com/filecoin-project/rust-fil-proofs/pull/671#discussion_r288795873.

**Comment by dignifiedquire** [comment]
@DrPeterVanNostrand after your PR is merged, can you please add the warnings, and copy the output into a gist, so we can have a better understanding how much is left on this? Thank you

**Comment by DrPeterVanNostrand** [comment]
@dignifiedquire here are the clippy warnings
https://gist.github.com/DrPeterVanNostrand/1465e93eda049995e4c49d1d972a74fa

**Comment by laser** [comment]
@DrPeterVanNostrand - Are you working on this issue? If not, do you know what's remaining? I'm having some trouble determining the state of this item from reading the GitHub issue-comments.

**Comment by porcuquine** [comment]
800 commits later, I'm not sure if this issue can be closed or not. Please advise.

**Comment by vmx** [comment]
There's even a PR open for it: https://github.com/filecoin-project/rust-fil-proofs/pull/1122
