### ISSUE TITLE
SectorBuilder should not hold all of its metadata in memory

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#406]
this story is a stub

## Notes

Instead of serializing/persisting SectorBuilder state to disk ("snapshotting"), we should store all of that stuff on disk and query for it through some new interface.

**Comment by dignifiedquire** [comment]
@laser is this still needed?

**Comment by laser** [comment]
@dignifiedquire We should do some calculations to determine how much RAM a typical miner will lock up by holding that metadata in memory. To do this, we need to make some guesses about:

- how many sectors a typical miner will manage
- how many pieces we can expect to have in a sector

Once we have those numbers, we can look at the structs and make some educated guesses.
