### ISSUE TITLE
Finalize Spec

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#420]
This issue exists to track work which will happen in [specs](https://github.com/filecoin-project/specs).

### Acceptance Criteria

Spec is completely up to date with proofs, inclusive of hardware requirements and a copy-editing pass

**Comment by dignifiedquire** [comment]
@porcuquine @nicola can we close this and track further spec work in the specs repo?

**Comment by porcuquine** [comment]
Sure.
