### ISSUE TITLE
Integrate Piece Inclusion Proof

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#421]
Piece Inclusion Proof is integrated into Filecoin

**Comment by mhammersley** [comment]
@porcuquine, apologies for delay; i just saw your note in the spreadsheet online. i'll defer to your judgment on whether this should be p1 or p2, then. do you still agree it's launch-critical?

**Comment by porcuquine** [comment]
Probably P2 right now. My understanding is that it's need for launch, meaning mainnet — but it's explicitly not prioritized yet.
