### ISSUE TITLE
Multiple Sector Sizes

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#422]
Spec proposal for multiple sector sizes (interfaces, circuit changes) exists and, if ratified, is implemented

 - [x] Spec Proposal
 - [x] Review
 - [x] Ratified
 - [ ] Implement Proposal

**Comment by porcuquine** [comment]
Proposal work in progress: https://github.com/filecoin-project/specs/issues/175

**Comment by porcuquine** [comment]
No longer WIP: in review.

**Comment by laser** [comment]
Things which are done:

- a storage miner actor is pinned to a sector size when created
- the protocol allows for multiple sector sizes
- proving period duration, generation attack threshold, and collateral are now (stubbed) functions of sector size

Outstanding issues:

- [need to resolve this specs PR](https://github.com/filecoin-project/specs/pull/318), which decides whether or not the protocol defines an enumeration of supported (sector size, proof partitions)
- [this bug](https://github.com/filecoin-project/rust-fil-proofs/issues/611)

Things which are not done which I have no plans to do anytime soon:

- any new software to support "verified single tenancy"

**Comment by dignifiedquire** [comment]
we are now shipping with multiple sector sizes
