### ISSUE TITLE
Connect PoSt to API

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#437]
Now that we have a minimum viable PoSt, we need to make it callable from the API. This includes providing potential (could be generated on-demand) access to the merkle trees for whichever sectors are challenged. (NOTE: challenged sectors are currently stubbed, so in order to exercise the latter, the implementation may require a slight extension.)

**Comment by dignifiedquire** [comment]
This is done, go-filecoin uses post 🎉
