### ISSUE TITLE
Cache (expansion?) parents

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#455]
# Cache strategy design

~We need to have a very clear idea of how is `parents` used to be able to design the cache in an efficient manner, especially since there is a memory constraint and we just can't cache everything all the time.~
We need to be able to support a full-cache strategy, which will use a lot of memory — but have this be optional. A framework for these space vs time optimization configurations should be designed as a separate issue. (TODO: create that issue.)

What follows is my current understanding based on what I've seen from the code in ZigZag example,

```
./target/release/examples/zigzag --size 1024 --no-bench
``````

The same ZigZag graph seems to be used throughout the code, not the same `ZigZagGraph` structure but rather its "reversed" (`zigzag()`'ed ) version passed from one layer to another, specifically, the same `base_graph` and `expansion_degree` is maintained, which results in always the same parents for each separate direction (`forward`/`reversed`).

The `parents` can actually be split in the parents of the base graph and of the ZigZag extension, for now this concentrate on the ZigZag extension (`expanded_parents`, although for simplicity `parents` will be used in this text to actually mean the subgroup of parents we care to cache), this is because the underlying computation is more expensive than the base. We won't cache or analyze the underlying Feistel computations (anything below `correspondent`), which is basically a series of sequential hash functions, caching a particular hash result seems of little value since it is useful only for the computation of the current node (the chances of being reused are very low), and for roughly the same amount of space we can just cache the actual result (a parent index).

The parents of this "single" (in the sense described above) ZigZag are requested in 3 places:

1. During the replication phase, in `transform_and_replicate_layers`.

2. During the prove generation in `DrgPoRep::prove`.

3. During the verification in `DrgPoRep::verify`.

I'm not sure but I'm assuming that steps 1-2 would be called separately from step 3 and wouldn't share the cache (that is, that another process would be the one verifying it under normal -not test- circumstances).

There are two different profiles for the `parents` use, the replication (1) and the prove/verify (2/3), but from the initial write-up I'm assuming that we want to optimize step 1 and don't care about 2-3 (which use `parents` orders of magnitude less than step 1).

## Step 1: replication.

This requests the parents in sequential order for each layer (in the corresponding direction), e.g., layer-0: `parents(0); parents(1); parents(2); [...] parents(N-1);`, then layer-1: `parents(N-1); parents(N-2); parents(N-3); [...] parents(0);`, then layer-2 the same as layer-0, layer-3 same as layer-1 and so on. Each layer is processed *sequentially* (even with `generate_merkle_trees_in_parallel` set, which just parallelizes the merkle tree generation in `merkle_tree()`).

So the replication is calling `parents` for every node *once* in each layer, in sequential order (sequential here referring not to calling the parents in an orderly fashion like 0,1,2,3 which has no impact, but that every layer calls all the parents once, *finishes*, and then another layer repeats it).

Based on that, the current cache strategy implemented in PR https://github.com/filecoin-project/rust-proofs/pull/465 (and roughly delineated in this [comment](https://github.com/filecoin-project/rust-proofs/pull/465/files#diff-1551c863327ac4e6dbfca70895f4c9c2R51)) doesn't aim at an LRU cache, instead it just covers the biggest `parents` search space as possible with a fixed-size allocated memory.

The only consideration against this fixed cache would be if layers are not processed sequentially (as described in https://github.com/filecoin-project/rust-proofs/pull/465#discussion_r255245121): if we know (and can coordinate) that many layers would be calling the `parents` for the same group of nodes "more or less at the same time" then an LRU could be considered. This (I think) wouldn't be trivial to implement and would require a high degree of coupling, we would need to coordinate, say, all even (forward) layers to request `parents` for the same group of nodes at once (a group that could fit in a determined cache size), before allowing them to move to another part of the search space (clearing the previous cache as we would have a strong certainty that those values wouldn't be requested again).

----------------------------------------

## Original write-up

Background:
 - ZigZag replication has many (10 currently) layers.
 - A graph is reversed at each layer, but is only calculated on-demand.
 - There are two different parent calculations.
- One of these, the ‘expansion’ parents, uses feistel and is expensive.
- We can cache this and reuse everywhere.
- The actual expansion parents alternates (as layers reverse).
- The underlying feistel permutation is what can be cached.
- This is a permutation of indexes, so for space efficiency could be packed appropriately.
- (Data is indexed by 32-byte chunks.)
- It probably makes most sense just to cache the `expanded_parents` calls.
- It *might* be valuable to also cache the whole `parents` calculation.
- There is a time-space tradeoff that should be explored before deciding whether this makes sense in general.
- Whether or not we cache `parents` depends on the marginal time savings of doing so (may be low).
- It would be worth knowing the savings, if it is cheap to learn.
- I mention all this because the right design would make it easy to select no caching, or caching of either one or both calculations as a configuration.

Start by looking at `zigzag_graph.rs`, where `feistel` is called: 
https://github.com/filecoin-project/rust-proofs/blob/master/storage-proofs/src/zigzag_graph.rs#L165-L178

The call to `permute` OR `invert_permute` will be called `expansion_degree` times on every index (node) at every layer.

Also look at `parents` and `expanded_parents` in the same file.

This may need to be fleshed out or better specified, but the above should be enough background for you to begin digging in and understanding the problem.

**Comment by schomatis** [comment]
Implemented in https://github.com/filecoin-project/rust-fil-proofs/pull/465.
