### ISSUE TITLE
Rename rust-proofs to something else?

### ISSUE THREAD

**Issue by jbenet** [filecoin-project/rust-fil-proofs#475]
Hey cryptolabbers, I'm writing public updates, and finding the name `rust-proofs` hard to write about and reference widely, as it will be ambiguous for many. We've discussed this here and there before, but don't think we've addressed it directly yet.

Aware of the imposition and annoyance this will cause (because a bunch of references exist all over), I have to propose that we change the name of this repo/effort to something like:
- `rust-filproofs` or `rust-fil-proofs` (my ⭐️)
- `filproofs` or `fil-proofs` 
- `libfilproofs`
- `rust-filcrypto` or `rust-fil-crypto` (not so good, may not include other crypto stuff like BLS sig algos, etc.
- `filcrypto` or `fil-crypto`
- `filetoproofs` (from File to Proofs, or Filet o Proofs)
- `filecoin-project-incontrovertible-cryptographic-evidence-algorithms` [if you're not into the whole brevity thing](https://youtu.be/Be7Og9Gc_KY?t=9)
- you suggest more

I don't know that we can go through the rename quickly (it would certainly help upcoming updates & comms), or that it's worth doing, relative to everything else going on atm. but i do think that -- if we're going to do it -- we should do it relatively soon, and we may want to just start using that name in wider updates.

**Comment by dignifiedquire** [comment]
Rename is happening right now

- [ ] repo
- [ ] go-filecoin: https://github.com/filecoin-project/go-filecoin/pull/2040
- [ ] replication-game: https://github.com/filecoin-project/replication-game/pull/25
- [ ] website: https://github.com/filecoin-project/website/pull/91
