### ISSUE TITLE
Cache groth params in memory

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#477]
### Description

When groth params are needed, they are either loaded from disk or generated then written out to disk.

Loading is faster, but it's still slow. There exists a mechanism for caching the 'official' parameters in memory. See `ZIGZAG_PARAMS` in `internal.rs`.

We should extend this mechanism to handle at least all parameters that are needed by `go-filecoin`. This can be considered the same set which is generated by `paramcache`. It's not clear whether *all* generated groth parameters should be cached, since this could potentially lead to a lot of memory usage during tests.

### Acceptance criteria

- Examination of logs in `go-filecoin` shows that groth parameters are not being repeatedly slowly loaded. (will require first integrating wiht `go-filecoin` to verify) — so this should not block merging of a tentative solution. However, if the underlying problem is not addressed, this issue should be reopened.

### Risks + pitfalls

- The set of parameters we need to hold in memory may change over time, and it may also become the case that there are too many potential sets to always hold all of them in memory. So we should prefer a solution which will automatically adapt to a changing set, and ideally which is flexible enough to allow further configuration over time.

### Where to begin

- The most natural solution may be to add an in-memory cache to `parameter_cache.rs` and prefer this to the disk cache when configured to do so. Make this the default for all parameter files initially.

**Comment by whyrusleeping** [comment]
why do we have to load the full parameters into memory just to verify a proof? The proving key is the large one, the verification key is quite small.

**Comment by porcuquine** [comment]
@whyrusleeping You are correct, and that work is described here: https://github.com/filecoin-project/rust-fil-proofs/issues/477

That will address the specific problem of groth parameter loading gating verification time. This addresses the more general waste of repeatedly loading and the same parameters — whether for sealing or verification. (That it will also addresses the short-term verification issues is a convenience which motivated expediently prioritizing this issue.)

**Comment by porcuquine** [comment]
Also, the caching mechanism developed in #478 can be conveniently extended to hold verification keys — which will be simpler than an independent mechanism for the latter would have been.

**Comment by porcuquine** [comment]
@whyrusleeping I added direct support for verification keys to #478.
