### ISSUE TITLE
`paramfetch` fails from Filecoin install

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#485]
It fails to find `parameters.json` (which I guess it's not in the usual place). Also, `paramfetch` may not even be meant to be run from Filecoin, in which case please close this.

```
~/go/src/github.com/filecoin-project/go-filecoin/proofs/bin$ ./paramfetch fetch 
parameter manifest './parameters.json' does not exist
nothing to fetch
```

**Comment by porcuquine** [comment]
@sidke Can you take a look and close (with explanation) if not applicable? I'm guessing it was a premature attempt before `paramfetch` was fully released.

**Comment by laser** [comment]
`paramfetch` must be run with either the `--json` flag or from a directory containing `parameters.json`.

go-filecoin developers will typically run the following command from the root of the go-filecoin project:

```
./proofs/bin/paramfetch --all --json=./proofs/misc/parameters.json
```
