### ISSUE TITLE
Reduce warnings when building

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#488]
For reasons that completely elude me all the arguments in 

https://github.com/filecoin-project/rust-proofs/blob/12bc40ba164a66cc1e9b3d4aa89ae2635fe4986f/filecoin-proofs/src/api/mod.rs#L138-L145

are considered unused by the compiler, resulting in many verbose warnings like

```
warning: unused variable: `flattened_comm_rs_ptr`
   --> filecoin-proofs/src/api/mod.rs:139:5
    |
139 |     flattened_comm_rs_ptr: *const u8,
    |     ^^^^^^^^^^^^^^^^^^^^^ help: consider using `_flattened_comm_rs_ptr` instead

warning: unused variable: `flattened_comm_rs_len`
   --> filecoin-proofs/src/api/mod.rs:140:5
    |
140 |     flattened_comm_rs_len: libc::size_t,
    |     ^^^^^^^^^^^^^^^^^^^^^ help: consider using `_flattened_comm_rs_len` instead

warning: unused variable: `challenge_seed`
   --> filecoin-proofs/src/api/mod.rs:141:5
    |
141 |     challenge_seed: &[u8; 32],
    |     ^^^^^^^^^^^^^^ help: consider using `_challenge_seed` instead

warning: unused variable: `faults_ptr`
   --> filecoin-proofs/src/api/mod.rs:143:5
    |
143 |     faults_ptr: *const u64,
    |     ^^^^^^^^^^ help: consider using `_faults_ptr` instead

warning: unused variable: `faults_len`
   --> filecoin-proofs/src/api/mod.rs:144:5
    |
144 |     faults_len: libc::size_t,
    |     ^^^^^^^^^^ help: consider using `_faults_len` instead

warning: unused variable: `sector_bytes`
   --> filecoin-proofs/src/api/mod.rs:145:5
    |
145 |     sector_bytes: u64,
    |     ^^^^^^^^^^^^ help: consider using `_sector_bytes` instead
```

I suspect the `unsafe extern "C"` has something to do with it (although strangely `proof` is the only argument that is actually seen as used, so I can't figure out a pattern here) but have no idea how to actually fix it, could we add an `#[allow(dead_code)]` (or similar) to this function to suppress the warnings? (Also, this may just be a particular side effect of my working environment setting, not sure if anyone else is also seeing this.)

This isn't terribly important but I missed a very informative `cargo` warning (that actually should have been an error, and will be in future versions) because it got lost in all the noise, so as a Rust newbie I'd really appreciate fixing this :)

@dignifiedquire

**Comment by dignifiedquire** [comment]
Look at line 156n there is an early return making the args unused. That code below should be commented out and the args prefixed with underscores if we want to continue faking it.
