### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#489]
There have been issues when using this as a dependency, e.g. https://github.com/filecoin-project/replication-game/issues/10. If we simply publish to crates.io then those issues go away. 

Crates.io though can only be use when all dependencies are published to it. We are currently missing:

- zcashackworks/sapling-crypto
- filecoin-project/merkle-light

**Comment by dignifiedquire** [comment]
Filed an issue for sapling-crypto here: https://github.com/zcash-hackworks/sapling-crypto/issues/100

**Comment by dignifiedquire** [comment]
@porcuquine we should decide what to do with our merkle-light fork, maybe we just rename it and publish our own version, what do you think?

**Comment by porcuquine** [comment]
@dignifiedquire That seems fine to me. I think we need to feel free to easily make changes, and that seems the cleanest way to do so.
