### ISSUE TITLE
Cannot generate a proof-of-spacetime for more or less than 2 sectors

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#493]
### Description

VDF PoSt setup parameters are [created with a `sectors_count` of 2](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/internal.rs#L149). 

VDF PoSt [prove](https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs/src/vdf_post.rs#L169) asserts that the number sectors being proven match the public parameters `sectors_count`. 

Since `sectors_count` is always 2, we cannot generate a proof-of-spacetime for a number of sectors which is not equal to 2.

**Comment by laser** [comment]
cc @porcuquine

**Comment by porcuquine** [comment]
`sectors_count` is a public paremeter of PoSt — so this is functioning as designed. 2 is an arbitrary, small number larger than 1, selected to simplify initial integration tests.

There are many possible ways to address the problem implied by this issue. However, the solution to the immediate problem — if it is one — is to change the hard-coded value of `POST_SECTORS_COUNT` to be a number different than 2.

**Comment by laser** [comment]
Great. I fixed this issue here:

https://github.com/filecoin-project/rust-fil-proofs/pull/494

It’s awaiting your review.

**Comment by dignifiedquire** [comment]
how does that solve the issue that this number will be ever growing and miners submit more and more sectors? and that the requirement that this is exactly the number of sectors that are proven in a post.

**Comment by laser** [comment]
@dignifiedquire 

I spoke to @porcuquine about this at length earlier today. The TLDR is that sectors count is fixed to 2, and miners who want to prove more than 2 sectors will simply need to generate multiple PoSts.

**Comment by laser** [comment]
Also: If a miner has an odd-number of sectors, they will pair up their commitments and, for each complete pair, generate a PoSt. The final sector (without a pair) will be proven by itself (by duplicating the commitment).

**Comment by dignifiedquire** [comment]
That sounds like an entirely different construction than what was written in the spec and talked about last time. When and where does this change come from?
