### ISSUE TITLE
Proof of Space-Time (PoSt)

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#497]
## Current Plan

- [x] Get the basics of a PoSt without VDFs specced
- [ ] Implement necessary plumbing between go-fileocoin and rust-fil-proofs based on the spec
- [ ] Implement the actual circuit and internals of this PoSt

## FAQ

- Q: What about other constructions?
- A: We will cross that bridge when they are ready.

- Q: What about Faults?
- A: They will be part of this effort, both spec wise, as well as implementation wise.

- Q: Who should I ask about this?
- A: For now, ask @dignifiedquire and he will at least be able to point you to the right person with the answers.

**Comment by dignifiedquire** [comment]
work in progress, on upgrading the post spec, happening here: https://github.com/filecoin-project/specs/blob/update-post/drafts/proof-of-spacetime.md (working title: "Base PoSt")

**Comment by dignifiedquire** [comment]
ref: https://github.com/filecoin-project/specs/pull/332
