### ISSUE TITLE
Improve zigzag example

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#500]
### Description

The `zigzag` example needs some improvements as part of a push to reconcile security and scaling requirements.

Non-exhaustively:
 - [x] Support tapered challenges
 - [ ] Use less memory so larger parameters can be generated
 - [ ] Log individual partition proof timing
 - [x] Update defaults
 - [ ] Don't hold onto data during proof generation. Current implementation does so in case of extraction, but we don't really use that. Consider removing.
 - [ ] Don't duplicate vanilla proving (it's included in CompoundProof generation). If we had a better way of gather granular timing/profiling of internal parts, we could use that. We should. Meanwhile, now that vanilla proving is fast, it's not a huge deal — but for correctness it should not be added to total proving time.

**Comment by dignifiedquire** [comment]
Zigzag examples is moving into filbase, closing this issue for now. Will track new requirements there
