### ISSUE TITLE
configuration file for rust-proofs

### ISSUE THREAD

**Issue by sidke** [filecoin-project/rust-fil-proofs#501]
### Description

one should be allowed to configure rust-proofs through a configuration file
possibly can be read from the file and sent through to rust-proofs from go-filecoin via FFI

### Acceptance criteria

- provide configuration to rust-fil-proofs without environment variables
- use a file accessible to gfc and pass through ffi
- have default configuration values
- have configuration profiles, sets of predefined values that can be chosen from instead of setting everything specifically

**Comment by porcuquine** [comment]
I think it's fine (possibly desirable) if env vars are also used to override — they just shouldn't be the sole method. Just mentioning for clarification.
