### ISSUE TITLE
target_pointer_width bit 32 ERror

### ISSUE THREAD

**Issue by loulancn** [filecoin-project/rust-fil-proofs#503]
### Description

   Compiling prettytable-rs v0.8.0
   Compiling storage-proofs v0.1.0 (/opt/gopath/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/storage-proofs)
error[E0412]: cannot find type `ERror` in module `std::io`
   --> storage-proofs/src/batchpost.rs:179:92

    |
179 | fn write_usize(target: &mut Vec<u8>, value: usize) -> ::std::result::Result<(), ::std::io::ERror> {
    |                                                                                            ^^^^^ did you mean `Error`?

   Compiling filecoin-proofs v0.1.0 (/opt/gopath/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs/filecoin-proofs)
error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: Could not compile `storage-proofs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
root@9storcom:/opt/gopath/src/github.com/filecoin-project/go-filecoin/proofs/rust-proofs#

**Comment by schomatis** [comment]
Fixed in https://github.com/filecoin-project/rust-fil-proofs/pull/484.
