### ISSUE TITLE
define PR merge topology strategy policy

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#516]
### Description

The time has come to formalize and define a PR merge topology strategy. I've spoken to several members of the dev team about this and know people have opinions. Let's use this issue as a place to have the discussion, with a plan of finalizing before next Tuesday (so this doesn't drag on forever).

For bonus points, let's also consider formalizing a branch-naming convention.

### Acceptance criteria

We reach some semblance of consensus, and a PR formalizing it as documentation to contributing.md is merged according to its own rules.

If we can't even get that right, then the outcome will be declared an illegal result, and we can battle it out some more.

### Risks + pitfalls

We might battle it out forever.

### Where to begin

Throw down some proposals, straw men, or strong opinions.

**Comment by anorth** [comment]
It would be very helpful if we could align policies across multiple repos in the Filecoin project. Go-filecoin recently defined theirs as "no merge commits".

https://github.com/filecoin-project/go-filecoin/blob/master/CONTRIBUTING.md#landing-changes

**Comment by dignifiedquire** [comment]
I don’t mind for merges but would like to be able to generate changelogs from the git history, using a specific git commit convention

**Comment by porcuquine** [comment]
I don't think we should overspecify this to begin with. I'd rather begin by blacklisting some bad patterns and whitelisting some good ones. That would be an incremental improvement over the current non-policy, without loss of flexibility. I'll flesh this out later today, but wanted to register early that I think there is specific value in not flattening our use of version control completely.

**Comment by schomatis** [comment]
> I'd rather begin by blacklisting some bad patterns and whitelisting some good ones.

+1 to that instead of forcing everyone to a rigid convention.

> https://github.com/filecoin-project/go-filecoin/blob/master/CONTRIBUTING.md#landing-changes

I'd prefer not to loose commit granularity inside PRs (provided they are logically structured) to maybe make it easier to reason about past changes when reviewing `master`'s commit history and productively use tools like `git bisect` (especially for big PRs). Equating PRs to commits feels to me like we're losing some dimensionality.

I think the changelog could be generated from merged PRs instead of commits, as IPFS does.

**Comment by porcuquine** [comment]
I agree that a strategy for automated changelogs makes sense and that this will require some conventions around commits. In order not to overly complicate this discussion, I'm thinking perhaps that should come next. Once we know what topology needs to be supported, we can decide on how to extract the changelog. I'm not familiar with the IPFS process, but it sounds viable.

**Comment by porcuquine** [comment]
I also agree with @schomatis that blanket loss of granularity requiring internal commits to always be flattened seems like a loss. That said, there is a cost to trying to preserve the added information, so I think I would advocate for a policy of expressing the *right* amount of information (which might sometimes be complete collapse).

**Comment by porcuquine** [comment]
Here's a cut at something I think makes sense:

### Allowed (white list)
 - Single fast-forward merge commit, with all internal commits squashed.
 - Non-fast-forward merge commit, with all internal commits squashed -- rebased to branch from the previous commit to master.
 - Non-fast-forward merge commit, with curated (as appropriate), linear, internal commits preserved -- rebased to branch from the previous commit to master.

### Disallowed (black list)
 - Non-rebased merge commits which branch from anywhere but the previous commit to master.
 - Merge commits whose internal history contains merge commits (except in rare circumstances).
 - Multiple fast-forward merge commits for a single PR.
 - Internal junk commits — (e.g. strings of WIP).

Basically, we should allow the option of the 'simplest possible commit', primarily since it can be accomplished by merging changes from master using the GitHub button (when stale), then merging with 'squash and merge'. The benefit of the GitHub buttons is it allows contributors to merge their own work without having to seek re-approval. For simple contributions coming from community members, or for convenience, this is a good option. (Plus some people just like it.)

The various non-fast-forward options exist along a continuum. On the 'simple' end, this style is almost identical to the previous in information content. However, it does preserve more easily-accessible metadata for discovery of a commit's provenance when generated through the GitHub UI. (Plus some people just like it.)

The more expansive version of the non-fast-forward merge should be curated as necessary, with a best effort to ensure selected commits build (to maximize value of `git bisect`). Since many-commit merges hog space in the log and potentially add noise, the option should be viewed as a communication and historical tool. That is, if the goal is to merge quickly and spend less time, it's generally preferable to select an information-losing method. If you choose this strategy, you should probably still be interactively rebasing and consciously choosing what to commit (unless the work at hand proceeded very cleanly in the first place).

As always, there are exceptions, and I haven't tried to be exhaustive or to over-specify. Hopefully the spirit of this proposal is clear. The main theme is that should prefer simplicity, while preserving whatever record they consider most helpful for future reference. When opting to leave a more verbose record, authors should take concomitantly more care.

**Comment by dignifiedquire** [comment]
sgtm

**Comment by schomatis** [comment]
:+1:

**Comment by porcuquine** [comment]
@laser @sidke @schomatis — can you weigh in with either agreement or an amendment/counter?

**Comment by laser** [comment]
I prefer that we always squash commits when merging. 

It will:

a) ensure that all commits in master pass build
b) ensure that the master commit log shows only non-merge commits (makes it easy to generate commit logs during release)

**Comment by porcuquine** [comment]
Just addressing b), it's easy enough to omit merge commits. Not sure how your script works, but below is an example using `git log`. If we want all 'Pull Requests' to have only one commit, that's a distinct issue.

Example from current `master`.

I think this is what you don't want:
```
➜  rust-proofs git:(master) git log --oneline --graph

584f32 (HEAD -> master, tag: 8584f326d86a2010, origin/master) Merge pull request #514 from filecoin-project/bug/validate-all-params-511
|\
| * 03ac66a (origin/bug/validate-all-params-511) validate parameters before fetching
| * 7adee8e fail on missing json file
| * a9a5d81 validate all parameters after paramfetch
|/
* 5cfd1d9 (tag: 5cfd1d931ebb674c) examples: zigzag: add heap profiler
* 5601967 (tag: 5601967c7fbe95fe) feistel: remove TODOs
* 967e34d storage-proofs: documentation notes
* 15663bf (tag: 15663bfa22b81aed) verify_post should be passed cfg + add FFI tests for PoSt generation/verification (#508)
*   e53392c (tag: e53392ce69a75e6b) Merge pull request #513 from filecoin-project/zigzag-example-taper
|\
| * c95a6c4 (origin/zigzag-example-taper, zigzag-example-taper) Improve zigzag example for ongoing benchmarks.
|/
* bc025a2 (tag: bc025a2fe9c3346f) revert to using fake_generate_post instead of real generate_post (#512)
*   ca7b335 (tag: ca7b335262bee6e4) Merge pull request #471 from filecoin-project/fix/prove/request-parents-once
|\
| *   51ab3d9 (origin/fix/prove/request-parents-once) Merge branch 'master' into fix/prove/request-parents-once
| |\
| |/
|/|
* | cba59e8 (tag: cba59e8643d4dd52, generate-post-params) distinguish padded/unpadded bytes at the type level (#506)
* |   0bd548c (tag: 0bd548cbf0150a43) Merge pull request #478 from filecoin-project/feat/in-memory-param-cache-alt
|\ \
| * | 81c9e0b (origin/feat/in-memory-param-cache-alt, feat/in-memory-param-cache-alt) Add memory cache for groth params and verifying key.
|/ /
| *   dc1f6e6 Merge branch 'master' into fix/prove/request-parents-once
| |\
| |/
|/|
* | 5fc1fce
```

And here it is with `--no-merges`:

```
➜  rust-proofs git:(master) git log --oneline --graph --no-merges
* 03ac66a (origin/bug/validate-all-params-511) validate parameters before fetching
* 7adee8e fail on missing json file
* a9a5d81 validate all parameters after paramfetch
* 5cfd1d9 (tag: 5cfd1d931ebb674c) examples: zigzag: add heap profiler
* 5601967 (tag: 5601967c7fbe95fe) feistel: remove TODOs
* 967e34d storage-proofs: documentation notes
* 15663bf (tag: 15663bfa22b81aed) verify_post should be passed cfg + add FFI tests for PoSt generation/verification (#508)
* c95a6c4 (origin/zigzag-example-taper, zigzag-example-taper) Improve zigzag example for ongoing benchmarks.
* bc025a2 (tag: bc025a2fe9c3346f) revert to using fake_generate_post instead of real generate_post (#512)
* cba59e8 (tag: cba59e8643d4dd52, generate-post-params) distinguish padded/unpadded bytes at the type level (#506)
* 81c9e0b (origin/feat/in-memory-param-cache-alt, feat/in-memory-param-cache-alt) Add memory cache for groth params and verifying key.
* 5fc1fce (tag: 5fc1fced2107e49a) chore: rename rust-proofs to rust-fil-proofs
```

**Comment by laser** [comment]
Cool, looks like `--no-merges` will be quite useful.

As you pointed out in some earlier thread, @porcuquine, `git bisect` is a very useful tool. If we have commits in `master` which don't build, `git bisect` won't be of much use to us. If we squash when merging, we can ensure that `git bisect` will be useful to us. Alternatively, we can agree (as a team) to ensure that every commit in our branch builds (and passes tests) before merging.

**Comment by porcuquine** [comment]
I think we can hit this in multiple ways. I agree with you partially. But I also agree with @schomatis that commit *granularity* is often the thing which brings highest value to bisecting. (I've definitely had that experience in the past.) This is not meant to be exhaustive, but a few thoughts:

- I think a strong best-effort to ensure each commit builds when going for multi-commits is reasonable. People can set up `pre-commit` hooks, and we could consider adding one for the project.
- I don't think we can *require* it unless we want to make it a CI check. We could do that. I'm 100% fine with CI checks to enforce whatever we agree to. I'm only suggesting here that we take it slow so we don't overcommit to either the wrong work or a process we will be unhappy with.
- I don't agree that the occasional bad commit makes `git bisect` useless.
 - There's always `git bisect skip` if you hit that situation occasionally.
 - You can also use `git bisect skip` and a little magic to bisect *as though* only the 'main line' commits exist (i.e. excluding the sub-commits of merged branches). We could even scriptify that solution if we wanted to, though I see that as more of an individual dev tools option. (Point being you can completely opt out of the branch commits when you bisect — which I think reduces to what you want.

So the main point is that git is powerful enough to let these worlds co-exist. I don't think a free-for-all is good because some noise isn't helpful. But reasonably manicured metadata about work history can be valuable, so I still think we should allow it (while encouraging/enforcing a degree of hygiene).

**Comment by porcuquine** [comment]
I chatted with @laser about this, and he's willing to go along with a more permissive policy, as long as:

 - He can use squash-and-merge.
 - The constraints we adopt are workable in relation to the coming release strategy.

Squash-and-merge is explicitly okay. Let's plan to be willing to refine the guidelines somewhat based on the requirements of the release plan. I happen to believe that the history produced by squash-and-merge can be deterministically generated from other strategies as needed, so if we also need a little scripting to make things clean, that's okay. But I agree that we should be adopting constraints which will cooperate with our other processes, so let's see what emerges.

I would like to add one further request. Now that we are beginning to add a lot of disjoint optimizations which may need to be reverted, cherry-picked, etc. for various reasons. I'd like to ask that those landing such features — say those which require configuration options (coming soon!) to be selected — *prefer* a merge commit and to merge from GitHub UI. This makes it much easier to identify and recognize individual units of work when they need to be manipulated after the fact.

Other than that last point, which people should discuss if they disagree, this is ready to go. Someone just needs to PR it. My text above is probably a reasonable base, though probably needs to be cleaned/rewritten some. If we don't see complaint here, I'll do it eventually; and anyone else is welcome to do the same.

**Comment by schomatis** [comment]
Seems reasonable to me.

**Comment by dignifiedquire** [comment]
@porcuquine could you throw together a PR with the essence of what you think came out of this discussion, and then I'll make sure to get it to the finishline

**Comment by porcuquine** [comment]
Will do.
