### ISSUE TITLE
Improve compile times

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#519]
I don't know when, but at some point in the last months our compile times have gone really bad. I don't have any real data, except for my impressions but things got pretty bad. 

Where to start investigating

- different rust versions, could be a regression in nightlies or sth like that
- git bisect our code basis figuring out what changed when

From there we should have a clearer understanding on where the issues are and what we can do to improve things.

**Comment by dignifiedquire** [comment]
There is definitely some slow down coming from the compiler :( 

```
commit: 62b43ca768bec267dc26015d70ae82cb7f663f53
command: cargo +stable build --all
rustc: rustc 1.32.0 (9fda7c223 2019-01-16)
time: 358.87 user - 28.36 system - 1:06.83 elapsed

commit: 62b43ca768bec267dc26015d70ae82cb7f663f53
command: cargo +nightly-2018-12-06 build --all
rustc: rustc 1.32.0-nightly (14997d56a 2018-12-05)
time: 365.17 user - 28.90 system - 1:10.30 elapsed

commit: 62b43ca768bec267dc26015d70ae82cb7f663f53
command: cargo +nightly-2019-02-24 build --all
rustc: rustc 1.34.0-nightly (aadbc459b 2019-02-23)
time: 401.57 user - 28.23 system - 1:13.43 - elapsed

commit: 62b43ca768bec267dc26015d70ae82cb7f663f53
command: cargo build --all
rustc: rustc 1.34.0-nightly (02c4c2892 2019-02-26)
time: 423.16 user - 30.80 system - 1:21.02 elapsed
```

**Comment by schomatis** [comment]
ouch, could we go back a few version? (or do we depend on `1.34`?)

**Comment by dignifiedquire** [comment]
We don't, but I reached out to the rust compiler team, and will follow up here with anything that I can find out. (Note `master` is still on the old 1.32 one, so everyone is fine, except my PR in #517)

**Comment by dignifiedquire** [comment]
Would be good to get some more details on which parts of the code are slow to compile and see if we can `cfg` somethings out by putting behind features or split into smaller crates.
