### ISSUE TITLE
Write benchmark on how long it takes to encode a single node

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#530]
### Description
As part of understanding the Proof of Spacetime polling time we need to have clear how long it takes TODAY to encode a single node.

We should try to estimate with a calculator with best known hardware how long would it take to calculate a single node

### Where to begin
See https://github.com/filecoin-project/research/issues/94

**Comment by porcuquine** [comment]
This just needs to be a Criterion benchmark that calls `vde::create_key()` then `sloth_encode()`. See the loop in `vde::encode`.

**Comment by dignifiedquire** [comment]
Anyone starting on this, please chat with @schomatis first to make sure there is no duplicated work
