### ISSUE TITLE
vanilla proving is way too slow

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#537]
### Description

*NOTE: this issue is marked **P0** because it blocks validation of large-sector sealing.*

Vanilla proving takes far longer than it should. Here is example output from benchmarks I ran last week:

```console
➜  rust-proofs git:(zigzag-example-taper) ✗ ./target/release/examples/zigzag --m 5 --expansion 8 --layers 10 --challenges 5 --size 262144 --groth
…
Feb 22 22:49:03.378 INFO vanilla_proving_time: 80.99321579 seconds, target: stats, place: filecoin-proofs/examples/zigzag.rs:208 zigzag, root: filecoin-proofs
```

Why does it take 80 seconds to generate 750 inclusion proofs?
  - 750 = 50 challenges * 15 inclusion proofs. (15 proofs = data node + replica node + 13 parent nodes)
  - This is (more or less) 5 x 15 = 75 proofs from each of 10 layers
  - In this example (256 MiB), proofs are 24 hashes in length.
  - Each hash is 32 bytes.
  - So total proof size is 750 x 24 x 32 = 600,000 bytes.
  - The trees are already generated, so no hashing should be happening.
  - The encodings are stored with the trees, so no replication should be happening.
  - Why is it taking 80 seconds to process 600,000 bytes?

It gets worse.

When I try to generate proofs after replicating 64 GiB, the vanilla proving never terminates. Using 8 partitions, I see 8 processes pinged 100% utilization.

In this case:
 - I was generating 8,848 x 15 = 132,720 proofs.
 -  For 64 GiB, the proofs are 32 hashes (32 bytes each).
 - So total data is 132,720 x 32 x 32 = 135,905,280
 - This is ~226 times larger than the previous (slow) example.
 - So at the previous rate, this should have taken about 5 hours.
 - It did not complete in 5 hours.

So… something is wrong. Let's find the problem and fix it.

### Acceptance criteria

Vanilla proofs for 1GiB take dramatically less than 80 seconds to generate. Maybe a couple seconds?

### Risks + pitfalls

This could be annoying to debug if it requires repeated performance of slow replication.
  - Use blake2s instead of pedersen. But first test both and see whether the choice affects proving time. If it does, that's unexpected and probably means hashing is happening (which it shouldn't).
  - Try to use small sectors. However, we do know the problem seems to get worse as sizes grow, so that may be difficult.
  - It would be easier if the products of replication could be saved to disk so we could restart at the proving phase.
    - This should be part of the disk-backed merkle-tree generation story (#481).
    -  If it's not, consider adding — both in support of this but *also especially* for ongoing benchmarks/experiments on large data. (cc: @schomatis)
    -  Having the ability to restart mid-replication, or to restart an interrupted replication would be extremely valuable.
    - This will also probably be a necessary eventual production feature.
    - Finally, it might be the case that making this possible fixes the problem. In case the problem is somehow related to memory bloat incurred during replication.

### Where to begin

- Run the command in the example above and record initial vanilla proving times.
- Read the code.
- Profile.
- Acquire but do not necessarily sacrifice a chicken.

**Comment by schomatis** [comment]
> * Why is it taking 80 seconds to process 600,000 bytes?

You're doing two full-blown (apparently unnecessary) MT copies per layer,

https://github.com/filecoin-project/rust-fil-proofs/blob/24845466dbe3d9bbb446e1f360c0ba36d64364a9/storage-proofs/src/layered_drgporep.rs#L268-L269

**Comment by porcuquine** [comment]
Great. I have a feeling I know what this is about. I'll see how easy it is to fix and report back.

**Comment by porcuquine** [comment]
I took the first baby steps toward removing the offending clones [here](https://github.com/filecoin-project/rust-fil-proofs/compare/bugfix/slow-vanilla-proving?expand=1): 

 However, we're immediately faced with this:

```rust
    Checking storage-proofs v0.1.0 (/Users/clwk/dev/go/src/github.com/filecoin-project/rust-proofs/storage-proofs)
error[E0508]: cannot move out of type `[merkle_light::merkle::MerkleTree<<<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Domain, <<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Function>]`, a non-copy slice
   --> storage-proofs/src/layered_drgporep.rs:268:29
    |
268 |                     tree_d: aux[layer],
    |                             ^^^^^^^^^^ cannot move out of here

error[E0508]: cannot move out of type `[merkle_light::merkle::MerkleTree<<<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Domain, <<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Function>]`, a non-copy slice
   --> storage-proofs/src/layered_drgporep.rs:269:29
    |
269 |                     tree_r: aux[layer + 1],
    |                             ^^^^^^^^^^^^^^ cannot move out of here

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0508`.
error: Could not compile `storage-proofs`.

To learn more, run the command again with --verbose.
```

There are two obvious paths here:
  - Make the fields take references and borrow here.
  - Ensure ownership of `aux` so we can move.

I started down each path enough to know it's likely to get hairy and propagate through the code base.

This explains why the offending clones have survived this long, but the performance problem introduced by cloning these trees is a show-stopper. So the time has come, the clones must die.

Let the clone wars begin, and may they be as bloodless as possible.

![image](https://user-images.githubusercontent.com/1746729/54077689-f70b6400-4270-11e9-9669-4e39e1a4989e.png)

**Comment by porcuquine** [comment]
@dignifiedquire Might know of some techniques to solve this, or maybe it's easier than I fear.

**Comment by porcuquine** [comment]
After some consideration, I think the right answer may be to allow this to be solved by other things we need to do anyway. If one of you (@schomatis or @dignifiedquire) is able to resolve this quickly, then that would be worthwhile. However, I'm not sure we should spend too much time on it now if we think an alternate solution will address the issue.

Here's what I have in mind:
  - disk-backed merkle tree should be very cheaply cloned because cloning should *not* involve a deep copy. This should get us around the ownership issues here. (Of course, we will need to think about how to avoid getting into actual ownership problems with the data.)
 - We are eventually going to need to move toward a pipelined approach, with stages (encoding a layer, merkle-tree generation for a layer) being checkpointed to disk. Related to above, in such a world, this problem just shouldn't exist. (This bullet may not be necessary to resolve the issue here, but it helps with context.)

My tentative suggestion is that we ensure the solution to #481 also allows for resolution of this issue. We could prove this by actually solving it there and closing this issue along with #481. Thoughts?

**Comment by schomatis** [comment]
Now that this is not a `P0` and in the interest of keeping focus on a single issue at a time I'd rather continue with https://github.com/filecoin-project/rust-fil-proofs/issues/481, at least until I have a clear picture of how much work does it need to be resolved.
