### ISSUE TITLE
[perf] Use fixed size arrays instead of vectors where possible

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#54]
Once #38 is done, we know the sizes for nearly all our vectors at compile time. We should use this to our advantage and switch from `Vec` to fixed sized arrays to improve performance.

**Comment by dignifiedquire** [comment]
Note: needs measurements if actually useful or not when doing this

**Comment by porcuquine** [comment]
If you can timebox the investigation to a couple hours, it would be worth knowing and documenting the expected upside and estimated complexity of making this change.

**Comment by dignifiedquire** [comment]
Investigating now

**Comment by dignifiedquire** [comment]
Places I found that could be explored

- make `Graph`, generic over the degree, and use a generic array for `parents`
- make `CompoundProof` generic over the partition size and use a generic array for things related to the partition size
- explore using arrays for hashing ops in `storage-proofs/src/hasher`
- make `zigzag` generic over the layer count, and use generic arrays for things related to it


Unclear if any of these are worth doing it though.

**Comment by dignifiedquire** [comment]
I am closing this, if anyone finds out there is a lot of benefit to any of these, please let me know and we can reconsider it.
