### ISSUE TITLE
Building `storage-proofs` separately

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#540]
This is not a bug because I'm not even sure if we we're even supposed to do this, but I used to be able to build packages separately, e.g., I could run `cargo test` on `storage-proofs` (to avoid building the rest of the workspace if run from the root of the repo) but it seems that since https://github.com/filecoin-project/rust-fil-proofs/commit/cba59e8643d4dd52452883050cd7ab207a896103 I'm getting some macro errors:

```
rust-proofs/storage-proofs$ cargo test
[...]
error: cannot find derive macro `Deserialize` in this scope
 --> sector-base/src/api/bytes_amount.rs:4:64
  |
4 | #[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
  |                                                                ^^^^^^^^^^^

error: cannot find derive macro `Serialize` in this scope
 --> sector-base/src/api/bytes_amount.rs:4:53
  |
4 | #[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
  |                                                     ^^^^^^^^^

error: cannot find derive macro `Deserialize` in this scope
 --> sector-base/src/api/bytes_amount.rs:7:64
  |
7 | #[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
  |                                                                ^^^^^^^^^^^

error: cannot find derive macro `Serialize` in this scope
 --> sector-base/src/api/bytes_amount.rs:7:53
  |
7 | #[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
  |                                                     ^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `sector-base`.
```

@laser Could you help me figure out a way around this? Or maybe find what would be the correct command (run from the root) that only builds what I need (instead of everything) when I want to test a specific package (because I think `cargo test --all <name-of-test>` is not super smart and seems to build everything all the time and only later it checks which test did you actually wanted, instead of building what's necessary just for that test).

**Comment by dignifiedquire** [comment]
quick note: you can use `cargo test -p storage-proofs` to compile the specific crate from the top level

**Comment by dignifiedquire** [comment]
also just tried going into the different sub directories and `cargo test` worked fine for me

**Comment by schomatis** [comment]
> cargo test -p storage-proofs

That worked, thanks!
