### ISSUE TITLE
CircleCI build should fail if parameters.json manifest is out of date or if files referenced in manifest aren't fetchable from IPFS

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#541]
### Description

Create a way to verify that all required groth parameters have been published, and add it as a CI check.

In order to ensure the checked parameters correspond exactly to those which would be generated by `paramcache`, it probably makes sense to extend that utility with a `--check` option.

This would:
  + Determine the names of the parameters which would be generated by `paramcache`.
  + Check to ensure that these are the parameters specified in `parameters.json`.
  + If so, verify that each parameter's Cid is fetchable via IPFS.
  + If any of these checks fail, exit with non-zero exit code.

NOTE: this assumes that if a Cid for a parameters file exists in IPFS, then it does indeed correspond to the generated parameters. If we cannot make this assumption, we have to run `paramcache` again to generate the real parameters, which is impractical as a check.

Once implemented, add a CI job which runs the check and fails the job if all required parameters have not been published.

### Acceptance criteria

CI fails when `parameters.json` is not up-to-date or contains references to Cids which cannot be fetch from IPFS.

**Comment by vmx** [comment]
This was most useful pre mainnet. But now the parameters won't change that often. Hence I dare to close that issue as "won't fix".
