### ISSUE TITLE
Populate the ZigZag parent's cache in advance for both forward and backward directions.

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#550]
https://github.com/filecoin-project/rust-fil-proofs/blob/bb5a96e0fe198d407775cabd8b2bda35554ecfa9/storage-proofs/src/zigzag_graph.rs#L359-L365

**Comment by schomatis** [comment]
(Bumping it to 3, this needs some more discussion about the design before it can be implemented.)

**Comment by dignifiedquire** [comment]
no more zigzag
