### ISSUE TITLE
Add sample config file and document.

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#552]
### Description

Quick follow-up to #539:

Can we add a sample config file to simplify the process for someone wanting to configure?
 - call it `.rust-fil-proofs.config.sample`
 - should be well-formed and contains at least a default value for top-level meta-config.
 - comment at top explains where to copy if one wants to override.
 - as convention, let's add comments explaining new config added.
 - add a line in the README documenting the location the config file belongs and referencing the sample.

I realize this duplicates places to put new defaults. I think having a config file at all should be optional, but we should not make it burdensome to adopt when someone wants to. (Someone includes everyone running performance benchmarks.)

Related to the last, this might also be the easiest way to deal with automated benchmark configuration. Config branches could modify the sample and have a script to copy it over (or not).

**Comment by dignifiedquire** [comment]
@sidke are you working on this, otherwise please unassign yourself from the issue

**Comment by porcuquine** [comment]
@cryptonemo You can close this if you don't think worth implementing on some timeframe.
