### ISSUE TITLE
a panic should never unwind the stack past the FFI

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#553]
### Description

go-filecoin depends on rust-fil-proofs via CGO. A panic in rust-fil-proofs should not propagate to go-filecoin where it cannot be handled.

### Acceptance criteria

Trap all panics at the FFI boundary. Transmute panic to an error message, and send that error message back to FFI consumer.

### Where to start

[This](https://doc.rust-lang.org/nomicon/ffi.html) portion of the Rust docs outline an approach for catching panics before propagating back to FFI consumers. [This](https://blog.datalust.co/rust-at-datalust-how-we-integrate-rust-with-csharp/) blog post gives some examples of how we might use the `UnwindSafe` trait.

**Comment by laser** [comment]
Also see @vmx PR to cbdingen: https://github.com/eqrion/cbindgen/issues/347#issuecomment-513301204

**Comment by vmx** [comment]
I close this issue as `fil-proofs-ffi` and `sector-builder-ffi` now have their panics caught.
