### ISSUE TITLE
Remove unused parameter from vde::create_key()

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#572]
### Description

The [_m parameter in `vde::create_key()`](https://github.com/filecoin-project/rust-fil-proofs/blob/e4fdb866349b215f7a136f999dcc6436033fa43f/storage-proofs/src/vde.rs#L115) currently isn't used. I don't know what `m` means, so I wonder if it can be removed.

I opened an issue before I actually work on it as it could be intentional and some parameter that should be introduced in the future again.

### Acceptance criteria

`vde::create_key()` doesn't have that parameter anymore.

### Risks + pitfalls

Might be reserved for future use.

### Where to begin

Just do it.

**Comment by dignifiedquire** [comment]
tldr: just do it. 

historically we used this prameter to ensure certain lenghts match up, but this is not necessary anymore given the current implementation
