### ISSUE TITLE
paramfetch UX improvement: show status

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/rust-fil-proofs#574]
### Description
When paramfetching in verbose mode the user waits a long time with no sign of progress.  It would be very nice if there was a status bar.

### Acceptance criteria
User has accurate signal of download progress for each file in verbose mode.

**Comment by porcuquine** [comment]
This is the right place. @vmx might take a crack at it.

**Comment by sidke** [comment]
if you run `paramfetch --verbose` it will show curl progress for downloads:

flag definition: https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/bin/paramfetch.rs#L44
curl flags: https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/param.rs#L135

**Comment by porcuquine** [comment]
@ZenGround0 If that works for you, can you close this issue? Issues tracking how `paramfetch` is invoked from `go-filecoin` scripts (which now seems like what matters) probably belong in that repo, but if you want to keep this open a little longer for that purpose, it's not a big deal.

**Comment by ZenGround0** [comment]
Thanks all.  I don't want to close this yet because the reason I got tripped up was a seeming issue with the paramfetch flags:

```
FLAGS:
    -a, --all        Download all available parameter files
    -h, --help       Prints help information
    -r, --retry      Prompt to retry on failure
    -V, --version    Prints version information
    -a, --verbose    Print diagnostic information to stdout
```

I ran with -a and expected `verbose` behavior.  However I believe I got the `all` behavior.  Could we give the shortened verbose flag a unique name?

**Comment by porcuquine** [comment]
I think @sidke might have fixed that previously. Maybe it just hasn't been integrated into a release for go-filecoin yet. @sidke?

**Comment by sidke** [comment]
correct, this is already fixed: https://github.com/filecoin-project/rust-fil-proofs/commit/504858cb7edc93b950e0c91e8cf4691e859aed95
