### ISSUE TITLE
Generate PIP data

### ISSUE THREAD

**Issue by sidke** [filecoin-project/rust-fil-proofs#596]
### Description

as a storage miner
I want to generate PIP data from pieces in a given sector
so that PIPs can be sent to the storage clients before sealing

### Acceptance criteria

a CommD should be generated before sealing so PIPs can be produced and sent as soon as possible to the storage clients
`generate_comm_d(&[u8]) -> [u8; 32]`
extend StagedSectorMetadata with a CommD and map of CommP to PIPs
update StagedSectorMetadata CommP map with PIPs as they are produced

**Comment by porcuquine** [comment]
Internal implementation provided in #602.
