### ISSUE TITLE
Fixed "sectors size" should be 262144 instead of 2

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#615]
### Description

Our existing PoSt construction allows us to generate a PoSt over a fixed number of sectors at a time. This number is currently fixed to 2. If an FFI consumer requests a PoSt over more than 2 CommRs, we pair up CommRs and sequentially generate a PoSt for each pair.

PoSt generation should take approximately one proving period to complete. If we need to generate more than one PoSt in a proving period (because we have committed, say, 10 sectors) and we generate those PoSts sequentially... well, we aren't going to finish by the end of the proving period.

The [spec](https://github.com/filecoin-project/specs/blob/master/actors.md#commitsector) shows that we should use [262144](https://github.com/filecoin-project/specs/blob/master/proofs.md#filecoin-proofs) for `POST_SECTORS_COUNT`.

### Acceptance criteria

1. FFI `generate_post` signature does not change
1. We generate a PoSt for 262144 CommRs in a single shot
1. Produce an error if FFI `generate_post` called with more than 16384 CommRs

**Comment by laser** [comment]
CC @porcuquine - This issue is a follow up from conversations I had with why in LA about fixed sectors count.

**Comment by porcuquine** [comment]
Sure. As I recall, two was just an arbitrary number we chose based on its useful property of not being one. What this will end up looking like, I don't know — but I have no problem with changing for now.

**Comment by laser** [comment]
Note: This issue came up during the recent FIL on-site as being an important part of completing the storage protocol.

**Comment by laser** [comment]
Note: We have changed 1024 to 16384. 16384 = 1PiB/64GiB sectors.

**Comment by laser** [comment]
Note: The [spec](https://github.com/filecoin-project/specs/blob/840aa9a9777d955fdcd61017444741aabc96dbea/proofs.md#glossary) has been updated to set POST_SECTORS_COUNT to 212644 (16PiB / 64GiB sectors).

**Comment by laser** [comment]
@dignifiedquire - Can I delete this issue?

**Comment by dignifiedquire** [comment]
yes you can

**Comment by laser** [comment]
wontfix: replacing with rational post
