### ISSUE TITLE
parse Rust compiler output in order to create pkg-config file

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#616]
### Description

This feature is motivated by [bugs like this](https://app.zenhub.com/workspaces/filecoin-5ab0036a12f8e82ae4ed60f0/issues/filecoin-project/rust-fil-proofs/617).

The `RUSTFLAGS="--print native-static-libs" cargo build --release --all` produces a list of native libraries which must be linked along with `libfilecoin_proofs.a`. Today, we hard-code the OSX and Linux-specific values into the pkg-config `.pc` file which we distribute with `libfilecoin_proofs.a`.

Instead, we should produce this list of libraries by parsing the compiler output. This will help us to ensure that our pkg-config file is not incorrect.

### Acceptance criteria

- Any "native artifact" in the compiler output is reflected in the pkg-config `Libs` list.

### Risks + pitfalls

- This output will differ across operating systems.

**Comment by vmx** [comment]
I think this issue can be closed, it seems to be fixed: https://github.com/filecoin-project/rust-fil-proofs-ffi/blob/f8a2be56093e9fb73b0fb6336224308985c3f1a1/scripts/build-release.sh#L17-L21

**Comment by laser** [comment]
@vmx - You are correct! Thanks for pointing this out. I merged that last night.
