### ISSUE TITLE
Meaningful sector name on disk

### ISSUE THREAD

**Issue by steven004** [filecoin-project/rust-fil-proofs#620]
### Description
This is an enhancement request. 
As a developer or miner, I would like to know what the files saved on my storage are for, i.e. I want to know some connection between the sector names and the sectorID or content, instead of random strings, so that I could do some check without debugging into the code. 

### Acceptance criteria
Both the staging and sealed sector names saved in miner's storage have meanful names, which are built on some pre-defined rules, related to sectorID on the chain.

Keep the sealed sector name and its corresponding staging sector name similar (or the same).

It is also suggested putting the part of cid of the first piece into the name too. 

### Risks + pitfalls
No much risks, but need to change code in sector_store, disk_backed_storage, sector_builder mods. However, once it proves working, it works since the meta_access is kind of independent. 

### Where to begin
Not a very big deal. Could be done in one shot.

**Comment by steven004** [comment]
A proposal: 
To make the name flexible and forward-compliant, define a sector name like: 
      `xx-mmmmmmmmmmmm-dddddddddd`

- xx: 2 characters, to indicate the protocol or version to convert between sectorID and sectorName;
- mmmmmmmmmmmm: Media index or string, 12 characters to indicate where the sector is located 
- dddddddddd: 10 decimal digitals, index of this sector in the particular media, good for 2^32 space.

Since sectorID is u64 type, we could use the first 32bits for media indication, and the last 32bits for index in a particular media (e.g. a disk). 

As the first step, to simplify, I would suggest the following format as the default: 
      `on-000000000000-dddddddddd`

here, _on_ means compliance with original design, and 000000000000 means the default media. dddddddddd is sectorID's decimal string. Note that 32bits could represent 4096Pbytes when sector size is 1Gbytes, big enough for a casual miner. 

And, in the go-filecoin project, only implement the default one, anyone who wants to do cluster mining could develop their own expansion based on this. 

@dignifiedquire , your opinion?

**Comment by laser** [comment]
@steven004 - Thanks for the proposal. 

> xx: 2 characters, to indicate the protocol or version to convert between sectorID and sectorName;

> here, on means compliance with original design

OK, I understand this part of your proposal.

> dddddddddd: 10 decimal digitals, index of this sector in the particular media, good for 2^32 space.

OK, I think I understand this part too. 0000000001 (sector id 1), 1000000001 (sector id 1000000001).

> mmmmmmmmmmmm: Media index or string, 12 characters to indicate where the sector is located 

I do not understand this part of your proposal (and that's not because it is bad). 

Would you please provide me with an example of one of these `mmmmmmmmmmmm` strings that does not correspond to the "default media?" Would you please describe a scenario in which a single sector builder has some sectors with media index string A and some others with media index string B?

**Comment by steven004** [comment]
@laser ,  let's consider there is a miner who save all sectors in different storage bricks, a brick could be a single disk, or Raid-x of disk array, or even NAS. The sectos stored in one brick might be lost due to some failure, so we want to all the sectors with continuous IDs, so that it will be much easier for proving or missed set presented in a PoSt message. 

Here, in this design, the mmmmmmmmmmmm string should be encoded/decoded from/to the first 32bits of sectorID to distinguish different bricks, and all the sectors saved into a particular brick will be continously increased. 

A more specific example (may not practical, but to explain the concept): let's say a miner save sectors into 3 NAS storage with different IP addresses: 192.168.111.001, 002, 003, we could define the sector name as: ip-192168111001-dddddddddd, ip-192168111002-ddddddddddd, ip-192168111003-dddddddddd respectively, and the prefix ip means simply transferring the IP address from/to a 32-bit data as media index. 

Of course, these could be other ways to define different protocols or versions for future expansion. This design is to provide a mechanism here, and leave it for miners or commuity to develop their own version. 

And, also this is why I just make the default one as on-000000000000-dddddddddd, to make things simple and easy.

**Comment by steven004** [comment]
@laser any opinion? if you agree, I could move on to make some code change and submit a PR.

**Comment by laser** [comment]
Your proposed change makes sense to me. Please do submit a PR. Thank you!

**Comment by laser** [comment]
@steven004 - Note that your proposed change won't do much good until [we drop path information from the `sector_access` string](https://github.com/filecoin-project/go-filecoin/issues/2848).

**Comment by steven004** [comment]
> @steven004 - Note that your proposed change won't do much good until [we drop path information from the `sector_access` string](https://github.com/filecoin-project/go-filecoin/issues/2848).

Understood, we could do this step by step.

**Comment by steven004** [comment]
A [PR](https://github.com/filecoin-project/rust-fil-sector-builder/pull/29) is submitted in project rust-fil-sector-builder. Please review and comment.
