### ISSUE TITLE
increase total challenges and/or layers, possibly adding option for more partitions

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#626]
### Description

We need to begin increasing security parameters, while also taking note of how this affects performance for specified 'representative miners'.

Both number of layers and total minimum challenges are currently low and will need to be raised — though it's possible that the eventual acceptable values will be different or lower than the current plan.

We should experimentally determine a modest increase which still yields acceptable performance, at least for the smallest sectors.

This work should be sequenced after #625 so we understand the implications of changes made here for two different sector sizes.

### Acceptance criteria

Layers and/or challenges have been increased, and miners we intend to support can still seal with acceptable performance (with the sector size for which we intend to support them).

### Risks + pitfalls

This will involve a somewhat complicated game in which increased security leads to larger proofs which lead to a combination (we can strike a balance) of larger parameters and larger proofs. It seems inevitable that at some point, maybe now, user expectations for performance are violated. We will need to strike a balance between appeasing, ignoring, and adjusting expectations The challenge will be to do this within a framework which allows for continued change along this trajectory — while also providing feedback and helping us to better understand the practical implications of different security levels, which we can use as inputs to our efforts to determine where those levels can/should be set.

### Where to begin

In `filecoin-proofs/src/api/internal.rs`:
```
const LAYERS: usize = 4; // TODO: 10;
…
const POREP_MINIMUM_CHALLENGES: usize = 12; // FIXME: 8,000
```
Make those TODO/FIXME's a *little* less ridiculous.

**Comment by anorth** [comment]
Please ensure that a go-filecoin developer messing around with local networks or tests does not incur friction associated with unwanted security. 

I expect that means the magic numbers must be factored out to a configuration so that a dev configuration can maintain fast and loose values. To the extent that they are parameters that nodes in the network must agree on, but for which other values make any logical sense, they should be accessible by the go-filecoin binary for handshaking (https://github.com/filecoin-project/go-filecoin/issues/884).

**Comment by laser** [comment]
> I expect that means the magic numbers must be factored out to a configuration so that a dev configuration can maintain fast and loose values.

I'm afraid that I don't understand the solution which you describe above. Let me explain how sector sizes intersect with the protocol and miner operators - perhaps that will help us reach a shared vision for how this stuff should work.

It is the case that Groth parameters will be published by the Cryptolab team, and that Groth parameters will be published for a set of sector sizes. The set itself is not specified in the protocol; Cryptolab wants to be able to publish Groth parameters for a new sector size without impacting the protocol. 

A mining rig operator will need to select a sector size from this set when pledging. 

go-filecoin developer configuration may some day define the default sector size (used when pledging), but it will always be a member of the aforementioned set (and never an arbitrary size).

**Comment by porcuquine** [comment]
Based on discussions today, the plan is to grandfather in behavior of current 256MiB sectors.

This mean new, larger sectors will begin an incremental trajectory toward appropriate security and performance. Existing 256MiB sectors will continue to behave substantively as they do today (accepting that this will give different security properties than all other available sectors). This relates to sealing time, security, and proof size.

Bifurcation and special handling for 256MiB sectors should be handled as part of the work which implements this issue.

**Comment by dignifiedquire** [comment]
@porcuquine can we icebox this, until we have a clearer understanding of our target parameters?

**Comment by porcuquine** [comment]
I think it's worth doing fairly soon so we can at least actually exercise multiple sector sizes. However, I'll defer to you on when that needs to happen.

**Comment by dignifiedquire** [comment]
closing, we will have a different tracking issue for getting the final parameters in
