### ISSUE TITLE
Consider deleting  sloth_iter var as not used/always zero

### ISSUE THREAD

**Issue by arielgabizon** [filecoin-project/rust-fil-proofs#645]
https://github.com/filecoin-project/rust-fil-proofs/blob/dc83918734d3f36d8411a6ce47484c2db84fbb92/storage-proofs/src/circuit/zigzag.rs#L86

**Comment by dignifiedquire** [comment]
@porcuquine are you planning on doing this?

**Comment by porcuquine** [comment]
We could if we're committed to never re-introducing it. I'm not yet 100% sure we won't, so I think we should wait a little longer. It doesn't cost anything to leave in until the decision stabilizes.

**Comment by porcuquine** [comment]
We're investigating expected savings of avoiding the modular addition altogether. If removing that proves worthwhile, then `sloth_iter` will need to be completely removed. I suppose therefore, that I am still in the process of 'considering' this.

**Comment by dignifiedquire** [comment]
this was done
