### ISSUE TITLE
Crash when doing sealing 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/rust-fil-proofs#646]
### Description
Keep sending proposal from a client to a miner, each per 5 minutes. The miner crashed with the following messages: 
`May 09 13:57:08.807 INFO encoding, layer {}: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:445 storage_proofs::layered_drgporep
May 09 13:57:09.937 INFO generate_post: finish, target: FFI, root: filecoin-proofs, place: filecoin-proofs/src/api/mod.rs:138 filecoin_proofs::api
panic: send on closed channel`

### Acceptance criteria
No crash even multiple staged sectors queuing. 

### Where to begin
I am running go-filecoin test-devnet-0.2.1, and the corresponding rust-fil-proofs code.

**Comment by dignifiedquire** [comment]
Thank you for the report, any chance you can reproduce this, while running with the env variable `RUST_BACKTRACE=1`set?

**Comment by dignifiedquire** [comment]
unable to reproduce
