### ISSUE TITLE
Provide an option to optimize either wall clock time of replication or memory

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#647]
We currently use one and a half MTs worth of memory during replication (3 sector sizes), this is allocated (roughly) because we want to do two operations at the same time from the same source of `data` (the leaves of the MT): we want to build the current MT (reading) and we also want to start encoding (VDE) the `data` for the next round (writing).

We need to provide a configuration (ideally tunable but as a start we need to at least cover both extremes) to chose either of the two. Optimizing memory means leaving the current parallel MT-creation/VDE-encoding to do only one operation at the same time (on the same memory of 1 sector size, the leaves of the MT). Optimizing for replication time would be (at least for now) using the current parallel scheme (we can't go beyond it because VDEs need to happen in sequence so there's no more room for parallelization even at the cost of more memory).

**Comment by porcuquine** [comment]
Ideally, the memory-optimized solution will happen in a way which will make it as easy as possible to move merkle-tree generation to a separate machine tuned for that operation. Actually facilitating that shouldn't be part of this work, but knowledge of the possibility might inform it.

This isn't something we need to do now, but there are strategies for optimizing utilization to meet performance requirements which may depend on being *able* to do so.
