### ISSUE TITLE
no log output when retrieving a piece using libfilecoin_proofs.a

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#650]
### Description

FFI exposed functions should log when called and right before they return. The `read_piece_from_sealed_sector` function does not do this, and `internal.rs::get_unsealed_range` function doesn't log anything either.

**Comment by vmx** [comment]
@laser I guess you mean logging calls like this one?

https://github.com/filecoin-project/rust-fil-sector-builder/blob/1b75bf929bc6a868ef82465b4d0ff2d5a8bb9bff/sector-builder-ffi/src/api.rs#L309

There's plenty of those missing.

**Comment by laser** [comment]
@vmx I do indeed. I think the `*_destroy_*` calls can be skipped - but everything else should be INFO-level logged.

**Comment by vmx** [comment]
@laser I think logging even in the `*_destroy_*` (perhaps debug level) would make sense as this is where memory leaks happen if things go wrong.

**Comment by laser** [comment]
@vmx Sounds good to me.
