### ISSUE TITLE
Animated Explainer Videos 

### ISSUE THREAD

**Issue by Cryptovideos** [filecoin-project/rust-fil-proofs#653]
### I would like to propose creating some animated explainer videos that help to showcase Filecoin, the projects strengths, what it aims to achieve etc etc. I have been marketing various projects in this space for the past 2 years and would like to join you guys.

i would be happy to recivee Tokens from Filecoin as payment for my efforts as well :)

My Website is :http://www.motionfactory.co.za/

**Comment by dignifiedquire** [comment]
Please use contact@filecoin.io if you want contact us, this place is for technical discussions only.
