### ISSUE TITLE
Provide an option to reduce memory usage during MT build process

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#655]
Background https://github.com/filecoin-project/rust-fil-proofs/pull/642#issuecomment-491639515.

The MT build process used during replication temporarily allocates a vector the size of the leaves (i.e., one sector size) to process it in parallel (the same for the other levels of the tree, but the leaves is the biggest one). This significantly increases the maximum RSS from the expected 3 sector sizes to 4.

https://github.com/filecoin-project/merkle_light/blob/0571c1fbcd8865bf8624789c13319e3439dca6b0/merkle/src/merkle.rs#L615-L624

We should fix this or at least provide an option to reduce memory usage in exchange for (sequential) processing time (similar to what's done in https://github.com/filecoin-project/rust-fil-proofs/pull/642). Pinging @dignifiedquire for help figuring out a possible fix that doesn't impact CPU time, if that's not possible the option introduced in https://github.com/filecoin-project/rust-fil-proofs/pull/642 should be extend to also propagate to MT generation (that is, sequential zigzag layers _and_ sequential MT levels) which would allow to work in-place and not allocate more (temporary) storage.

Closes https://github.com/filecoin-project/rust-fil-proofs/issues/481.

**Comment by dignifiedquire** [comment]
@schomatis isn't this done with the latest merkle tree impl?

**Comment by schomatis** [comment]
Yes!
