### ISSUE TITLE
preload parents when encoding to benefit from cache

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#662]
### Description

Try to preload parents which will be needed to encode each node so they are available in the CPU cache when encoding.

Remember that the directly previous node will always be a parent, and this will not be available until directly before encoding begins.

We can probably preload a tunable number of nodes' parents in an ongoing manner — with the exception of the final parent. We can chain this value from one iteration of the encoding loop to the next and don't need to include it.

### Acceptance criteria

Replication is measurably faster.

### Risks + pitfalls

It's not clear how much, if any, benefit this will bring. However, it has been suggested that there could be up to 10x speedup — so worth a try. Because each layer begins with no preloadable parents, if there IS a large benefit to be gained, it will require multiple parallel threads fetching in order to keep up with encoding. This could get complicated.

**Comment by porcuquine** [comment]
I did some initial work on this but am pausing pending further insight as to whether this is a bottleneck — which is being investigated.

**Comment by dignifiedquire** [comment]
closing, we will have other strategies for this likely
