### ISSUE TITLE
staged and sealed sectors cannot be moved after they are created

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#672]
### Description 

See [this bug report](https://github.com/filecoin-project/go-filecoin/issues/2848) for more information.

We should not persist the staged and sealed sector paths into sector builder snapshot. To permit the sector builder directories being moved around, we should always prepend (at runtime) the sector builder staged (or sealed) directory path (provided to the sector builder at initialization time) to the sector access (filename).

Example:

Today, we store a snapshot containing a staged :sector access" that looks like this `most/excellent/dir/staging/QEUEMGIDTNIEHXSMSLLCXQKRGNJUNGUN`. We should instead store only `QEUEMGIDTNIEHXSMSLLCXQKRGNJUNGUN`.

### Acceptance criteria

A miner must be able to write some staged sectors, close down the node, move their sector builder directories elsewhere and then start up the sector builder (pointing to those new locations). After starting, the miner should be able to pick up where they left off.

**Comment by steven004** [comment]
> Today, we store a snapshot containing a staged :sector access" that looks like this `most/excellent/dir/staging/QEUEMGIDTNIEHXSMSLLCXQKRGNJUNGUN`. We should instead store only `QEUEMGIDTNIEHXSMSLLCXQKRGNJUNGUN`.

I would suggest we also support sub-folder under `root-dir/staging/', e.g. some staging sectors could be saved into `root-dir/staging/folder1/` and some could be in `root-dir/staging/folder2`. In this case, let's use a relative path, instead only the filename. E.g. the sector access could look like: `most/excellent/dir/staging/subfolder/QEUEMGIDTNIEHXSMSLLCXQKRGNJUNGUN`. We could store `subfolder/QEUEMGIDTNIEHXSMSLLCXQKRGNJUNGUN` instead.

The reason behind is that there could be a huge number of sectors for a miner. E.g. let's consider a 72T storage node, which could contain about 280K sectors (256M each). There could be a performance issue when too many files in one folder for some file systems. 

Regarding how to support multiple sub-folders, I would think this is another topic, a customized miner software could implement it easily. Here, the point is, once we implement this, then the folder is movable.

**Comment by laser** [comment]
@steven004 

> E.g. let's consider a 72T storage node, which could contain about 280K sectors (256M each). There could be a performance issue when too many files in one folder for some file systems.

The proving system will support sectors which are much larger than 256MiB. We haven't yet deployed Groth parameters for these larger sectors - but will at some point in the future. This may help miners work around the issue which you describe.

**Comment by steven004** [comment]
Understood. It will help when sector size is getting larger.
Even so, I still suggest to save relative path, instead only file name.
Considering even 4G or larger sector size, there will be still too many
sectors if we only use one folder in disk-storage, especially for a
miner-pool design. What I suggested will help miner organize sectors,
perhaps different folders for different clients, or different time period,
anyway, more flexibilities, but no (or only a little) more effort for
implementation, I believe.

**Comment by laser** [comment]
@steven004 - 

> Even so, I still suggest to save relative path, instead only file name.

I agree with your suggestion.
