### ISSUE TITLE
ensure direct parent is first parent input to KDF

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#677]
### Description

When parents are passed to KDF, they are sorted by index. The sort order should be reversed for every other layer.

Recall that the 'direct parent' i.e. the one with index directly preceding the current node for the direction of this layer's replication -- is always include as a parent of each node. This 'direct parent' should be the one hashed first. This means that when replicating in the 'forward' direction (as in the first layer, with index 0), the parents should be sorted in reverse index order.

Otherwise, it's possible to pre-hash all the parents except the direct parent, minimizing the amount of required sequential hashing.

### Acceptance criteria

KDF hashing cannot begin until the previous node has been encoded.

### Where to begin

Most simply:
 - Modify the `parents` method in `drgraph.rs` to sort in descending order. We need to change the value returned here so `DrgPoRep` behaves correctly.
 - Modify the `parents` method in `zigzag_graph.rs` to reverse the order of the calculated parents if the graph is reversed.

Ideally, instead of reversing, add a parameter to the base parents method, allowing callers to control the sort order.

**Comment by dignifiedquire** [comment]
@schomatis this should be unblocked, let me know if you need anything to finish this

**Comment by schomatis** [comment]
unblocked, will resolve this week
