### ISSUE TITLE
Internal Audit

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#685]
### Description

Tracking Epic for internal audit issues.

**Comment by nicola** [comment]
The internal audit will have three phases:
- **Theory Audit (~6 weeks)** by @nicola, @nikkolasg, @irenegiacomelli, @lucaniz: the team will read the current paper and will produce a document with correct parameters and the correct construction.
- **Implementation/Circuit Audit first pass (~1 week)** by @nicola, @porcuquine, @dignifiedquire, @arielgabizon: the team will read the code together and check it against the spec. The motivation for this work is to verify that there are no major flaws in our spec/circuit implementation
- **Implementation/Circuit Audit first pass (~3 weeks)** by @nicola, @porcuquine, @dignifiedquire, @dignifiedquire: the team will read the code together and dive into the details of the implementation. The motivation for this work is to verify that there there is NO flaw in our implementation

**Comment by pooja** [comment]
@nicola Has phase 1 (theory audit) already started?

**Comment by pooja** [comment]
Also you've listed dig twice in the second pass phase. Did you mean to include ariel?

**Comment by dignifiedquire** [comment]
> Also you've listed dig twice in the second pass phase. Did you mean to include ariel?

he needs me to work double time I fear 😱

**Comment by porcuquine** [comment]
Internal audits have come and gone, and the wind cries Mary.
