### ISSUE TITLE
Amortize Blake2s merkle tree generation

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#695]
### Description

When generating the merkle tree using Blake2s, we can save in CPU time by running Blake2s hashes in a batch. This would allow us to save substantial CPU cost.

### Where to begin

- [See blake2s amortization benchmarks](https://github.com/oconnor663/blake2_simd/blob/master/benches/bench_multiprocess/src/main.rs)

**Comment by dignifiedquire** [comment]
we are not using blake2s anymore in the MT
