### ISSUE TITLE
replica_id should only appear once in ZigZag public inputs

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#699]
### Description

Because a ZigZag circuit is naively composed of many DrgPoRep circuits, we end up passing one `replica_id` per layer as a circuit public input. We can eliminate the extra inputs by allocating only one input and passing the allocated number as a private input to the sub-circuits. This is analogous to how we pass a shared root to all the proofs-of-retrievability in a single DrgPoRep — and how we pass roots shared between layers to each DrgPoRep of a ZigZagDrgPoRep.

**Comment by dignifiedquire** [comment]
no more zigzag
