### ISSUE TITLE
publish new rust-fil-ffi-toolkit crate to crates.io

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#707]
### Description

I [recently introduced](https://github.com/filecoin-project/rust-fil-ffi-toolkit) a new Git repository which needs to be published to crates.io. After the crate is published, [this](https://github.com/filecoin-project/rust-fil-proofs-ffi/blob/master/Cargo.toml#L18) and [this](https://github.com/filecoin-project/rust-fil-sector-builder/blob/master/sector-builder-ffi/Cargo.toml#L17) need to be updated to use it.

### Acceptance criteria

- new crate published to crates.io
- dependent crates consume crates.io release instead of Git SHA

**Comment by dignifiedquire** [comment]
I have released `0.3.0` versions of both those crates
