### ISSUE TITLE
configure CircleCI for rust-fil-ffi-toolkit project

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#708]
### Description

I recently introduced [a new Git repo](https://github.com/filecoin-project/rust-fil-ffi-toolkit) which contains FFI-related tools shared by the rust-fil-sector-builder and rust-fil-proofs-ffi projects. We need a CircleCI build for this project. We don't need GitHub releases for this project, though.

### Acceptance criteria

- pushes to branches run tests and linting in CircleCI

**Comment by dignifiedquire** [comment]
https://circleci.com/workflow-run/395cb404-5098-40f6-921b-9f60660252b9 done
