### ISSUE TITLE
Benchmark MIMC

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#709]
### Description

It would be great to repeat the same benchmarks we did for pedersen

### Where to begin

[Sean's code](https://github.com/zkcrypto/bellman/blob/master/tests/mimc.rs)

**Comment by dignifiedquire** [comment]
This needs more investigation given the issues around MiMC mentioned here:  https://github.com/zcash/zcash/issues/2233 and especially https://github.com/zcash/zcash/issues/2233#issuecomment-416648993

**Comment by dignifiedquire** [comment]
@nicola how useful is this actually? should we keep this around, even though the known issues regarding this Mimc construction?
