### ISSUE TITLE
Remove or downgrade bitvec

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#720]
There are some serious performance regressions in `bitvec` after `0.5`. We should either downgrade, or replace the logic with custom one as appropriate.

**Comment by schomatis** [comment]
Once https://github.com/filecoin-project/rust-fil-proofs/pull/752 lands it will be fully downgraded to `0.5`, still I vote to take it out completely.

**Comment by porcuquine** [comment]
Kill it if it's not longer critical. We can't afford to keep getting slapped like this.

**Comment by dignifiedquire** [comment]
yes we should take it out, possibly writing our own minimal version of bitvec

**Comment by porcuquine** [comment]
Agreed. I think a bitvec just providing potentially just the basics but with an emphasis on performance and performance-stability would be a good cryptolab project. We could start from `0.5` :). We should survey our own code and define the feature set we actually need to support.

**Comment by cryptonemo** [comment]
Resolved with #719
