### ISSUE TITLE
Compare Benchmarks against master for every PR

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#726]
We had some issues with performance regressions in the past. In order to ensure this does not happen every PR should have a "CI" check in Github that compares the baseline performance of `master` with that PR. 

We can use the newly provisioned benchmark server for this, what needs some work is writing code to wire up our benchmarks such that they get reported, and the runs are triggered automatically.

**Comment by porcuquine** [comment]
I think some version of this exists and is almost entirely neglected. @dignifiedquire can you provide @cryptonemo with a brain-dump and/or point to documentation of this. Can the medium term output of that effort be that this *is* documented and either made useful/visible or (possibly) terminated if that is impossible.

**Comment by cryptonemo** [comment]
Closing in favor of #1396
