### ISSUE TITLE
Document our settings framework

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#732]
I'm always talking about setting environmental variables to avoid overwhelming the user but ideally I should be able to talk about setting _options_ and point to a document that explains how they work, e.g., through environmental variables with our `FIL_PROOFS` prefix but also (I think) in a TOML file _without_ that prefix. How to set it should be an explanation independent of the option itself.

**Comment by schomatis** [comment]
(@dignifiedquire assigning you because you were the last one to update that part of the code but feel free to reassign to me)

**Comment by porcuquine** [comment]
#1172 got close, but I think we may still not yet have documented the config (and we should).
