### ISSUE TITLE
Don't bench on ZigZag example by default

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#733]
Pretty please, so I don't need to keep including that weird `--no-bench` argument and avoid unnecessary explanations to the user.

https://github.com/filecoin-project/rust-fil-proofs/blob/a651a70fe3d7e6e6a3c11650f43164a45e238540/filecoin-proofs/examples/zigzag.rs#L476-L478

(Happy to submit a PR, just need a green light from any of the elders in the tribe.)

**Comment by dignifiedquire** [comment]
![giphy](https://user-images.githubusercontent.com/790842/61134567-2bfa2280-a4c0-11e9-9ffe-e0774d68fb59.gif)


JUST DO IT
