### ISSUE TITLE
Change `FILECOIN_PARAMETER_CACHE` environment variable to `FIL_PROOFS_PARAMETER_CACHE` as per convention

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#741]
### Description

For background, see [this](https://github.com/filecoin-project/rust-fil-proofs/issues/629#issuecomment-508527544) comment and [this](https://github.com/filecoin-project/rust-fil-proofs/issues/629#issuecomment-510632382) comment.

### Acceptance criteria

Change `FILECOIN_PARAMETER_CACHE` environment variable to `FIL_PROOFS_PARAMETER_CACHE` to match rust-fil-proofs conventions.

**Comment by mishmosh** [comment]
This will require changes to rust-proofs, as well as go-filecoin-infra (to coordinate on bootstrapping). Potentially also small change in go-filecoin.
