### ISSUE TITLE
force consumers of rust-fil-proofs (paramfetch, Rust lib, C lib, paramcache, parampublish) to set Groth parameter cache environment variable

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#742]
### Description

For background [read this comment](https://github.com/filecoin-project/rust-fil-proofs/issues/629#issuecomment-510258675).

The existing, default Groth parameter cache path is `/var/tmp/filecoin-proof-parameters`. This path will exist on OSX and will exist in Linux.

The existing caching code does not evict old Groth parameters or keys from the cache directory. A developer unfamiliar with the Groth parameter caching code (i.e. a go-filecoin developer) is unlikely to know that rust-fil-proofs is reading/writing to this directory. The cache grows without bound, and this can take up many GiB of space.

A proposed solution to this issue is to force a consumer of rust-fil-proofs to set the [environment variable which controls the cache location](https://github.com/filecoin-project/rust-fil-proofs/issues/741). A developer who does not set the environment variable will not be able to run `paramfetch`, nor `paramcache`, nor `parampublish`, nor exercise any Rust code which generates a PoSt, seals, or verifies a PoSt or PoRep proof.

### Notes

- The environment in which rust-fil-proofs tests run will need to have the cache controlling environment variable set.
- Investigate whether the bencher requires this, too.
- Need to produce a useful error message if environment variable not set.
- Need to check all downstream builds (rust-fil-proofs-ffi, rust-fil-sector-builder, go-filecoin) to ensure environment variable is set.

**Comment by anorth** [comment]
FWIW the presence of a default value here when the expected path changed caused confusing failures in the go-filecoin nightly that surfaced as permission failures, because the build was not populating the new directory. This would have been mitigated by being detected at startup: https://github.com/filecoin-project/rust-fil-sector-builder/issues/22

**Comment by porcuquine** [comment]
@anorth As far as you know, are downstream issues associated with parameter path fully resolved now?

**Comment by cryptonemo** [comment]
Resolved.  See https://github.com/filecoin-project/rust-fil-proofs/#parameter-file-location as well as the note about using `FIL_PROOFS_CACHE_DIR`
