### ISSUE TITLE
Panicked during PoSt generation while a sealed sector is corrupted.

### ISSUE THREAD

**Issue by steven004** [filecoin-project/rust-fil-proofs#743]
### Description
When I have a corrupted sealed sector, the filecoin daemon will panic when generating PoSt.

### Acceptance criteria
The system just remove the corrupted sector from proving set and generate PoSt for all valid sectors, and report back which sector is corrupted. 

### Risks + pitfalls
This is not an enhancement, has to be fixed. 

### Where to begin
This might be expected since the PoSt implemenation is still in progress. If so, this issue is just for tracking the feature availability.

The panic might from here: 
https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api.rs#L507

**Comment by laser** [comment]
I am moving this issue over to [rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs/issues/751).
