### ISSUE TITLE
integrate basic apex into circuits

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#748]
### Description

This is the first step toward ideas discussed in #563

The goal is to modify and  integrate the apex commitment implemented in #562 such that it can be used to reduce the number of constraints in a circuit with many merkle inclusion proofs sharing a common root.

For this step:
- The root commitment of the merkle tree should not change.
- This means that the apex should prove construction of the root as a complete merkle tree rather than using a merkle-damgard construction as the current implementation does. (No change in number of hashes proved.)

This will require modifying `commit`.

Then we need to extend the DrgPoRep circuit (where the many inclusion proofs occur), to take an optional apex heights for the data and replica trees. If apex heights are present, we should generate and commit an appropriately-sized apex for each tree (we have as private inputs).

`ApexCommitment::commit` should return a root, and we need to constrain that to be equal to the corresponding public input (either `comm_d` or `comm_r`).

Then, when synthesizing any particular inclusion proof, we should prove only up to the apex. Then the remaining path can be passed to `ApexCommitment::includes`, along with the hash resulting from the merkle inclusion proof so far.

Effectively, this means that every hash in the apex will be performed exactly once. ~The cost of checking inclusion is the same as the cost of the `conditionally_reverse` constraints that would have been performed in the inclusion proof~ [this was never true of the `conditionally_reverse` technique, but is true (at cost of verification key size and public inputs) of the Apex Max technique], so we essentially get the hashing for free. Therefore, the optimal apex size can be set based on the number of challenges and is independent of the number of constraints in one hash.

In order to avoid clogging up this development task with discussion, I'm going to put the calculations in #563 for discussion. If we can conclude that the optimal apex height depends only on the number of challenges, then it can be calculated at circuit synthesis time independent of hybrid merkle tree beta height (which is more complicated to optimize). In that case, we should do so. That will make configuration easier, always maximize savings, and will also make dependent calculations (like hybrid merkle beta height) easier since it will be deterministic.

**Comment by porcuquine** [comment]
Note that new developments in #563 may influence this issue. Let's keep this one open for the implementation, but we need to resolve a few more open questions and account for them. In particular, we may now have a strategy for avoiding the use of `conditionally_reverse` and associated constraints — but we need to quantify the tradeoffs in terms of verification key size vs constraints.

**Comment by porcuquine** [comment]
Paused until we decide whether we need apex at all in light of merkle-tree amortization.

**Comment by dignifiedquire** [comment]
we will not be using apex for now
