### ISSUE TITLE
Pad inputs to 255 (not 256) in circuits.

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#75]
#74 addresses this.

There might be other instances.

This issue is for tracking and discussion of the root issue.

The point is that a valid Fr will only have 255 bits, and there is an underlying expectation of bits being grouped in multiples of 3.

**Comment by dignifiedquire** [comment]
@porcuquine what do we want to do about this?

**Comment by dignifiedquire** [comment]
Going to close this, if this is still something we need to change, lets figure it out in the spec first
