### ISSUE TITLE
PoSt generation results in panic if a sector file in its proving set cannot be found

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#751]
The original bug report can be found [here](https://github.com/filecoin-project/rust-fil-proofs/issues/743), authored by @steven004.

Note:  If the `generate_post` caller provides a `comm_r` which corresponds to a sealed sector path in the sector builder's metatadata *but that does not correspond to a file on disk* (because it was deleted), `generate_post` should indicate to its caller that the replica was faulty. PoSt doesn't detect storage faults yet; this issue is blocked until it does.

-------

Note that as of July 19, PoSt doesn't yet detect storage faults.

### Description
When I have a corrupted sealed sector, the filecoin daemon will panic when generating PoSt.

### Acceptance criteria
The system just remove the corrupted sector from proving set and generate PoSt for all valid sectors, and report back which sector is corrupted. 

### Risks + pitfalls
This is not an enhancement, has to be fixed. 

### Where to begin
This might be expected since the PoSt implemenation is still in progress. If so, this issue is just for tracking the feature availability.

The panic might from here: 
https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api.rs#L507

**Comment by porcuquine** [comment]
Is there anything left to do here?

**Comment by cryptonemo** [comment]
It doesn't look like we panic anywhere in the post path now.
