### ISSUE TITLE
replica ID should be computed from Hash(ProverID || SectorID || ticket)

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#757]
### Description

As per [the ZigZag spec](https://github.com/filecoin-project/specs/blob/master/zigzag-porep.md#replication), replica ID should be computed as follows:

```
ReplicaID := Hash(ProverID || SectorID || ticket)
```

As per [the proofs spec](https://github.com/filecoin-project/specs/blob/master/proofs.md#seal), both the Seal and VerifySeal should accept a ticket (from the chain). Note that the source of this [ticket is still TBD](https://github.com/filecoin-project/specs/issues/56#issuecomment-514627021). 

### Acceptance criteria

We must modify `seal` and `verify_seal` to accept a ticket, and we should use that ticket to compute replica id.

**Comment by dignifiedquire** [comment]
fixed in master
