### ISSUE TITLE
Get realistic benchmarks into uber-calc (by Aug 2)

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#761]
### Description

Notes:

- @laser will take over this project from @dignifiedquire 
- @dignifiedquire will provide code pointers and some prose explaining what his current solution does
- @porcuquine to describe the delta between what dig's current solution does and what he needs
- @laser will write acceptance criteria from ^^ and, if needed, more stories

### Acceptance criteria

- [ ] get ZigZag and micro benchmark output as JSON
- [ ] ZigZag benchmark output should include max resident set size used
- [ ] benchmark output should include Git SHA
- [ ] benchmark output should include information about the hardware (CPU model, total memory, etc.)
- [ ] single command for developer to run benchmarks in the cloud (on a Packet box)
- [ ] run benchmarks on Packet box with each push to rust-proofs `master`
- [ ] push benchmark JSON to benchmark server on each run

### Risks + pitfalls

- TBD

### Where to begin

- TBD

**Comment by dignifiedquire** [comment]
## Overview

### Data collection

The data points below can currently be collected using two different scripts
- `filbase --benchy` collects information on ZigZag (rust-filbase)
- `cargo run --bin micro -p fil-proofs-tooling --release` collects the micro benchmarks (rust-fil-proofs) 

### Data storage

The current solution can store the information into prometheus. This might or might not be a good idea. An alternative that is possible much simpler and more flexible in the long run is to store the data into a sql or nosql database. 

### Reporting

- Visual: Initial prototype used Graphana, but this might not be that great, given certain limitations I have run into. Needs some exploration
- Machine readable: The hard requirement right now is to have a JSON file with the data points, that can be consumed by @porcuquine 

### Configuration

- rust-filbase has some flags on the commandline and we have a configuration file we can use to handle storage-proofs specific configs. In the long run that should likely hold all configurations, but needs more thought over the exact things that need configuration.

### Execution

- Manual runs, 
  - triggered via ssh
  - triggered via comment on a PR
- Automated runs for 
  - every commit to master of rust-fil-proofs


## Data Points needed

### ZigZag
### Parameters
- sector-size
  - Size of one sector. Unit: bytes
- base-degree
  - In-degree of the base depth-robust graph (DRG).
- expansion-degree
  - Maximum in-degree of the bipartite expander graph component of a ZigZag graph.
- sloth-iter
  - Number of iterations of sloth verifiable delay encoding (VDE) to perform.
- partitions
  - Number of circuit partitions into which a proof is divided.
- total-challenges
- partition-challenges

### Measurements
- replication-time
  - Time to replicate one sector. Unit: seconds
- sealing-time
  - Total CPU time to seal (replicate + generate proof of replication) one sector. Unit: seconds
- non-circuit-proving-time
  - Time to generate a non-circuit proof of replication. Unit: seconds
- vector-commitment-time
  - Time to generate the vector commitments used in a non-circuit proof of replication. Unit: seconds
- circuit-proving-time-per-constraint
  - Groth16 circuit proving time (from benchmarks) per constraint. Unit: seconds
- circuit-proving-time
  - Time to generate a circuit proof of replication using Groth16. Unit: seconds
- zigzag-total-proving-time
  - Total time to generate a proof of replication (circuit and non-circuit). Unit: seconds
- seal-time
  - Total time to seal (replication + proving) one sector. Unit: seconds
- total-zigzag-constraints
  - Total number of constraints which must be verified in a ZigZag circuit.
- replication-cycles
- sealing-cycles
- zigzag-vanilla-proving-cycles
- zigzag-groth-proving-cycles
- zigzag-total-proving-cycles
- zigzag-constraints
- total-seal-cycles

### Micro Benchmarks 
- single-kdf-time
  - Hashing time to perform a single KDF. Unit: seconds
- single-layer-merkle-hashing-time
  - Merkle hashing time for a single layer. Unit: seconds
- single-node-encoding-time
  - Time to encode a single node. Unit: seconds
- Conversion of 32 bytes to `Fr`.
- Hash Functions
  - input sizes
    - 1x32
    - 2x32
    - number of layers * 32
    - (parents + 1) * 32
  - functions
    - pedersen
    - blake2s
    - sha256

### Other Details to collect

- git commit sha
- basic cpu and memory stats of the machine (possible crate: https://github.com/heim-rs/heim)

**Comment by laser** [comment]
## Notes

### Using Benchy with ZigZag

#### Running

```
cargo build --release --features benchy \
  && ./target/release/filbase benchy zigzag --size 1024
```

#### Output

```
Replication: total time: 14.9740s
Replication: time per byte: 14.2800us
Vanilla proving: 533.4730us
Avg verifying: 0.3421s
Total proving: 0.0000s
# HELP circuit_num_constraints Number of constraints of the circuit
# TYPE circuit_num_constraints gauge
circuit_num_constraints{data_size_bytes="1048576",expansion_degree="8",hasher="pedersen",layers="10",m="5",partitions="1",samples="5",sloth_iter="0"} 0
# HELP circuit_num_inputs Number of inputs to the circuit
# TYPE circuit_num_inputs gauge
circuit_num_inputs{data_size_bytes="1048576",expansion_degree="8",hasher="pedersen",layers="10",m="5",partitions="1",samples="5",sloth_iter="0"} 0
# HELP replication_time_ms Total replication timea
# TYPE replication_time_ms gauge
replication_time_ms{data_size_bytes="1048576",expansion_degree="8",hasher="pedersen",layers="10",m="5",partitions="1",samples="5",sloth_iter="0"} 14974
# HELP replication_time_ns_per_byte Replication time per byte
# TYPE replication_time_ns_per_byte gauge
replication_time_ns_per_byte{data_size_bytes="1048576",expansion_degree="8",hasher="pedersen",layers="10",m="5",partitions="1",samples="5",sloth_iter="0"} 14280
# HELP vanilla_proving_time_us Vanilla proving time
# TYPE vanilla_proving_time_us gauge
vanilla_proving_time_us{data_size_bytes="1048576",expansion_degree="8",hasher="pedersen",layers="10",m="5",partitions="1",samples="5",sloth_iter="0"} 533
# HELP vanilla_verification_time_us Vanilla verification time
# TYPE vanilla_verification_time_us gauge
vanilla_verification_time_us{data_size_bytes="1048576",expansion_degree="8",hasher="pedersen",layers="10",m="5",partitions="1",samples="5",sloth_iter="0"} 324979
```

**Comment by porcuquine** [comment]
I'm going to put diffs to the list above here. I will update this comment over time. @laser @dignifiedquire

**Comment by laser** [comment]
@dignifiedquire - I have moved on to some of the infra/ops stuff (getting benchmarks running on `master` build, queuing benchmarks on Packet, etc.). I'm going to assign this story to you since you're going to be adding additional output (e.g. circuit stuff).

**Comment by dignifiedquire** [comment]
even though not everything got done, it seems the core issues are resolved, closing
