### ISSUE TITLE
run circuit (Groth) proofs for master branch at 02:00:00 GMT each day

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#813]
### Description

Capturing the ZigZag benchmark with `--groth` enabled (for 1GiB sectors) can take several hours. If we ran this benchmark on the default Packet box (the one which captures other benchmarks on every CircleCI `master` build), this job could hog the system-wide lock and block other builds (and thus developers).

We should find a way to run circuit (Groth) proof-benchmarks once per day in a way that isn't going to block the other benchmarks (or steal CPU/RAM resources from them). A solution may be to have CircleCI priovision (with Terraform) a brand new Packet box on which it runs the circuit proof benchmarks. It'd capture the results and then destroy the Packet box. Alternatively, we could provision a long-lived Packet box used only for the long-running benchmark capture.

### Acceptance criteria

- capture circuit proof benchmarks for `master` branch HEAD at once per day at 2AM GMT
- don't steal resources from existing Packet box
- CircleCI UI should display benchmarking JSON for @porcuquine (and others) to reap

### Risks + pitfalls

- make sure @ognots won't kill me for exposing a Terraform key to CircleCI

**Comment by porcuquine** [comment]
What's the status of this? Flagging so we can record what actually happened and either integrate/use it better or explicitly abandon.

**Comment by cryptonemo** [comment]
> We should find a way to run circuit (Groth) proof-benchmarks once per day 

Closing in favor of #1396
