### ISSUE TITLE
[bug] pub const POST_SECTORS_COUNT: usize = 512 very unreasonable.

### ISSUE THREAD

**Issue by embedSky** [filecoin-project/rust-fil-proofs#830]
**Describe the bug**

the code 
```
pub const POST_SECTORS_COUNT: usize = 512;
```
in moudle rust-fil-proofs I think the value 512 is very unreasonable .

**Comment by frrist** [comment]
Hey @embedSky, this issue now exists in the appropriate repo, as @ZenGround0 has stated feel free to reopen when the aforementioned information can be provided.
