### ISSUE TITLE
Make disk the default storage for MTs

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#831]
The last implementation stage was merged in https://github.com/filecoin-project/rust-fil-proofs/pull/796. Have the `disk-trees` feature as a default.

Blockers:

* Manage generated files (at the moment we don't clean anything and it quickly fills up the disk), see https://github.com/filecoin-project/rust-fil-proofs#memory.

* Benchmark speed degradation. Recently I reported that disk-MTs may have a negligible impact of less than 5% replication time but that assessment may be incorrect and only apply to the 2x sector size case, when we still generate MTs in parallel with encoding; in the 1x case, with `FIL_PROOFS_GENERATE_MERKLE_TREES_IN_PARALLEL=0` this may have a bigger impact, we need to benchmark this, see https://github.com/filecoin-project/rust-fil-proofs/issues/826 for initial thoughts on how to improve this.

**Comment by porcuquine** [comment]
As we measure things. We should target the case of parallel generation. This needs to be the normal mode of replication, with replication time bounded by serial encoding. The goal is to minimize memory consumption *without pausing replication*. It sounds like what you are saying is that under those conditions we achieve 2x sector size memory consumption. Can you please clarify whether that is *for Merkle tree generation* or if it also includes the replica itself being encoded in memory?

**Comment by schomatis** [comment]
The easiest solution around managing files I can think of is generating temporal files that get deleted once the MT is dropped (assuming we don't allow reusing old MTs, at least for this initial iteration).

We used to need specific non-temporal files for the file-`mmap` variant (to offload the mapping temporarily and load it back again when needed) but now that has been completely replaced by the disk-only store.

**Comment by porcuquine** [comment]
I think it's okay to throw away the trees for now. In the future and in general, I think miners would prefer to keep disk-cached trees if they have the space — since generating the trees is expensive.

**Comment by schomatis** [comment]
> Can you please clarify whether that is _for Merkle tree generation_ or if it also includes the replica itself being encoded in memory?

I always benchmark memory for the entire replication process. So I think that's number 2 (I may be misinterpreting the question though).

**Comment by schomatis** [comment]
Ok, so if 2x is an acceptable RAM-to-sector-size ratio I can take care of the file management and we can move ahead with this. For parallel MT generation and encoding, replication time (will confirm with more tests) was pretty much under control, see https://github.com/filecoin-project/rust-fil-proofs/pull/796#issue-305565394 as an example.

**Comment by porcuquine** [comment]
I think that works, but we will want to reduce it a bit more, if we can.

2 x 32GiB + (N > 0) = > 64 GiB

Current thinking is that this is acceptable, but it would be much better if *all in* replication memory consumption (including the Filecoin node itself) were under 64 GiB for a 32 GiB sector.

**Comment by schomatis** [comment]
Agreed, let's push for #826 then.
