### ISSUE TITLE
Preparation for go-filecoin long-running network 0.5.x

### ISSUE THREAD

**Issue by anorth** [filecoin-project/rust-fil-proofs#849]
After the 0.4.x release (🤞), go-filecoin intends to release a 0.5 version in September. We intend this network to run for a significantly longer period of time than the ~6 weeks that has been typical to date: as a rough indication, let's say a few months. As part of this, we will be implementing a protocol upgrade mechanism, so that code can be changed without requiring a reset of the chain. A filecoin node running after a protocol upgrade must be capable of validating the chain that was computed with the pre-upgrade code, i.e. it must have both versions.

We expect to initially exercise protocol upgrades by updating actor code (e.g. implementing storage collateral and/or fault handling) and we'll work out the complexity of supporting both states. At present, we don't intend to implement a "harder" upgrade, like a consensus data structure change. Or a proof format change.

For go-filecoin to be excited about including new proofs work in the protocol-upgrading releases following 0.5, any new proofs library needs to be compatible with the proofs existing on chain. I see two ways this could be achieved:
1. implement the data objects required for Rational PoSt and any other near-term improvements *now* so that the 0.5 chain only has to deal with one type of proof for a few months
2. expand the proofs interfaces to support both new and old proofs after the 0.5 network is started

I prefer option 1, if possible, and would guess that you do too. I'm not sure what, if any, incompatibilities might be in store - maybe option 1 is trivial! But I want to make sure that the situation is clear: go-filecoin won't be able to integrate new proofs work after 0.5 (until we abandon the network, ~months) unless a backwards-compatible path is maintained for validating a chain including older versions.

If changes for RationalPoSt require integration effort in go-filecoin, we'd need those changes to land within a week or so to give us enough lead time to integrate and test before the 0.5 launch. Note that there might be shortcuts: e.g. it might be possible to defer fault checking if we just don't support any fault reporting until it's implemented by the sector builder.

@dignifiedquire @laser @porcuquine @acruikshank @Ingar @icorderi

(Originally [posted in Slack](https://filecoinproject.slack.com/archives/CEGB67XJ8/p1566867866410200))

**Comment by anorth** [comment]
The teams have since conferred and agreed to target option 1: implement and integrate the necessary changes as soon as possible so as to include in the upcoming release.

@acruikshank will own integration efforts from the go-filecoin side (and is also on point for the protocol upgrade work), with support from @ingar and, if necessary, @anorth.

**Comment by dignifiedquire** [comment]
the devnet launched, closing
