### ISSUE TITLE
implement streaming to reduce prover memory

### ISSUE THREAD

**Issue by arielgabizon** [filecoin-project/rust-fil-proofs#856]
A major roadblock for using very large circuits is the prover memory in Bellman.
 
Here are the memory usage stats of the three main components - FFT, G1 multiexp and G2 multiexp  (ack:@kevyank from Finality Labs)

FFT: 32 * N bytes 
G1 Multiexp: 128 * N bytes
G2 Multiexp: 224 * N bytes

here N is the num of R1CS constraints, what we informally refer to as circuit size.

It seems thus we can get roughly a 4-8 reduction in total memory
simply by changing the multiexp code to do the multiexp in separate buckets e.g. of size N/8
and then adding the 8 partial results   (@kevyank recommends the subvectors to be of size 1mm for GPUs).

It seems this can be done by splitting the `bases` and `exponents` vectors to 8 subvectors of size N/8 and calling `multiexp_inner` separately on each one here: 
https://github.com/zkcrypto/bellman/blob/10c5010fd9c2ca69442dc9775ea271e286e776d8/src/multiexp.rs#L237

**Comment by keyvank** [comment]
There is a parameter of type `ParameterSource` trait which is given to the `create_proof` function ([code-1](https://github.com/filecoin-project/bellman/blob/8bdf8e12a085a5fd6a2eb4435fdfc5db78f5d409/src/groth16/prover.rs#L180)) and provides the bases of the multiexp calls while generating the proofs. Currently, this trait is only implemented for `Parameters` struct, which loads all of the bases at once into the main memory ([code-2](https://github.com/filecoin-project/bellman/blob/8bdf8e12a085a5fd6a2eb4435fdfc5db78f5d409/src/groth16/mod.rs#L423), [code-3](https://github.com/filecoin-project/bellman/blob/8bdf8e12a085a5fd6a2eb4435fdfc5db78f5d409/src/groth16/mod.rs#L289)) causes the executable to crash when generating proofs for very large circuits.
As a workaround, we can provide a new implementation of `ParameterSource` that only (lazily) loads a portion of the data when needed.
In the `multiexp()` function, we run the multiexp algorithm on the first portion, remove it from the main memory, and then do the same with the next portion and so on, adding all of the results to an accumulator.
With a 8 GB ram, we should be able to process portions of size ~67mm G1 bases or ~38mm G2 bases.

**Comment by arielgabizon** [comment]
Excellent, so it seems there is already an infrastructure for this change.

Question: I quoted you above saying the FFT takes half the space when it's done "in place"
Is this the default in Bellman?

**Comment by keyvank** [comment]
Yes, the CPU version (Original bellman version) is doing the in-place approach already, we did the other way for getting more performance.

**Comment by porcuquine** [comment]
@keyvank What would it take to implement an option so provers could decide whether they want to optimize for memory or time? How much would time increase when opting for low memory with GPU?

**Comment by keyvank** [comment]
@porcuquine We'll need another FFT kernel in that case, then FFT would only require 4GB GPU memory when the memory optimization option is set. I think it will take 2/3 days to implement this.

**Comment by porcuquine** [comment]
@keyvank That sounds good. Please go ahead and work on this when priorities allow.

**Comment by porcuquine** [comment]
After further discussion, it seems the cost of this 'huge loss of performance' is not worth the benefit 'reduction from 8 to 4GB GPU RAM for FFT'. 

@keyvank Please disregard, my previous. I am closing the issue.
