### ISSUE TITLE
Increase expansion parents from 8 to 16

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#857]
To conform with new analysis (see https://github.com/filecoin-project/rust-fil-proofs/issues/827). Although straightforward we should check any potential impacts (e.g., parents cache size, replication time, change in the circuits).

**Comment by schomatis** [comment]
Ideally this should come after the changes in https://github.com/filecoin-project/rust-fil-proofs/pull/791 I think (not blocking, though).

**Comment by porcuquine** [comment]
In keeping with notes on #827, I don't think we should change the value of the parameter. I think we should instead be generating more parents given the same parameter.

**Comment by dignifiedquire** [comment]
>  I think we should instead be generating more parents given the same parameter.

In this case we would need a second parameter, or something else, that gives us the upper bound of parents, as that is critical to have, especially in light of #791

**Comment by schomatis** [comment]
Will be fixed in https://github.com/filecoin-project/rust-fil-proofs/pull/864.
