### ISSUE TITLE
Reduce size of parents cache

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#858]
The expansions parents (the only ones saved in the cache, the base ones are generated on demand) are going to be increased from 8 to 16 (https://github.com/filecoin-project/rust-fil-proofs/issues/857) which will have a considerable impact on memory consumption (when the cache is [activated](https://github.com/filecoin-project/rust-fil-proofs#speed)). The first measure to alleviate this increase is try to move the cache from memory to disk (https://github.com/filecoin-project/rust-fil-proofs/issues/855). It is also desirable (if the previous strategy doesn't work, or at least as a compliment to it) to reduce the size of the cache as much a possible. Some suggestions are scattered throughout different issues, the main ones are:

1. Use 32 bit node indexes (instead of the current `u64`) when the sector size is small enough. 
2. Do not include padding nodes.

**Comment by dignifiedquire** [comment]
parents cache is using `u32`s now
