### ISSUE TITLE
Cache merkle trees for PoSt

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#868]
### Description

We need to cache merkle trees for PoSt. It would be too expensive to generate full merkle trees for every challenged sector when generating online proofs.

The solution has two parts:

1. We should cache (on disk) the merkle trees generated for replicas when they are sealed. Metadata will need to expand to track these cached trees.

This solves the problem of expensive regeneration — but at the cost of tripling storage requirements (merkle tree is 2x sector size).

2. Later, we should implement partial merkle tree caching. Here we discard the bottom K (recommendation is 7) rows of the tree and store the rest. This has a much smaller storage overhead, while still being cheap to recompute only the sub-tree required to prove a single challenged leaf. If the storage/computation balance is not optimal, it can be tuned by changing K.

We should defer 2 for now, but we need 1. Ideally 1 will be implemented in such a way that 2 will be least incremental effort later.

**Comment by porcuquine** [comment]
As per new plan, I have assigned to @dignifiedquire for triage and tracking.

**Comment by laser** [comment]
I have discussed a tentative design with @dignifiedquire and will write a brief design doc for this before EOD.

**Comment by schomatis** [comment]
In the meanwhile I'll start extending the MT API to be able to pass an `Option<Path>` to it, `None` would mean use a temporary file (as is done now by default) and `Some(Path)` would indicate to persist the file (basically to not delete the file after we drop the MT), if the file already exists on disk it should just load its content and _not_ build (again) from the leaves. The path should be available at the `transform_and_replicate_layers` call. Does this sound good?

**Comment by dignifiedquire** [comment]
sounds roughly right to me, @laser please confirm this matches what we discussed

**Comment by schomatis** [comment]
@laser 
> Will this Option<Path> represent the (optional) path to the cached merkle tree? or will it represent the path of the directory in which the merkle tree(s) will be written?
The path should be to the _file_, the MT API shouldn't care how we administer or label our MTs.

The basic MT API is in:

https://github.com/filecoin-project/rust-fil-proofs/blob/8ac6d0a40202dab40e794ab53a3d786efced3ceb/storage-proofs/src/drgraph.rs#L31-L36

https://github.com/filecoin-project/rust-fil-proofs/blob/8ac6d0a40202dab40e794ab53a3d786efced3ceb/storage-proofs/src/layered_drgporep.rs#L395-L422

**Comment by schomatis** [comment]
Flagging here so it doesn't get lost in Slack, the major API issue between `rust-fil-proofs` and `merkletree` is that the second one stores MTs in _two_ files (so we can share the leaves, `data`, with the encoding phase and help parallelize the replication process) while the first one planned on a cache for a _single_ file per MT. Other than (which is still unresolved) the MT repo can accomodate this cache mechanism with the `DiskStore` (and it should be decided later if `VecStore` should also support it).

**Comment by dignifiedquire** [comment]
this is done
