### ISSUE TITLE
Means to detect missing verifying keys

### ISSUE THREAD

**Issue by anorth** [filecoin-project/rust-fil-proofs#875]
### Description
Due to challenges with parameter fetching/generation, go-filecoin now generates only the test-size parameters in `make deps`; larger parameters require explicit user invocation of `paramcache` (except for the undesirable lazy generation behaviour #649).

Provide a means for consumers to test for the presence of keys and any other prerequisite state so that a verifying node can fail fast if instantiated without the requisite verifying keys.

### Acceptance criteria
- An FFI call allows a consumer to check whether the verifier and prover have the keys/parameters they need.

**Comment by dignifiedquire** [comment]
@laser just as a reminder this already exists in rust land: https://github.com/filecoin-project/rust-fil-sector-builder/blob/master/sector-builder/src/builder.rs#L222

**Comment by laser** [comment]
> this already exists in rust land

Agreed. Point of clarification: We do have the building blocks to provide what @anorth has requested (i.e. there exists a `PoRepConfig#get_cache_verifying_key_path` method), but it's not yet exposed through the FFI.
