### ISSUE TITLE
Reduce PoSt memory consumption

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/rust-fil-proofs#876]
Leverage the new disk-MTs in a similar way that the `zigzag` example does.

As of now PoSt is taking 10x the sector size:

```
./fil-proofs-tooling/scripts/benchy-remote.sh rational-post --size=$((1024*1024))

"benchmarks": {
    "inputs": {
      "sector-size": 1073741824   (in bytes, not KiB)
    },
    "outputs": {
      "proving-cpu-time-ms": 2491363,
      "proving-wall-time-ms": 72149,
      "verifying-wall-time-ms": 33,
      "verifying-cpu-time-ms": 33
    }
  },
  "max-resident-set-size-kb": 11039604
}

```

**Comment by schomatis** [comment]
One place to look would be the vector allocation here:

https://github.com/filecoin-project/rust-fil-proofs/blob/8ac6d0a40202dab40e794ab53a3d786efced3ceb/filecoin-proofs/src/api/post.rs#L69-L77

**Comment by dignifiedquire** [comment]
Shouldn't this be already using DiskTrees now that they are the default?

**Comment by schomatis** [comment]
@dignifiedquire Yes, but they don't _leverage_ them (the same way we had to modify code in the `zigzag` example to do so), e.g., in the above snippet the replica file (`access`) is read into a buffer in _memory_ before being passed to the `merkle_tree` call that will convert it back to a `DiskStore` (we now use a specific `merkle_tree_from_leaves` API in `transform_and_replicate_layers` to avoid that). (Note that this is just an illustrative example and may not even be one of the main sources of the 10x memory consumption.)

**Comment by porcuquine** [comment]
Is this still a thing?

**Comment by schomatis** [comment]
Don't think so.
