### ISSUE TITLE
Integrate and test bellman with GPU

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#887]
Now that https://github.com/filecoin-project/bellman/pull/4 is merged need to

- add a `gpu` feature to filecoin-proofs and storage-proofs
- publish a new version of bellperson
- enable tests on CI to use it once we have access to GPU instances 
- do full cycle tests
- once all things are working enable it by default

**Comment by deltazxm** [comment]
Is it done?It seems to can't use GPU run bellman

**Comment by dignifiedquire** [comment]
it is implemented but disabled by default at the moment, it needs activation using the feature flag `gpu` on `filecoin-proofs`

**Comment by deltazxm** [comment]
I have already opened it,but the benchmark result is  slower than CPU.I can not believe it

**Comment by dignifiedquire** [comment]
integration is done, bug fixing and testing is ongoing
