### ISSUE TITLE
Use zkcrypto (bellman upgrade when available)

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#90]
[Apparently, these changes won't affect us until a new bellman version is released. When that happens, we should update. Until then, nothing needs to happen.]

Zcash has refactored their crypto libraries: https://github.com/zkcrypto

We should update by:

+ Use new crates.
+ Stop using old crates.
+ Modify imports.
+ Hopefully minimal changes to code itself – but this may be optimistic.

In practice this will probably be a mechanical refactor with some effort needed to first understand the new structure. It will touch many/most files, so ideally it can be done at a time when other development is either at a lull or isolated to small parts of the code base.

There is no urgency, but this needs to happen at some point. I haven't tracked closely, but it's likely that we can get the optimization to pedersen hashing they worked on for use (not sure of status) when we do this.

**Comment by dignifiedquire** [comment]
this is done, we are now using forks of the latest versions in zkcrypto
