### ISSUE TITLE
VDE encoding from Vec of 0s

### ISSUE THREAD

**Issue by merced** [filecoin-project/rust-fil-proofs#914]
Just notice in current VDE code, higher layer will be built upon 0 value Vec, possibly it's a silly question as I just missed something, but just want to confirm if this is intentional. Just feel a little bit weird that staged data are unrelated to sealed data except the replicate id. Thank you!
![image](https://user-images.githubusercontent.com/19342544/66814050-847e0780-ef68-11e9-80f6-1b1857c0aea7.png)

**Comment by dignifiedquire** [comment]
Yes this is on purpose, but not quite right, the fully right way is implemented in #915 

Some more details on this can be found in this spec PR: https://github.com/filecoin-project/specs/pull/566

**Comment by merced** [comment]
Thanks a lot!
