### ISSUE TITLE
Merkle Light Panic in replication

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#927]
likely in either building the tree for columns or the encoded data a panic occurs when replicating 8GiB

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
left: `2147479552`
right: `8589934592`

merkletree-0.11.0/src/store.rs:257:9
```

**Comment by cryptonemo** [comment]
This is the in the 'current' merkletree-0.11.0 (i.e. master)?  What's a good way to reproduce?

**Comment by dignifiedquire** [comment]
> This is the in the 'current' merkletree-0.11.0 (i.e. master)

yes

replicating with 8GiB, not sure what else yet

**Comment by dignifiedquire** [comment]
I suspect there are some issues with flushing to disk, but not sure

**Comment by dignifiedquire** [comment]
this is fixed in the latest merkle-light version
