### ISSUE TITLE
More gracefully handling out of disk space errors

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/rust-fil-proofs#943]
Currently, the code panics if it hits an out of disk space error. We can all agree that this isnt the right way to handle the problem. 

Simply returning the error back up to the user isnt the right thing to do either. The right way to handle this would be to wrap all your write operations with something that preallocates the length of the write, and if that fails *truncate* the file back down to the original size. truncation is important here, and not just deleting the file because CoW filesystems actually require additional space to perform a delete, where truncations free up space first. This doesnt *always* work, but it should tend towards not leaving the filesystem in a super borked state most of the time.

**Comment by dignifiedquire** [comment]
The way we should likely implement this is by creating a wrapper type around `std::fs::File`, which roughly looks like this


```rust
pub struct SafeFile(std::fs::File);

impl SafeFile {
    pub fn new(size: usize) -> Self {
    }
}

**Comment by dignifiedquire** [comment]
> preallocates the length of the write, 

Pretty much all of our operations already do this, the issue is that the creation in the first place fails for the most part.

proposed construction

```rust

pub trait FileExt {
  fn set_len_safe(&self, len: usize) -> io::Result<()>;
}

impl FileExt for std::fs::File {
  fn set_len_safe(&self, len: usize) -> io::Result<()> {
    // 1. stat for current len
	// 2. try calling `set_len` with new len
    // 3. if it try `set_len` with old len
  }
}
```

**Comment by dignifiedquire** [comment]
Files that we create in the `tmpfile` already get cleaned up using OS level calls, so that should not be an issue: see https://docs.rs/tempfile/ for details

**Comment by tcharding** [comment]
Noob question: do folks run this software as non-priveleged users? If so we could wrap all writes with a call to `fs2::available_space()`, and return early if there is not enough space on the filesystem to do the write.

As well as the suggested trait extension above we will likely need a wrapper for `fs::copy()`.

I came up with this while trying to find out if the `Metadata`  method `set_len()` calls `fallocate`, I was unable to ascertain this.

ref: https://docs.rs/fs2/0.4.3/fs2/

**Comment by cryptonemo** [comment]
Unclear if still needed and prior work on this was discarded in #1171.  Open a new issue if still required.
