### ISSUE TITLE
Set SectorID in [1, 2^63-1] to avoid some parse error

### ISSUE THREAD

**Issue by steven004** [filecoin-project/rust-fil-proofs#944]
### Description
This change request is from the issue submitted originally in https://github.com/filecoin-project/lotus/issues/569 by @steven004 .

When sectorId>2^63, there might result in some parse error in some lower supporting modules, after discussed, there is one preferable option is to set the sectorId not larger than 2^63-1, so that it can be parsed as int64 type too. 

Please see the discussion in [this thread](https://filecoinproject.slack.com/archives/CP50PPW2X/p1573524486427000) in slack too. 

### Acceptance criteria
sectorID is just allowed be in [1, 2^63-1], otherwise, return error. 

### Risks + pitfalls
The SectorID is an independent type in this package. This can be easily implemented by added some checks in some functions related to SectorID. 

However, in project rust-fil-sector-builder, where the initiation of last sectorID is implemented, we need to add some check there too. At the same time, to provide a multiple disk/media support, the sectorID is considered as two parts: segmentID(the first half) and Index(second half), and it is allowed to put IP address as the segmentID. we need change that too.  

Each of these changes is independent. They could be done one by one.  

### Where to begin
Revise the SectorID type related methods.

**Comment by steven004** [comment]
@dignifiedquire @laser , your opinion? This request change in rust-fil-proofs and rust-fil-sector-builder. If you agree, I could go ahead to make corresponding change.

**Comment by dignifiedquire** [comment]
see my comment in the lotus issue. I think this is a bug in the serialization.

**Comment by dignifiedquire** [comment]
closing for now as this has not come up again
