### ISSUE TITLE
Wrong type? commC&commQ

### ISSUE THREAD

**Issue by KIMQI001** [filecoin-project/rust-fil-proofs#961]
### Description
storage-proofs/src/stacked/proofs
Wrong type?
`        let mut tree_c_config =
            StoreConfig::from_config(&config, CacheKey::CommQTree.to_string(), None);   // wrong?
        let mut tree_q_config =
            StoreConfig::from_config(&config, CacheKey::CommCTree.to_string(), None);
`

**Comment by cryptonemo** [comment]
@dignifiedquire Looks like a mix-up: https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs/src/stacked/proof.rs#L808

@KIMQI001 Thanks!
